### ISSUE TITLE
replaceSymbol doesn't work on self-types

### ISSUE THREAD

**Issue by travisbrown** [scalacenter/scalafix#1000]
If you add these lines to the `ReplaceSymbol.scala` test input:
```scala
trait SomeHashMap[K, V] { this: HashMap[K, V] => }
trait AnotherHashMap[K, V] extends HashMap[K, V]
```
And these to the output:

```scala
trait SomeHashMap[K, V] { this: CoolMap[K, V] => }
trait AnotherHashMap[K, V] extends CoolMap[K, V]
```
The second will pass but the first won't, because `replaceSymbol` (and also the `.symbol` extension method for `Tree` from `scalafix.syntax`) doesn't seem to work on self-types.

We ran into this issue with the ScalaTest [Autofix](https://github.com/scalatest/autofix) migration rules, where some of our test helper classes had self-types which weren't migrated.

**Comment by olafurpg** [comment]
Thank you for reporting! I reported an issue https://github.com/scalameta/scalameta/issues/1916 There's not much we can do on the Scalafix side to fix this.

It looks like SemanticDB is not emitting occurrences for type trees in self parameters, I can try to take a look in the coming week. We recently introduced "rename symbol" in Metals, which I suspect is also suffering from the same issue.
