### ISSUE TITLE
Publish scalafix-testkit 

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scalafix#102]
The scalafix repo has nice infrastructure to test rewrites. It would be nice to expose this infrastructure as a library.

Following discussions in https://gitter.im/typelevel/catz?at=58d95d8f8e4b63533d6c470f

**Comment by olafurpg** [comment]
scalafix-testkit got merged in https://github.com/scalacenter/scalafix/pull/116 

A snapshot release should be available on bintray in ~30 minutes, along with updated docs on the webpage. However, note that we are in the process of migrating the bintray scalameta/maven repo from ivy-style to maven-style, so the artifacts may not resolve in the next 1-2 days.

**Comment by jvican** [comment]
Oh, this is super useful, I will use it myself. Thanks.
