### ISSUE TITLE
CLI tool still exits `0` after an exception

### ISSUE THREAD

**Issue by stuhood** [scalacenter/scalafix#104]
Hey @olafurpg ! Thanks for the tool.

It looks like in `0.3.2`, the CLI tool still exits with `0` after encountering the following error(s) (sent to stderr):
```
Unexpected error fixing file: Reporters.scala
Cause: java.lang.UnsupportedOperationException: scalafix.rewrite.ScalafixMirror.empty $anon#symbol requires the semantic api,
Unexpected error fixing file: Loggers.scala
Cause: java.lang.UnsupportedOperationException: scalafix.rewrite.ScalafixMirror.empty $anon#symbol requires the semantic api,
```

I'll look into the actual error with @xeno-by . But if you have time to make the edits to exit non-zero on error, it would be appreciated!

**Comment by olafurpg** [comment]
Thank you for reporting! I've opened #105 to clean up exit codes.

The cli was only recently revived thanks to introduction of the offline mirror in scalahost. However, I haven't yet exposed `--classpath/sourcepath/scalafix-nsc-pluginpath` options in the cli that are necessary to run semantic rewrites. Track #106 for updates on that front. Before v0.3.2, it was only possible to run semantic rewrites via the scalafix-nsc compiler plugin so I had given up on supporting a cli due the complexity of the integration.
