### ISSUE TITLE
Parser fails to recognize literal types using Refined

### ISSUE THREAD

**Issue by gvolpe** [scalacenter/scalafix#1045]
I've set up `scalafix` in this project: https://github.com/gvolpe/pfps-examples/pull/19, which seems to have issues recognizing literal types when using the `refined` library. This is the error I'm getting:

```scala
[error] /workspace/oss/pfps-examples/src/main/scala/meetup/TypesDemo.scala:171:44: error: identifier expected but character constant found
[error]   type EmailR    = String Refined Contains['@']
[error]                                            ^^^
[error] /workspace/oss/pfps-examples/src/main/scala/examples/newtypes/newts.scala:53:43: error: identifier expected but character constant found
[error]   type Username = String Refined Contains['g']
[error]                                           ^^^
[error] (Compile / scalafix) scalafix.sbt.ScalafixFailed: ParseError
[error] Total time: 0 s, completed Jan 11, 2020 12:11:08 AM
```

Seems to be a bug?

**Comment by johnynek** [comment]
I saw this as well:
```
[error] /home/oscar/oss/hiona/src/main/scala/dev/posco/hiona/Example.scala:156:31: error: identifier expected but integer constant found
[error]         v45lin: Option[Values[45, Identity.type]],
[error]                               ^^
[error] (Compile / scalafix) scalafix.sbt.ScalafixFailed: ParseError
```

**Comment by sebastianvoss** [comment]
Same problem here. Is there any workaround? I couldn't prevent this with any of the [suppression syntax](https://scalacenter.github.io/scalafix/docs/users/suppression.html).

**Comment by gvolpe** [comment]
It seems `scalafix` is not actively maintained at the moment (see the amount of open issues).

**Comment by olafurpg** [comment]
Fix in #1091 

There is nobody else than me right now who is actively maintaining Scalafix. I do my best to respond to some tickets but I don't have the capacity to address all issues. It would be especially great to get more help maintaining features that I know many users care about but are not relevant for our usage of Scalafix at Twitter. For example: sbt-scalafix, 2.13 support (like this issue), jdk 11

**Comment by gvolpe** [comment]
Wow thanks @olafurpg ! I understand, that's OSS :)

I said it seems it is not actively maintained because the Scala Center seems more focused on Dotty and there's no one working on this from the Scala Center (since you left).

Thanks again for looking at this :heart:

**Comment by olafurpg** [comment]
I didn't work much on Scalafix during my last year at the Scala Center. If anything, I have worked more on Scalafix since I joined Twitter :)
