### ISSUE TITLE
Scala Play Routes Files and Twirl Templates Are Not Excluded

### ISSUE THREAD

**Issue by mikail-khan** [scalacenter/scalafix#1067]
I specified an exclusion regular expression for semanticdb as follows:

```scala
.settings(scalacOptions ++= Seq("-Ypartial-unification", "-Yrangepos", "-Ywarn-unused:imports", "-P:semanticdb:exclude:^*.scala.html$|^*.routes$"))
```

but it doesn't seem to ignore those files. I am not sure if I have specified the regular expression incorrectly for sematicdb or if this is actually a bug.

You can test this by cloning the following:

https://github.com/hmrc/cgt-property-disposals-frontend/tree/CPDP-1215

**Comment by bjaglin** [comment]
Thanks for reporting @mikail-khan! It looks like the branch in your link does not exist any longer. This looks like a specific scalameta/semanticdb question/issue, could you follow-up [over there](https://github.com/scalameta/scalameta/issues) maybe? Thanks!

**Comment by olafurpg** [comment]
Thank you for reporting! Can you elaborate on what you observe and what behavior you expect? IIRC, the twirl template files are not normal Scala files, they're used an input for a source generator that prints Scala source code.

**Comment by mikail-khan** [comment]
I thought by specifying the regex to exclude routes and templates I would observe the following:

1. For routes file I would not see these type of warnings:

```scala
[warn] conf/app.routes: Unused import
[warn] conf/app.routes: Unused import
[warn] conf/app.routes: Unused import
[warn] conf/app.routes: Unused import
[warn] conf/app.routes: Unused import
```
A line is generated for each line in the routes file.

2. For Twirl template files, it complains about the comments block

```scala
[warn /button.scala.html:1:1: Unused import
[warn] @*
```

So I specified the regular expression to avoid analysing the files but the regexp seems to be ignored.

You can setup any basic Play project. Add some routes and template files. Add in scalafix. And try to compile the project. It should throw up those warnings.

**Comment by mikail-khan** [comment]
I bumped my project to 2.13.2 and I am able to silence those warnings with this:

```scala
  .settings(scalacOptions += s"-Wconf:src=${target.value}/.*:s")
```

**Comment by olafurpg** [comment]
Those errors come from the compiler are are unrelated to SemanticDB. A workaround is to silence those errors using the new `-Wconf` flag in 2.13.2.
