### ISSUE TITLE
sbt-scalafix has issues with scalaVersion 2.13

### ISSUE THREAD

**Issue by Fristi** [scalacenter/scalafix#1069]
Using `addSbtPlugin("ch.epfl.scala"     % "sbt-scalafix"        % "0.9.11")` in my build as for scalafix.

On every project I've set the `scalaVersion := 2.13.1` and include the `scalafixSemanticdb` plugin everywhere.

When I compile I get this:

```
error: Type mismatch;
  found    : Map[K, V] (value: {"scalaVersion": "2.13.1"})
  expected : scalaVersion=2.12.10
error: Type mismatch;
  found    : Map[K, V] (value: {"scalaVersion": "2.13.1"})
  expected : scalaVersion=2.12.10
[info] Running scalafix on 2 Scala sources
error: Type mismatch;
  found    : Map[K, V] (value: {"scalaVersion": "2.13.1"})
  expected : scalaVersion=2.12.10
[info] Running scalafix on 3 Scala sources
error: Type mismatch;
  found    : Map[K, V] (value: {"scalaVersion": "2.13.1"})
  expected : scalaVersion=2.12.10
```

Any remedy?

**Comment by duchoang** [comment]
I also got the same error when using this with `scalaVersion := "2.13.1"`
```
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.9.12")
```
Could anyone take a look please?

**Comment by olafurpg** [comment]
Thank you for reporting! This is a known limitation, as documented here https://scalacenter.github.io/scalafix/docs/rules/ExplicitResultTypes.html#limited-scala-support the `ExplicitResultTypes` rule only supports 2.12.1

**Comment by duchoang** [comment]
Thanks Ólafur 👍, indeed in my scalafix conf, I'm using this:
```
rules = [
   ...
   ExplicitResultTypes
]
```
After removing this rules, it worked perfectly fine.

**Comment by Fristi** [comment]
Fixed it for me as well
