### ISSUE TITLE
Scalafix + sbt 0.13 running rule from private artifactory.

### ISSUE THREAD

**Issue by vito-c** [scalacenter/scalafix#1074]
I'm using sbt 0.13.18, scala 2.11.12 and I am trying to run a scala rule that lives in our artifactory. 
```
import com.geirsson.coursiersmall.{Repository => R}
scalafixResolvers.in(ThisBuild) ++= List(
  new R.Ivy(s"https://artifacts.private/repo/blah")
)
```
When I try to run the rule I get this error:
```
[error]   org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 55; White spaces are required between publicId and systemId. (White spaces are required bet
ween publicId and systemId.)
```
If I change it to be:
```
import com.geirsson.coursiersmall.{Repository => R}
scalafixResolvers.in(ThisBuild) ++= List(
  new R.Ivy(s"https://username:pwd@artifacts.private/repo/blah")
)
```
I get unauthorized.

Here is the doc I was following.
https://scalacenter.github.io/scalafix/docs/developers/tutorial.html#adding-custom-resolver

**Comment by bjaglin** [comment]
can you reproduce this with [coursier in CLI](https://get-coursier.io/docs/cli-fetch) ? if so, you might file a ticket [upstream](https://github.com/coursier/coursier)

**Comment by scottrice10** [comment]
I believe this is answer by https://github.com/scalacenter/scalafix/pull/1228.

**Comment by bjaglin** [comment]
@vito-c please re-open if it still does not work with the syntax freshly documented in https://github.com/scalacenter/scalafix/pull/1228/files
