### ISSUE TITLE
Ensure versions are displayed correctly in docs

### ISSUE THREAD

**Issue by ckipp01** [scalacenter/scalafix#1084]
Currently in the documentation it shows that that you should install scalafix in the following way:

```scala
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.9.13")
```
However, `0.9.13` is the current version of core, not the plugin. However, the version of core gets put into the plugin here. This may not be common as they may always be in sync, but this might confuse people as they try to install and they aren't able to find the artifact, which happens currently. However, the badge is showing the correct version.

<img width="834" alt="Screenshot 2020-03-26 at 15 29 44" src="https://user-images.githubusercontent.com/13974112/77658515-19087f00-6f77-11ea-928f-07a88d4315e9.png">

**Comment by cchantep** [comment]
Now 0.9.15 is indicated, and should be compatible with Scala 2.13, but artifacts are not published.

**Comment by mlachkar** [comment]
In fact, when releasing, there is a delay that can reach some hours, between the release of sbt-scalafix, and scalafix-core.
One of the objectives of scalafix v1 is to sseparate versioning of sbt-scalafix and scalafix-core similar to sbt-scalafmt and scalafmt-core.

**Comment by cchantep** [comment]
Thx for the answer @mlachkar .
That's weird this ticket was created March 26th and many days after I still see the issue.

**Comment by mlachkar** [comment]
Right now, for example, we have the issue where the documentation is not updated despite we released 0.9.16, but there is no issue when specifying this version in your plugin conf file (all the artifacts are present).
I can't explain why this happened on March 26th, but right now, the `git tag` is referencing a detached commit for master, which is the root cause. 
We are planning to improve release documentation to avoid this issue.

**Comment by olafurpg** [comment]
>  That's weird this ticket was created March 26th and many days after I still see the issue.

@cchantep Can you elaborate? This ticket is still open.

**Comment by cchantep** [comment]
I mean for me the delay is more days than hours, so may be we're not seeing the same symptoms?

**Comment by bjaglin** [comment]
As a mitigation, sbt-scalafix and scalafix are now already released together. Actual decoupling is tracked in https://github.com/scalacenter/scalafix/issues/1146 (although there is no active work on it).
