### ISSUE TITLE
Rewrites option in CLI is ignored

### ISSUE THREAD

**Issue by jvican** [scalacenter/scalafix#110]
There are two ways of setting the rewrites to run programmatically:
  
* One via `ScalafixConfig`.
* Other one via `ScalafixOptions`.
  
The first one works in latest master, while the last one seems to be ignored. So if someone does not set the rewrites option in the config but sets them in the options, the rewrites are silently ignored.

**Comment by olafurpg** [comment]
Thank you for reporting! The `rewrites` field in ScalafixOptions was copied to ScalafixConfig in the `Cli.parse` method. This approach does not work with `Cli.runOn`. We can fix by letting `ScalafixOptions.resolvedConfig` copy `--rewrites` instead of `Cli.parse`.

**Comment by olafurpg** [comment]
This got fixed in some recent PR, I can't remember which one.
