### ISSUE TITLE
RemovedUnused seems not to work on test sources

### ISSUE THREAD

**Issue by dhs3000** [scalacenter/scalafix#1124]
I have configured Scalafix with the rule `RemovedUnused` in my project.
If I run it with `sbt scalafix` it removes the unused imports as expected, when I run `sbt test:scalafix` it compiles, the compiler warns about the unused imports, and Scalafix runs, but the files are not changed afterwards.

I created a [small test project](https://github.com/scalacenter/scalafix/files/4634283/scalafix-removeunused-bug.zip) to demonstrate the behavior.
When calling `sbt test:scalafix`, it outputs correctly that it is processing two files in the test folder, but the files stay unchanged.

I tried the rule `ProcedureSyntax` with main and test files and that works as expected.

**Comment by bjaglin** [comment]
This could be a duplicate of https://github.com/scalacenter/scalafix/issues/1110, can you try one of the workarounds described in https://github.com/scalacenter/scalafix/pull/1116 until a new `sbt-scalafmt` release is cut (with a version of scalafix that includes the fix)?

**Comment by dhs3000** [comment]
[This workaround](https://github.com/scalacenter/scalafix/pull/1116#issuecomment-627268502) helps.

Sorry, I scanned the issues for the `RemovedUnused` rule as the other rule worked on test sources.

Thank you very much :)
