### ISSUE TITLE
Scalafix failing after update do 2.13

### ISSUE THREAD

**Issue by tomasherman** [scalacenter/scalafix#1125]
Hello,

when i upgraded my project to scala 2.13, scalafix started failing with some odd errors:

```
error: error while loading AnyFunSpec, class file '/Users/hermant/Library/Caches/Coursier/v1/https/artifactory.int.avast.com/artifactory/maven/org/scalatest/scalatest_2.13/3.1.2/scalatest_2.13-3.1.2.jar(org/scalatest/funspec/AnyFunSpec.class)' is broken
(class java.lang.RuntimeException/error reading Scala signature of AnyFunSpec.class: Scala signature AnyFunSpec has wrong version
 expected: 5.0
 found: 5.2 in AnyFunSpec.class)
```

It seems like for some reason scalafix or the compiler expects `5.0` version in signature. Any idea what that might be happening? I was not able to find any proof that my project is using scala 2.12 compiler as suggested by other issues i found related to these errors. 

I use the latest scalafix version and scala 2.13.2

**Comment by bjaglin** [comment]
Could you you try one of the workaround described in https://github.com/scalacenter/scalafix/pull/1116 (which has not been released yet) ?

**Comment by jakubjanecek** [comment]
The workaround seems to work.

**Comment by tomasherman** [comment]
It seems to be working for me aswell. Thanks. It would be nice if this was documented somewhere - from docs it appears as if 2.13 is supported out of the box. Anyways, thanks again for quick help/resolution
