### ISSUE TITLE
Possible Problem With Scalafix and Shapeless Based Library?

### ISSUE THREAD

**Issue by mikail-khan** [scalacenter/scalafix#1126]
Adding code to my tests to generate arbitrary case class values using Scalacheck Shapeless causes a massive error when running Scalafix (see attached file for full error stack)

[error.txt](https://github.com/scalacenter/scalafix/files/4660088/error.txt)

**Comment by bjaglin** [comment]
Could you you try one of the workaround described in https://github.com/scalacenter/scalafix/pull/1116 (which has not been released yet) ?

**Comment by mikail-khan** [comment]
[This](https://github.com/scalacenter/scalafix/pull/1116#issuecomment-627268502) workaround solved the problem. But the [other](https://github.com/scalacenter/scalafix/pull/1116#issuecomment-627328522) suggested one did not.

**Comment by bjaglin** [comment]
can you confirm that https://github.com/scalacenter/sbt-scalafix/releases/tag/v0.9.16 fixes your problem?

**Comment by mikail-khan** [comment]
confirmed.

I had this workaround:

```scala
lazy val scalaFixTestWorkAround = Def.settings(
  scalacOptions in Test := {
    val initial = (scalacOptions in Test).value
    val semanticDbOptions = initial.filter(_.contains("-P:semanticdb:"))
    val semanticDbLess = initial.filterNot(_.contains("-P:semanticdb:"))
    semanticDbLess ++ semanticDbOptions.lastOption.toSeq
  }
)
```
removing it does not cause the error anymore.

**Comment by bjaglin** [comment]
Thanks for confirming, closing this then.
