### ISSUE TITLE
Allow rewrites to use Scalafix logger

### ISSUE THREAD

**Issue by jvican** [scalacenter/scalafix#113]
I am unsure if Scalafix uses an internal logger or not.
  
What I think it would be useful is that rewrites had access to a logger, to be able to emit errors, warnings and infos by themselves without using the precarious `println`.
  
This would allow for cleaner error messages that can reuse the already existing Scalafix infrastructure and whose severity can be filtered by Scalafix itself (and enabled via CLI flags).

**Comment by olafurpg** [comment]
This is a good idea. We could include the logger as part of the `RewriteCtx`.

**Comment by olafurpg** [comment]
I just opened https://github.com/scalacenter/scalafix/pull/118 to add support for reporting messages from rewrite to scalafix users.

**Comment by olafurpg** [comment]
Fixed in #118
