### ISSUE TITLE
Fail if -Yrangepos is missing when executing semantic rules

### ISSUE THREAD

**Issue by bjaglin** [scalacenter/scalafix#1143]
According to [semanticdb](https://scalameta.org/docs/semanticdb/guide.html#sbt) and [scalafix](https://scalacenter.github.io/scalafix/docs/users/installation.html#sbt) user documentation, `-Yrangepos` is mandatory but there is nothing that enforces that.

I spent quite some time debugging a `RemoveUnused` execution that was cleaning up unused privates but leaving unused locals untouched, despite relevant entries in semanticdb's diagnostics. It turned out the range of the diagnostics for them [was not matching was what in the tree](https://github.com/scalacenter/scalafix/blob/v0.9.16/scalafix-rules/src/main/scala/scalafix/internal/rule/RemoveUnused.scala#L85), so no action was taken.

I am not sure which features the lack of `-Yrangepos` can impact, so I wonder if we should add a check (and fail verbosely if the flag is missing):
1. in the semanticdb plugin?
1. in scalafix before semantic rules execution?
1. in semantic rules themselves, on a case-by-case basis? https://github.com/scalacenter/scalafix/blob/1564a4b7eec87e16f2c6bce233848c6b542eb966/scalafix-rules/src/main/scala/scalafix/internal/rule/RemoveUnused.scala#L31-L39

**Comment by dwijnand** [comment]
Eugene (@eed3si9n)'s recently brought up finally switching the compiler to range positions: https://github.com/scala/scala-dev/issues/472, so this problem might become moot.

That said, there's no certainty that that will happen, so you might want to resolve this issue nonetheless.

**Comment by olafurpg** [comment]
I believe the SemanticDB compiler plugin fails compilation when Yrangepos is disabled. Could this have changed in recent Scala versions?

**Comment by bjaglin** [comment]
> I believe the SemanticDB compiler plugin fails compilation when Yrangepos is disabled. Could this have changed in recent Scala versions?

Could be, for the record, I ran into this with Scala 2.13.2 & sbt-scalafix 0.9.16.

**Comment by mcanlas** [comment]
Is `rangepos` required for all methods of inclusion? Not all of the examples listed at https://scalacenter.github.io/scalafix/docs/users/installation.html#sbt have it included.

**Comment by bjaglin** [comment]
I am closing this as it is now confirmed that this will no longer be a problem in scala 2.13, see https://contributors.scala-lang.org/t/range-positions-yrangepos-will-be-on-by-default-in-2-13-4/4506.
