### ISSUE TITLE
scalafix-interfaces: expose rewrites as patches

### ISSUE THREAD

**Issue by bjaglin** [scalacenter/scalafix#1154]
Current situation as of Scalafix 0.9.17:
- https://github.com/scalacenter/scalafix/blob/v0.9.17/scalafix-interfaces/src/main/java/scalafix/interfaces/ScalafixDiagnostic.java only exposes lint patches
- Rewrites diffs (as generated by java-diff-utils) can be observed by inspecting stdout with the `ScalafixMainMode.STDOUT` mode, but are not really actionnable

Goal:
- `scalafix-interfaces` clients should be able to decide when, how and which rewrites are applied

Client use cases:
- implement local refactoring actions in an IDE via Scalafix rules (https://github.com/scalameta/metals-feature-requests/issues/18?)
- attach actionable diffs to updated lines within the code review UI (using https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/incorporating-feedback-in-your-pull-request#applying-a-suggested-change through https://github.com/reviewdog/reviewdog for example)

Possible implementations:
1. change the behavior of `ScalafixMainMode.STDOUT` to produce an actionnable diff using a format like [unified diff](https://en.wikipedia.org/wiki/Diff#Unified_format)
1. introduce `ScalafixMainMode.STDOUT_UNIFIED_FORMAT` to expose an actionnable diff using a format like [unified diff](https://en.wikipedia.org/wiki/Diff#Unified_format)
1. add a `ScalafixMainCallback.reportRewrite(ScalafixRewrite rewrite)` with `ScalafixRewrite` being something similar to https://github.com/java-diff-utils/java-diff-utils/blob/java-diff-utils-parent-4.7/java-diff-utils/src/main/java/com/github/difflib/patch/Patch.java, which gets called for all `ScalafixMainMode`s.

Limitations:
- Since (Scalafix) patches are applied sequentially, the information of which rule requested the rewrite is tricky to expose, and depends on application of "previous" rules rewrites, so clients willing to segregate rewrites by rules would have to run scalafix once per rule.

**Comment by olafurpg** [comment]
This is a good idea! I'm 👍 for approaches 2 and 3. Approach 2 is already kind of implemented with the --check flag
```sh
❯ scalafix -r ProcedureSyntax --check project/Dependencies.scala
--- /Users/lgeirsson/dev/scalafix/project/Dependencies.scala
+++ <expected fix>
@@ -2,7 +2,7 @@
 /* scalafmt: { maxColumn = 120 }*/

 object Dependencies {
-  def foo {
+  def foo: Unit = {

     println(42)
   }

```

I guess the only required change would be to replace `<expected fix>` with the file path.

**Comment by olafurpg** [comment]
Looping in @mlachkar since I think she was working on something related for Metals
