### ISSUE TITLE
sbt-scalafix: enable caching by default?

### ISSUE THREAD

**Issue by bjaglin** [scalacenter/scalafix#1164]
There has not been any user feedback about the caching feature introduced as opt-in in https://github.com/scalacenter/sbt-scalafix/pull/102 and documented in https://github.com/scalacenter/scalafix/pull/1139. It's most likely because few users have scalafix enabled as part of the compilation and really need that incremental compilation.

I am still opening this to track the known limitations and gauge the interest of potentially making caching an opt-out rather than an opt-in.

#### Known false positives (cache-hit while it should cache-miss):
1. Only source files are stamped, so a classpath change or `scalacOptions` update could alter the bytecode and/or the semanticdb file and/or what the presentation compiler exposes to complex rules like `ExplicitResultTypes`, but the rule will not be re-executed. See (3) in https://gitter.im/scalacenter/scalafix?at=5ea6b3b43d7e50071c34fd67.
1. ~https://github.com/scalacenter/scalafix/issues/1164#issuecomment-656567498~ https://github.com/scalacenter/sbt-scalafix/pull/145

#### Known shortcomings (cache-miss while it could cache-hit):
1. ~successive runs with different rules invalidate the previous cache, so sequential runs like https://github.com/typelevel/cats/pull/3424#issue-421860342 cannot make use of it~
   * addressed in https://github.com/scalacenter/sbt-scalafix/pull/139
1. usage of [rules compiled on the fly](https://scalacenter.github.io/scalafix/docs/developers/tutorial.html#run-the-rule-from-source-code) disables caching
1. `--tool-classpath` disables caching
1. `--stdout` invocations are not cached

**Comment by bjaglin** [comment]
A thought: caching could be enabled by default for any "permanent" Scalafix setup (scalac options & SemanticDB compilre plugin), but remain disabled by default for adhoc/`scalafixEnable` usages (where it's not really making a difference anyway).

**Comment by bjaglin** [comment]
Considering that `--check` is used mostly on CI, maybe it does not make sense to share the cache for rewrite & check invocations: `--check` would imply `--no-cache`, reducing further the risk of false positive on CI.

**Comment by bjaglin** [comment]
As a first step, I am proposing to automatically [enable caching when scalafix runs as part of compile](https://github.com/scalacenter/sbt-scalafix/pull/140), since that's where it's the most useful.

**Comment by olafurpg** [comment]
I think I just discovered a bug in `scalafixCaching`. Steps to reproduce:

* run `scalafixAll`, all files are fixed producing diffs
* run `scalafixAll`, cached so no files are fixed even if the input files have changed from the initial `scalafixAll`

Example, in the logs below I had edited a single file and then I ran `scalafixAll` twice in a row. The first `scalafixAll` produced a diff so I expected the second run to trigger Scalafix again.

```diff
-- obtained
++ expected
sbt:sbt-scalafix> scalafixAll
[info] Compiling 1 Scala source to /Users/lgeirsson/dev/sbt-scalafix/target/scala-2.12/sbt-1.0/classes ...
[info] Running scalafix on 1 Scala sources (incremental)
[success] Total time: 4 s, completed 10-Jul-2020 10:53:28
sbt:sbt-scalafix> scalafixAll
[info] Compiling 1 Scala source to /Users/lgeirsson/dev/sbt-scalafix/target/scala-2.12/sbt-1.0/classes ...
+ [info] Running scalafix on 1 Scala sources (incremental)
[success] Total time: 2 s, completed 10-Jul-2020 10:53:33
```

**Comment by bjaglin** [comment]
Thanks for the clear report! I think it also applies to the `scalafix` task itself. I believe the problem comes from the fact that input file stamping happens after execution of all rules, to avoid re-running scalafix again. But that is correct only if we have a single rule invoked, which is not checked... I'll remove the unsafe optimization and simply stamp before rule execution.

**Comment by bjaglin** [comment]
> As a first step, I am proposing to automatically [enable caching when scalafix runs as part of compile](https://github.com/scalacenter/sbt-scalafix/pull/140), since that's where it's the most useful.

This was shipped as part of https://github.com/scalacenter/sbt-scalafix/releases/tag/v0.9.19, so I am closing this.

**Comment by bjaglin** [comment]
We have been using caching for over a year now (before I upstreamed it), and we haven't had any problem with it nor bug reports, so I wonder if it would make sense to make it the default now? It's currently enabled only if `scalafixOnCompile` is turned on.
