### ISSUE TITLE
RemovedUnused not working if -Wconf:any:warning-verbose

### ISSUE THREAD

**Issue by jeffrey-aguilera** [scalacenter/scalafix#1178]
`-Wconf:` options were added in Scala 2.13.2. `warning-verbose` includes category and location in logging output, which is apparently being parsed to find the unused imports.

**Comment by bjaglin** [comment]
Thanks for the report! For the record, https://github.com/scalacenter/scalafix/pull/1163 recently reduced false negatives when checking against `scalacOptions` in `RemoveUnused`.

Regarding the usage of `-Wconf`: from my understanding it's only a way to filter/change the logging level of compiler warnings, but it does not enable them as such. Could you post an example of code / scalacOptions for which you would expect `RemoveUnused` to run?

**Comment by bjaglin** [comment]
@jeffrey-aguilera are you still running into that? thanks!
