### ISSUE TITLE
ExplicitResultTypes don't rewrite implicit members of local traits

### ISSUE THREAD

**Issue by ohze** [scalacenter/scalafix#1180]
# Input
```scala
/*
rule = ExplicitResultTypes
ExplicitResultTypes.skipLocalImplicits = false
*/
package test.explicitResultTypes

class ExplicitImplicitTypesTest {
  trait T
  def f(): T = new T {
    implicit val i = 1
  }
  def g(): Unit = {
    class C {
      implicit val i = 1
    }
  }
}
```
# Output
Two `implicit val i = 1` above are not rewritten.
# Expectation
Should rewrite to `implicit val i: Int = 1` because the code above don't compile in dotty.

I test with dotty 0.24.0 and 0.25.0-RC2 => error: `type of implicit definition needs to be given explicitly`.

**Comment by giabao** [comment]
In fact, `skipLocalImplicits = false` config has no effect. ExplicitResultTypes still do not rewrite the following code:
```scala
class C {
  def g(): Unit = {
    implicit val i = 1
  }
}
```
