### ISSUE TITLE
sbt-scalafix 0.9.7 uses older semanticdb incompatible with Scala 2.13.3

### ISSUE THREAD

**Issue by exoego** [scalacenter/scalafix#1183]
Current latest sbt-scalafix `0.9.7` with the default `scalafixSemanticdb.revision` are failing to download `semanticdb-scalac_2.13.3`.
So, if the default `scalafixSemanticdb.revision` is used, sbt-scalafix is not usable for project using Scala 2.13.3:

```
[error] (myProject / update) sbt.librarymanagement.ResolveException: Error downloading org.scalameta:semanticdb-scalac_2.13.3:4.3.14
[error]   Not found
[error]   Not found
[error]   not found: /home/vagrant/.ivy2/local/org.scalameta/semanticdb-scalac_2.13.3/4.3.14/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.13.3/4.3.14/semanticdb-scalac_2.13.3-4.3.14.pom
[error]   not found: https://oss.sonatype.org/content/repositories/releases/org/scalameta/semanticdb-scalac_2.13.3/4.3.14/semanticdb-scalac_2.13.3-4.3.14.pom
```

If `semanticdbVersion` is manually configured to [4.3.18](https://github.com/scalameta/scalameta/releases/tag/v4.3.18), sbt-scalafix works:

```scala
inThisBuild(
  List(
    semanticdbEnabled := true,
    // semanticdbVersion := scalafixSemanticdb.revision, 
    semanticdbVersion := "4.3.18", 
    Configs.isProductionRelease := false
  )
)
```

However, I would like to avoid overriding `scalafixSemanticdb.revision` as much as possible, since it is uncelar which version of scalameta is compatible with sbt-scalafix.
And, the specified version won't be updated when newer sbt-scalafix is released...

I expect sbt-scalafix automatically find latest scalameta version, or new version of sbt-scalafix aligning are published when new version of scalameta published.

**Comment by bjaglin** [comment]
This was fixed on master by https://github.com/scalacenter/scalafix/pull/1179, so it's pending release.

Regarding automating that: as you probably saw, we have scala steward helping us keeping upstream dependencies up to date, and https://github.com/scalacenter/scalafix/issues/1146 will soon make it possible to bump scalafix-core (and thus semanticdb) independently of sbt-scalafix (which will make the release process easier and thus reduce delays), so the situation should improve.

**Comment by exoego** [comment]
Thanks.
I will open a PR for https://github.com/fthomas/scala-steward/issues/1514 so Scala Steward can update `semanticdbVersion` too.

**Comment by bjaglin** [comment]
sbt-scalafix 0.9.18 is out
