### ISSUE TITLE
sbt-scalafix 0.9.18 failed to fetch scalafixDependencies

### ISSUE THREAD

**Issue by exoego** [scalacenter/scalafix#1201]
* Scala 2.13.3
* sbt-scalafix 0.9.18
* OpenJDK 11.0.7

`build.sbt`
```scala
ThisBuild / scalafixDependencies ++= Seq(
  "org.scala-lang" %% "scala-rewrites" % "0.1.1"
)
inThisBuild(
  List(
    semanticdbEnabled := true, // enable SemanticDB
    semanticdbOptions += "-P:semanticdb:synthetics:on",
    semanticdbVersion := scalafixSemanticdb.revision,
    scalafixScalaBinaryVersion := CrossVersion.binaryScalaVersion(scalaVersion.value),
  )
)
```

Running `scalafixAll fix.scala213.ExplicitNonNullaryApply` causes 

```
[error] (scalafixAll) scalafix.sbt.InvalidArgument: Failed to fetch [Dependency(Module(com.github.liancheng, organize-imports_2.13), 0.3.1-RC3), Dependency(Module(org.scala-lang, scala-rewrites_2.13), 0.1.1)]from [IvyRepository(file:/home/vagrant/.ivy2/local/[organisation]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier]).[ext], dropInfoAttributes = true), MavenRepository(https://repo1.maven.org/maven2), MavenRepository(https://oss.sonatype.org/content/repositories/public), MavenRepository(https://oss.sonatype.org/content/repositories/snapshots)]
```

**Comment by bjaglin** [comment]
Thanks for the report. It looks like your `build sbt` is incomplete as I don't see any mention of `com.github.liancheng %% organize-imports`. Can you check that so I can reproduce the issue? Thanks.

**Comment by exoego** [comment]
Ah sorry, the error message is for build.sbt with iorganize-imports.
However, even without organize-imports, the same error still happens.

**Comment by bjaglin** [comment]
This looks like a problem with scala-rewrites, I can't see 0.1.1 published in https://repo1.maven.org/maven2/org/scala-lang/scala-rewrites_2.13/, can you follow up there?

**Comment by dwijnand** [comment]
Oops, didn't notice the tag build fail.  Restarted it and everything's there now:

* https://repo1.maven.org/maven2/org/scala-lang/scala-rewrites_2.12/0.1.1/
* https://repo1.maven.org/maven2/org/scala-lang/scala-rewrites_2.13/0.1.1/

**Comment by exoego** [comment]
@bjaglin @dwijnand 
This issue is now resolved.
Thanks for quick response 🙇 !
