### ISSUE TITLE
Cross-build by default in scalafix.g8

### ISSUE THREAD

**Issue by bjaglin** [scalacenter/scalafix#1202]
As a follow-up to https://github.com/scalacenter/sbt-scalafix/pull/121, https://github.com/scalacenter/scalafix.g8/blob/4d491493ae947a962ff4bf10e368cca161540219/scalafix/build.sbt#L5 should cross-build by default to 2.11, 2.12 & 2.13. Users can always opt-out if it's too demanding (but we should probably have a warning explaining what is the impact of doing so).

Related discussion: https://github.com/scalacenter/scalafix/issues/1108#issuecomment-647402044

**Comment by mlachkar** [comment]
Done here https://github.com/scalacenter/scalafix.g8/pull/14
