### ISSUE TITLE
ExplicitResultTypes should backquote identifiers if necessary

### ISSUE THREAD

**Issue by jrudolph** [scalacenter/scalafix#1219]

**Comment by danicheg** [comment]
Hey! I've faced this issue too. A repro is plain: 
```scala
case class `Foo-Bar`(baz: Int)

val foobar = `Foo-Bar`(42) // before
val foobar: Foo-Bar = `Foo-Bar`(42) // after. Leads to "not found: type -" error
```
If someone could share some insights on fixing this, I could give it a try.

**Comment by bjaglin** [comment]
@danicheg A PR would be welcome!

You can add your test case in https://github.com/scalacenter/scalafix/tree/main/scalafix-tests/output/src/main/scala-2/test/explicitResultTypes.

The actual fix is probably on https://github.com/scalacenter/scalafix/blob/58de77035898032b3cc258a36cfdb0afac56f628/scalafix-rules/src/main/scala/scalafix/internal/rule/CompilerTypePrinter.scala#L112

Scalameta's prettyprinter [handles backquoting when needed](https://github.com/scalameta/scalameta/blob/dd4801a937c4ecf292c949f9179ee5f3ca0d8272/scalameta/trees/shared/src/main/scala/scala/meta/internal/prettyprinters/TreeSyntax.scala#L134-L221), so I would start by investigating why it's not used.
