### ISSUE TITLE
Local build instructions don't work

### ISSUE THREAD

**Issue by japgolly** [scalacenter/scalafix#1231]
Hi! I followed the instructions in https://scalacenter.github.io/scalafix/docs/developers/local-rules.html and added new SBT modules. The only modification I made was to comment out the test module due to #1230, everything else is the same.

When I try to run the rules, it tries to download the underlying module:

```
> sbt
root> base-util-jvm/scalafix shipreq
[warn] 
[warn] 	Note: Unresolved dependencies path:
[error] stack trace is suppressed; run last base-predef-jvm / update for the full output
[error] (base-predef-jvm / update) sbt.librarymanagement.ResolveException: Error downloading com.beardedlogic.shipreq:scalafix-rules_2.12:b50ebdb8ad4bed0b453ecf3e0db4fe68490530cc-dev-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: ~/.ivy2/local/com.beardedlogic.shipreq/scalafix-rules_2.12/b50ebdb8ad4bed0b453ecf3e0db4fe68490530cc-dev-SNAPSHOT/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/com/beardedlogic/shipreq/scalafix-rules_2.12/b50ebdb8ad4bed0b453ecf3e0db4fe68490530cc-dev-SNAPSHOT/scalafix-rules_2.12-b50ebdb8ad4bed0b453ecf3e0db4fe68490530cc-dev-SNAPSHOT.pom
```

**Comment by japgolly** [comment]
I got this working somehow.
I'm not sure exactly what the problem was but for anyone else with a similar problem:

I have a set of common settings that all my SBT modules use. It sets things like the scala version, scalac flags, etc. In order to make this work I had to make two changes:
1. create another version of the common settings and remove all scalafix settings
2. make sure all scalafix modules use the new common settings

So the reason I had this failure is that either, there was a necessary setting the modules weren't getting before, and/or the usual scalafix settings mustn't be applied to the rules module.

**Comment by bjaglin** [comment]
Thanks for reporting & documenting!

> and/or the usual scalafix settings mustn't be applied to the rules module

That sounds like it - which scalafix settings are you referring to?

**Comment by japgolly** [comment]
Good question! To be honest I didn't even bother looking, but now that I do, this is what I was referring to:

```scala
  val scalafixSettings: Project => Project =
    if (scalafixEnabled)
      _.enablePlugins(ScalafixPlugin).dependsOn(ScalafixBuild.`scalafix-rules` % ScalafixConfig)
    else
      _.disablePlugins(ScalafixPlugin)
```

**Comment by bjaglin** [comment]
Could it be that `scalafix-rules` itself was getting that `.dependsOn(ScalafixBuild.`scalafix-rules` % ScalafixConfig)`? I would have expected a more verbose sbt failure in that case though.
