### ISSUE TITLE
Explore ways to consolidate Patch and Rewrite

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scalafix#124]
From https://gitter.im/scalacenter/scalafix?at=58eecfd28bb56c2d11a16ebd

> Shane Delmore @ShaneDelmore 03:09
> @olafurpg I still have some confusion about Patch vs Rewrite. I have a sample AddGlobalImport, and don't fully understand how it is a Patch and not a Rewrite. https://github.com/ShaneDelmore/cbt/blob/10ef4c952149d1a9f52a707f36fafcdcbcc66d28/examples/cross-rewrite-example/build/build.scala#L44
> In this case, I really want to add it only if it is needed, for example if Either.map is used in the file, but in that case I need a Rewrite, not a Patch, and it seems they cannot be used in the same places.
> 
> Shane Delmore @ShaneDelmore 03:27
> How exactly is AddGlobalImport a patch? It seems like a rewrite, it must need a context right?
> Or some sort of PseudoPatch? It doesn't feel like quite the same thing as "replace these tokens with some other tokens".
> 
> Ólafur Páll Geirsson @olafurpg 09:54
> @ShaneDelmore Great question. I've thought a lot about how to consolidate Patch and Rewrite.
> AddGlobalImport is in one form a rewrite that only produces TokenPatches
> While a rewrite can return TreePatches
> The reason AddGlobalImport is not a rewrite is becuase 1. it needs to run last and 2. it requires a rewrite ctx + all import patches from other rewrites

Some current issues:

- Too many concepts: Patch/TreePatch/TokenPatch, Rewrite, RewriteCtx, Mirror, RewriteCtx[Any], ...
- Still easy to do dangerous stuff, like create RemoveGlobalImport (which require semantic info) from a syntactic rewrite (triggers runtime error in `Patch.apply`)

**Comment by olafurpg** [comment]
OK, here's a draft of potential approach to simplify things. It still keeps  `Patch` but

- gets rid of all `T <: Patch` in the public facing
- requires semantic patches like AddGlobalImport to prove they have a `RewriteCtx[Mirror]` in scope
- automatically handles flattening of `Seq[Seq[Patch]]`/`Option[Patch]`/...

```scala
class Rewrite[T] {
  def rewrite(ctx: RewriteCtx[T]): Patch // not Seq[Patch], use Patch.++ to combine patches
}
sealed abstract class Patch {
  def syntax: String // code after applying this patch
  def syntaxDiff: String // diff between original code and code after applying this patch
  def structure: String // show underlying patches  "addGlobalImport(...) + remove(...)"

  // combinators
  def +(other: Patch): Patch
  def ++(other: Seq[Patch]): Patch // Maybe something Option[Patch]

  // syntactic tree patches
  def remove(tree: Tree): Patch
  def replace(tree: Tree, toReplace: String): Patch

  // syntactic token patches
  def remove(tok: Token): Patch
  def replace(tok: Token, toReplace: String): Patch
  def addLeft(tok: Token, toAdd: String): Patch
  def addRight(tok: Token, toAdd: String): Patch

  // semantic tree patches
  def addGlobalImport(i: Importer)(implicit ctx: RewriteCtx[Mirror]): Patch
  def removeGlobalImport(i: Importer)(implicit ctx: RewriteCtx[Mirror]): Patch
  def renameSymbol(from: Symbol, to: Name)(implicit ctx: RewriteCtx[Mirror]): Patch
  // ...
}
object Patch {
  val empty: Patch // starting point
}
```

Implementation details like TokenPatch/TreePatch/AddGlobalImport/RemoveGlobalImport/... would be marked `private[scalafix]`. This would be quite a breaking change for existing rewrites. However, I think we are still in such an early stage that we we should try to optimize for the cleanest design.

PS. This design is partly inspired from `Doc` in [paiges](https://github.com/johnynek/paiges/blob/master/core/src/main/scala/com/github/johnynek/paiges/Doc.scala)

**Comment by ShaneDelmore** [comment]
I love the ability to look at results after the patch is applied, but Patch.syntax doesn't give me much hint that it is the result of the code being applied.

What about Patch.result?  After? Applied? Outcome?

The object Patch simplification is really nice.  I can tell right from the signatures and names what they do.

**Comment by olafurpg** [comment]
I'm glad you like the idea.

> What about Patch.result? After? Applied? Outcome?

I agree `.syntax` is not great. I like `.applied`/`.appliedDiff` better.

One more thing, the syntactic patches will also need to take an implicit `RewriteCtx[Any]` (type aliased to `SyntacticRewriteCtx` or similar) as well. I think that's necessary to support `.applied`

**Comment by ShaneDelmore** [comment]
In the case of using the compiler plugin, once it is instantiated it will have it's own RewriteCtx so I won't need to provide one separately with the Seq[Patch], is that correct?

**Comment by olafurpg** [comment]
> won't need to provide one separately with the Seq[Patch]

What do you mean by that?

By requiring a `RewriteCtx` to create patches, it won't be longer possible to run simple programs like

```scala
val patched = Patch(Seq(AddGlobalImport(???)))
```
Instead, you will need to go via a `Rewrite`

```scala
val patched = Rewrite.syntactic{ implicit ctx => Patch.addGlobalImport(???)}.applied

**Comment by ShaneDelmore** [comment]
I think I may just be wording this poorly. To continue with the AddGlobalImport example, this is not really a think you would ever do by itself right?  What you really want is If(GlobalImportNeeded) AddGlobalImport. And how do you know if the import is needed without a context? Also, AddGlobalImport needs a context to run doesn't it?  It is not syntactic only, so I am not understanding why I need to pass a context to my check if the global import is needed, but not to actually add the global import. I will spend more time with the code today and see if the answer becomes more clear.

**Comment by olafurpg** [comment]
> this is not really a think you would ever do by itself right? 

I think there are valid cases where you might want to explicitly add an import. For example, `scala.collection.immutable.Seq` or `import scala.Predef.{any2StringAdd => _}`.

> , but not to actually add the global import. 

You need to prove you have a semantic context in scope to add global import, since it's not syntactic.

One way to look at it is that AddGlobalImport as a mid-level construct. It's not low-level because it's not a token-level patch, but it's not high-level either because you still need to figure out if the import is actually needed or not. In some cases, I think it will always be necessary to manually manage if an import is needed, for example `import foo.syntax._` or `import foo.{Bar => Kaz}`.

> What you really want is If(GlobalImportNeeded) AddGlobalImport.

What do you think about adding higher level-constructs than AddGlobalImport that work something like "I want in insert `Bar` with underlying symbol `_root_.foo.Bar.`"? That patch would then take care of inserting imports if those are needed. I think that is a great idea.

**Comment by olafurpg** [comment]
I have one issue with 

```
object Patch {
  def addGlobalImport(i: Importer)(implicit ctx: RewriteCtx[Mirror]): Patch
}
```

I think it's a bit awkward to pass in the implicit for every patch, what do you think about adding extension methods to `RewriteCtx[Mirror]` instead? The syntax then becomes
instead

```scala
import scalafix._
// before
Rewrite.semantic(implicit ctx => Patch.addGlobalImport(importer"foo.bar") + Patch.???)
Rewrite.semantic(ctx =>
  ctx.addGlobalImport(importer"foo.Bar") +
  ctx.renameSymbol(symbol"_root_.kas.A", q"B") 
```

**Comment by olafurpg** [comment]
I have a WIP branch refactoring Rewrite and Patch to use this new design: https://github.com/scalacenter/scalafix/compare/master...olafurpg:ctx.patch?expand=1 I hope to get it ready for a PR tomorrow.

Enforcing constraints on the type-level opens up so many questions. Interesting bugs and question practically discovered by the compiler while refactoring. The main open ones are

- What to do with `ScalafixConfig.rewrites: Seq[Rewrite[ScalafixMirror]]`? ScalafixMirror is going away. Options are to either
  1. type parameterize ScalafixConfig (preferable), or
  2. move rewrites field out of ScalafixConfig
- settle on signature of `Patch.applied`? Should it take a context or should the context already be be included in the underlying patches created with `ctx.addGlobalImport`

The breaking changes are quite large so I'm happy to personally migrate any existing code using the current rewrite api. Don't hesitate to ping me about this.

It's possible and quite easy to provide an automatic migration for rewrites that `extend Rewrite[T]`. However, some code I've seen for example in the cbt scalafix plugin the `Rewrite[T]` api is not so much used. I believe it's better to manually migrate in those cases.

**Comment by ShaneDelmore** [comment]
Regarding the different api choices, for whatever it is worth, they send slightly different messages to me regarding intent.  

The implicit context says "I want to add a global import, and I need a context to help me accomplish the task" where ctx.addGlobalImport says "I want to add a global import to this context".  The second version does seem clearer to me, plus it helps people auto-complete their way to appropriate things to do to the context which is always helpful when learning a new api.

**Comment by olafurpg** [comment]
Thank you @ShaneDelmore for starting the discussion on Gitter about your confusion between Patch and Rewrite. I believe that the new rewrite api in #127 makes this distinction clearer

- A Patch can produce a unified diff/.patch file.
- A Rewrite produces a Patch given a RewriteCtx. 

It is no longer possible to bypass rewrites to create patches, since TreePatch and TokenPatch are now `private [scalafix]` and the only way to create patches is through this api here https://github.com/scalacenter/scalafix/blob/master/scalafix-core/src/main/scala/scalafix/rewrite/SemanticPatchOps.scala which requires a RewriteContext in scope. 

I will write more docs on the new api and I offer to manually migrate any scalafix rewrites that were written against the old API. Don't hesitate to take me up on that offer @ShaneDelmore. The migration has some mechanical steps, but I believe a manual migration would be a good experience for me to do.

**Comment by ShaneDelmore** [comment]
That is a very generous offer but rewriting them myself will help me get practice with the new api.  I want to start adding rewrites to imclipitly soon to allow to to generate simple fixes for mechanical problems found so I should have good cause to exercise the new api in a couple of weeks.

**Comment by olafurpg** [comment]
Sounds good, you can check out the rewrites in this repo (like https://github.com/scalacenter/scalafix/blob/cff7ae8f46eb127be29f2c3ad308bbfe894d846f/scalafix-core/src/main/scala/scalafix/rewrite/Xor2Either.scala) for examples of how the new api looks like.
