### ISSUE TITLE
Stale symbol information when using sbt 1.3x injection style

### ISSUE THREAD

**Issue by mcanlas** [scalacenter/scalafix#1245]
I recently changed my scalafix settings from

```scala
addCompilerPlugin(scalafixSemanticdb)
```

to

```scala
semanticdbEnabled := true,
fixSemanticdb.revision
```

as documented at https://scalacenter.github.io/scalafix/docs/users/installation.html

We've started to see non-deterministic errors like 

```
warning: [OrganizeImports] Could not determine whether 'scala' is fully-qualified because the symbol information is missing. We will continue processing assuming that it is fully-qualified. Please check whether the corresponding .semanticdb file is properly generated.
[warn] import scala.concurrent.duration.DurationInt
```

Does anyone know what the difference between these two injection styles is and/or what causes the above error?

**Comment by mcanlas** [comment]
Maybe related to https://github.com/liancheng/scalafix-organize-imports/pull/90

**Comment by bjaglin** [comment]
Thanks for the report @mcanlas! From my understanding, you are seeing different behavior for the `OrganizeImports` rule depending on the way the semanticdb compiler plugin is set up in your sbt project, right? Do `show allDependencies` / `show Compile/scalacOptions` differ depending on how it's set up?

**Comment by mcanlas** [comment]
When I use the newer style (`semanticdbEnabled`), I can see references to `-P:semanticdb:targetroot` in `show Compile/scalacOptions`

The older style (that works) has no `targetroot` keys at all.

**Comment by bjaglin** [comment]
Right, it looks like `-P:semanticdb:targetroot` is set by default in https://github.com/sbt/sbt/blob/dd00fc6cbe6dffa463136428d0bf0917eba80a3b/main/src/main/scala/sbt/plugins/SemanticdbPlugin.scala#L55.

When manually injecting `-P:semanticdb:targetroot` in `scalacOptions`, do you get the same (faulty) behavior as when using the sbt 1.3.x style?

I haven't been able to reproduce the problem locally, so any further details would be welcome.

**Comment by mcanlas** [comment]
@taisukeoe I saw in a change you committed below

https://github.com/scalacenter/scalafix/commit/a578a83a4f9995c160ebc72c1a0eac3fb06a8985

that differentiated between SBT versions. Could you explain the nature of this change and how it works?

**Comment by taisukeoe** [comment]
@mcanlas 
The nature of this change is to follow the new standard way, which is introduced at https://github.com/sbt/sbt/pull/4410 .

This `semanticdbEnabled` style has some different sbt Key wirings than explicit project-wise `addCompilerPlugin` style. That's why sbt `semanticdbEnabled` style works in `ThisBuild` scope.

https://github.com/sbt/sbt/pull/4410/files#diff-6d9589bfb3f1247d2eace99bab7e928590337680d1aebd087d9da286586fba77R446 .

If there is any problem on this `sbt` key wiring, it would be nicer to reproduce this issue, and then confirm if this issue should be resolved on scalafix side or sbt side.

**Comment by bjaglin** [comment]
@mcanlas are you still experiencing the issue? a repro is needed if we want to move forward with this
