### ISSUE TITLE
Undocumented option symbolReplacement for ExplicitResultType

### ISSUE THREAD

**Issue by mlachkar** [scalacenter/scalafix#1246]
```
rules = ExplicitResultTypes
ExplicitResultTypes.skipSimpleDefinitions = false
ExplicitResultTypes.symbolReplacements {
  "test/explicitResultTypes/SymbolReplacement.DefaultTimer." = 
    "test/explicitResultTypes/SymbolReplacement.Timer#"
  "test/explicitResultTypes/SymbolReplacement.Dog#" = 
    "test/explicitResultTypes/SymbolReplacement.Animal#"
}
```

**Comment by olafurpg** [comment]
This option is intentionally undocumented since it’s only intended to be used for internal needs. My experience with publicly documenting “low-level” configuration like this is that many users end up struggling to get it working according to their expectations/hopes and you end up spending a lot of time addressing questions on gitter or answering issues on GitHub.

**Comment by olafurpg** [comment]
I’m not opposed to documenting this option, just wanted to share the risks of doing so

**Comment by mlachkar** [comment]
Thanks for your advice. I also think that this feature shouldn't be documented, and maybe shouldn't be part of the ExplicitResultType. I will close this issue.

**Comment by olafurpg** [comment]
I just remembered now the original motivation to add this feature. The rule was inserting a singleton type in a lot of cases where we wanted to widen the type to a supertype
```diff
-- obtained
++ expected
class Timer
object DefaultTimer extends Timer

trait MyTrait { def myTimer: Timer }
class MyClass extends MyTrait {
-  override def myTimer: DefaultTimer = DeaultTimer
+  override def myTimer: Timer = DeaultTimer
}
```
We currently don't enforce `ExplicitResultTypes` in our codebase at Twitter, but if we were to do that we would most likely need to have the ability to override this configuration option.
