### ISSUE TITLE
Shorter URI syntax for rewrites

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scalafix#125]
Following up on a discussion with @xeno-by. It would be nice if it was possible to configure rewrite with a short memorable syntax. For example,

```
github:olafurpg/scalafmt/1.0 => http://github.com/olafurpg/scalafix-scalafmt/blob/master/scalafmt/rewrites/src/main/scala/Scalafmt10.scala
```

The `github:` protocol could maybe even be automatically inferred, if this syntax becomes popular. I believe such a short syntax would help library authors give concise migration instruction for their users on how to run the scalafix migration script.

Related:

- https://www.scala-js.org/news/2017/03/21/announcing-scalajs-0.6.15/
- https://github.com/scalameta/scalameta/blob/master/changelog/1.7.0.md

**Comment by gabro** [comment]
@olafurpg the example you mention assumes a default path for rewrites (`/rewrites/src/main/scala`), a default branch (`master`) and a default name `ProjectnameVV.scala`.

Is this something you intend to enforce/suggest as default?

**Comment by olafurpg** [comment]
Yes, I was thinking of writing a simple spec for how a `<rewrite>` cli arg is expanded into a rewrite. Any feedback on what the spec should be is welcome!

I was thinking that maybe the project name should include the version number in it, so you can have a separate project per rewrite, to avoid classpath conflicts. I was also thinking of supporting `scalameta/1.7` as a shorthand for `scalameta/scalameta/1.7`.

**Comment by olafurpg** [comment]
Btw, I just merged #127 which significantly cleaned up runtime compilation of rewrites. The relevant piece of code that expands a uri into a url is here https://github.com/scalacenter/scalafix/blob/b98411b08e8347fc53c5ab2eeeee563b1dbf72ef/scalafix-reflect/src/main/scala/scalafix/reflect/ScalafixCompilerDecoder.scala#L27

If someone wants to take a stab at this, I'm happy to give more pointers. A good place to test this would be next to the integration test here https://github.com/scalacenter/scalafix/blob/b98411b08e8347fc53c5ab2eeeee563b1dbf72ef/scalafix-tests/src/it/scala/scalafix/tests/URLConfiguration.scala

**Comment by gabro** [comment]
That makes sense, it will greatly help in achieving a consistent way of shipping rewrites.
Not sure about the branch though, I'm worried that `master` couldn't not be a strong default. Maybe the ability of optionally specifying the branch/tag/tree-ish could be useful?
Something along the lines of

```
scalameta/scalameta/1.7?sha=v1.7
```

**Comment by gabro** [comment]
I can take a stab at this, it should be easy enough. A draft spec could be

```
github:<ORG>/<PROJECT>/<VERSION>
```

expands to

```
http://github.com/<ORG>/<PROJECT>/blob/master/scalafmt/rewrites/src/main/scala/<PROJECT><VERSION>.scala
```

Then we can build on top of it, does it make sense?

**Comment by olafurpg** [comment]
Awesome!

What do you think about?
```
github:<ORG>/<PROJECT>/<VERSION>
http://github.com/<ORG>/scalafix-<PROJECT>/blob/master/<REPO>/rewrites-<VERSION_NORMAL>/src/main/scala/<PROJECT><VERSION_NORMAL>.scala
```
where VERSION_NORMAL is a `".replaceAll("[^\\d]", "_")`.

Note that the project name is prepended with `scalafix-`, the same way `olafurp/homebrew-scalafmt` is aliased as `olafurpg/scalafmt` in homebrew.

Regarding the branch name, I like the idea of supporting it as query parameter `?sha=master`. That will allows for more reproducibility.

**Comment by gabro** [comment]
oh, so it's always going to be a separate project `scalafix-<PROJECT>`? So far I assumed that rewrites would've been shipped withing the original project. Was this discussed before? I'm interested in the reasoning behind it!

**Comment by gabro** [comment]
Also what would `<REPO>` be in your example above?

**Comment by olafurpg** [comment]
There hasn't been a public discussion about it yet, just in my head :)

My reasoning for having a separate project was in order to not pollute the main project with rewrite code. We could use the project's main with separate branch like `scalafix-rewrites`, but that would mean that all users fetch the rewrite branch when cloning the repo. In scalameta/scalameta, we only have a master branch and I think we would prefer to keep it that way if possible. WDYT?

**Comment by olafurpg** [comment]
> Also what would <REPO> be in your example above?

My bad, that was supposed to be PROJECT, I updated the comment

**Comment by gabro** [comment]
I see.

I'm wondering whether having two repos per library would be too much of a hurdle for maintainers.
In my head, I've always imagined rewrites to live in the same repo, in a `rewrites` directory - say - next to `src` and `tests`.
A pro of this approach would be to keep the code together with the rewrites, allowing atomic releases of new versions (new code + rewrite).
It is also probably easier to integrate the `rewrites` project into existing tooling (sbt, CI, code coverage).

Would be great to hear from the people that are going to use this.

**Comment by olafurpg** [comment]
I can see how a project that's part of the main repo and main build can also be useful. The lower the barrier of entry to doing the rewrites the better! Considering that your original proposal doesn't exclude library authors from creating a separate github project and telling users to run `ORG/scalafix-rewrites/1.0` then I'm favor of your original proposal with the modification that 

1. the `rewrites` project would be renamed into `scalafix-rewrites`. Maybe I'm just being paranoid, but I want to avoid the situation where `rewrites` is already an existing sbt project in the build. 
2. the .scala file is inside the PROJECT.scalafix package so that you don't have to keep the file in the empty package or inserting a custom package name and deal with IntelliJ offering to move the file into another subdirectory.

```
github:ORG/PROJECT/VERSION?sha=SHA
// expands into
http://github.com/<ORG>/<PROJECT>/blob/<SHA>/<PROJECT>/scalafix-rewrites/src/main/scala/<PROJECT>/scalafix/<PROJECT><VERSION>.scala
```

WDYT?

**Comment by gabro** [comment]
Looks fine to me, I think it's flexible enough for various use cases that I can imagine.
Only one thing I'm not sure about, what's the `<PROJECT>` after the `<SHA>` for? It seem a bit inconvenient for mono-library repos.

(also, how to I run the test suite at https://github.com/scalacenter/scalafix/blob/b98411b08e8347fc53c5ab2eeeee563b1dbf72ef/scalafix-tests/src/it/scala/scalafix/tests/URLConfiguration.scala ?)

**Comment by olafurpg** [comment]
One concern I had with keeping all rewrites in a single project was that you may hit on classpath conflict issues in the test suite. However, I think it will be possible to circumvent that by adding support for use a custom classpath per test suite in scalafix-testkit https://scalacenter.github.io/scalafix/#scalafix-testkit 

Then you can write unit tests with some syntax like this

```
$ cat Scalameta17.source
dependencies = "org.scalameta:scalameta:1.7.0"
rewrites = "fqn:org.project.Scalameta1_7"
<<< test name
object Foo
>>>
object Bar
```
and scalafix-testkit would take care of compiling those sources with the classpath of that dependency

**Comment by olafurpg** [comment]
> Only one thing I'm not sure about, what's the PROJECT after the SHA for?

Ignore that, I thought it was necessary but apparently it's not :)

> (also, how to I run the test suite at https://github.com/scalacenter/scalafix/blob/b98411b08e8347fc53c5ab2eeeee563b1dbf72ef/scalafix-tests/src/it/scala/scalafix/tests/URLConfiguration.scala ?)

`> ~tests/it:testOnly *URL*` is what I run. I put it in the IntegrationTest config since it does http requests and I don't think unit tests should do network calls.

One last think, what do you think if VERSION_NORMAL is prepended with an underscore `_`? That would mean that the `scalameta/scalameta/1.7` rewrite would be named `Scalameta_1_7`. Also, what do you think about doing this transform on PROJECT in the filename?

```
@ "asdfasdJKLJKH".toLowerCase.capitalize
res1: String = "Asdfasdjkljkh"
```

Anyways, I trust you'll figure out the implementation details for what that we haven't discussed yet. Let me know if you hit on any issues 😄

**Comment by gabro** [comment]
Thanks for the pointers, yep, I agree on both the `capitalize` (I've implemented it that way already) and on the `_` as well. Expect a PR soon! :)

**Comment by Blaisorblade** [comment]
Hi @olafurpg !
Saw a link to this issue and wondered: Are version migrations "cumulative" or not? Is this somehow handled by scalafix or by the user? I asked @gabro briefly, and he told me to ask here.

To sketch it out: Say a library L has different APIs for versions 1.5, 1.6, 1.7, and I prepare Scalafix migrations for L across these versions.

1. Users have to compose migrations by hand (or prepare precomposed migrations). This is easiest.
Then `VERSION` is just an arbitrary string for Scalafix.

2. You can ask Scalafix to migrate from 1.5 to 1.7, and Scalafix figures out included migrations. This can be more convenient but requires more choices. For some scenarios it's clearly overkill, maybe not always?
You'd also need to give a semantics to `VERSION` (at least, an ordering) to figure out included migrations, which can get overly tricky in general I guess. Maybe just make VERSION an increasing natural, like Android API levels?

**Comment by olafurpg** [comment]
@Blaisorblade 

>  Are version migrations "cumulative" or not? Is this somehow handled by scalafix or by the user?

At the moment, a rewrite is a program that produces a single patch file. To use the semantic api, which is necessary for example to work on symbols, the original source file needs to typecheck before running scalafix.

It's possible to compose rewrites in the library with `rewriteA.andThen(rewriteB)`, but it's up to the rewrite author if that composition makes sense. At the moment, scalafix does nothing "smart" to automatically compose rewrites in behalf of the library author or library user. Scalafix does not fiddle with build settings either.

Imagine that a library author releases a version number X where the old api has deprecation warnings and the new api exists. In these cases, the user should be able to
1. upgrade from an old version number to version X by bumping up the dependency in the build settings,
2. run `sbt compile` and see a bunch of deprecation warnings, 
3. run `sbt scalafix foo/bar/X`, which should write the resulting patch to file. There may be a `scalafixDiff` task to print the patch to the console
4. run `sbt compile` with no more deprecation warnings

I'm open for suggestions on how to make stuff like `scalafix X Y` work to migrate from version X to Y, but for now I think it's best to focus on keeping things as simple as possible.
