### ISSUE TITLE
Error message not exposed in the API

### ISSUE THREAD

**Issue by tgodzik** [scalacenter/scalafix#1250]
It seems the error message that actually has a message is currently not possible to retrieve:

https://github.com/scalacenter/scalafix/blob/4f113a708c6ebf6ba0f948e85c417383a1a5b139/scalafix-cli/src/main/scala/scalafix/internal/interfaces/ScalafixFileEvaluationImpl.scala#L27

Should we just add an additional method to retrieve it?

CC @mlachkar

**Comment by tgodzik** [comment]
Also it seems the error is always `UnexpectedError`

**Comment by mlachkar** [comment]
So in scalafix, a lint error is considered as an error, but scalafix has run successfully, but this Option[messageError] will contain a messagee error, if scalafix was not able to run.

**Comment by mlachkar** [comment]
I would like to change the isSuccesful to make make it false only if there an UnexpectedError, which will indicate that the message error will be Some(messageError).
It's a little confusing

**Comment by tgodzik** [comment]
Isn't that error message that I pointed out to an actual error message? It does seem to indicate an issue withing scalafix and not a linting one.

**Comment by mlachkar** [comment]
I added a message error to scalafixFileEvaluation and fixed the `Unexpected Error`. 
It should be better
