### ISSUE TITLE
Add rewrite to remove unused imports

### ISSUE THREAD

**Issue by jvican** [scalacenter/scalafix#126]
I would like a Scalafix rewrite that removes unused imports. This rewrite is useful for unclutter the name scope of a Scala file where names are unused.
  
In an informal discussion with @olafurpg, he suggested me to parse compiler error messages to implement this functionality since the current scalahost compiler plugin is being deprecated. Olaf suggests that the API entrypoint is `.messages: Seq[CompilerMessage]`.
  
I will provide an implementation for this some time in the future, if someone doesn't beat me to it!

**Comment by olafurpg** [comment]
This got fixed in https://github.com/scalacenter/scalafix/pull/166
