### ISSUE TITLE
0.9.24: loss of meaningful braces

### ISSUE THREAD

**Issue by rossabaker** [scalacenter/scalafix#1299]
In http4s, since upgrading to 0.9.24, we're seeing a loss of braces that were preserved in 0.9.23.  Input:

```scala
    final def doFetchR2[B](req: Request[G], f: Response[G] => G[B])(implicit G: Sync[G]): G[B] =
      fetch[B](req) { f }
```

Diff:

```scala
     final def doFetchR2[B](req: Request[G], f: Response[G] => G[B])(implicit G: Sync[G]): G[B] =
-      run(req).use[G, B] f
+      run(req).use[G, B] { f }
```

It's also affecting more complex expressions, like partial function literals.  Input:

```scala
  def doClientFetchR5[F[_]: Sync, A](client: Client[F], req: Request[F], f: Response[F] => F[A]): F[A] = {
    client.fetch[A](req) { case res@Response(_, _, _, _, _) => f(res) }
  }
```

Diff:

```scala
   def doClientFetchR5[F[_]: Sync, A](client: Client[F], req: Request[F], f: Response[F] => F[A]): F[A] = {
-    client.run(req).use[F, A] case res@Response(_, _, _, _, _) => f(res)
+    client.run(req).use[F, A] { case res@Response(_, _, _, _, _) => f(res) }
```

I don't have a minimization yet, but it can be observed from `sbt ++2.12.12 scalafixTests/test` on https://github.com/http4s/http4s/pull/3943/commits/b4f0ca5632b534b74576ce21ca3e2cb79b657c1a.

Could this be related to the scalameta-4.4.0 upgrade?

**Comment by bjaglin** [comment]
Thanks for the report. I have reproduced the problem with scalafix 0.9.24, as well as with master that now includes scalameta-4.4.2. I'll try to find some time in the coming days to extract a repro from https://github.com/http4s/http4s/tree/main/scalafix/rules/src/main/scala/fix to file a ticket in scalameta as it does seem related to the bump.

**Comment by rossabaker** [comment]
I haven't connected it to a scalameta bump, but our tests are passing again with 0.9.25.

Thanks!
