### ISSUE TITLE
Boilerplate generator for rewrite

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scalafix#132]
If I'm a library author and I want to provide migration rewrites as github:org/repo/v1.0 then I need to manually calculate the expanded filepath and create the necessary file/directory structure. It would be nice if the scalafix cli could generate this with a command like

```bash
$ scalafix generate github:org/repo/v1.0
Created rewrite boilerplate!
Main: scalafix-rewrites/src/main/scala/org/repo/scalafix/Repo_1_0.scala
Test: scalafix-rewrites/src/Test/scala/org/repo/scalafix/Repo_1_0Test.scala
```

cc/ @gabro

**Comment by olafurpg** [comment]
I hit on this while preparing my talk for Scala Romandie. I'm wondering if we should change the cli interface to use commands. 

```bash
# before
scalafix --rewrite github:a/b/1.0 foo.scala
# after
scalafix rewrite github:a/b/1.0 foo.scala
```

**Comment by gabro** [comment]
I was scratching my head about this one too. A generator/scaffolder would be great, I was also considering giter8 (the one `sbt new` uses) but I don't know how flexible it is.

**Comment by gabro** [comment]
I was also thinking that the generator could pre-populate a `.source` file for diff testing.

**Comment by olafurpg** [comment]
g8 is great for users but it in my experience it has been a hassle to use for writing generators. The way g8 handles variable replacement is simply buggy and I've found it hard to test that the generated project works as advertised.

I would like to invest more in the scalafix cli as I believe this should be quite easy to implement. Installing the command line tool will probably be as easy as
-  `brew install scalacenter/scalafix/scalafix` on Mac o
- downloading a bootstrap script or
- copy-pasting a coursier command like https://scalacenter.github.io/scalafix/#scalafix-cli

**Comment by olafurpg** [comment]
> I was also thinking that the generator could pre-populate a .source file for diff testing.

I agree, was just thinking that :)

**Comment by olafurpg** [comment]
Another issue with g8 is that I haven't seen it used for incremental generation. I want this to play nicely in an existing project

**Comment by gabro** [comment]
Ok, I have zero experience with g8 so I'll trust your judgment.
Anyway, yes, I think an incremental way of adding the boilerplate for a rewrite is crucial for a good user experience.

**Comment by gabro** [comment]
@olafurpg superseded by #233?

**Comment by olafurpg** [comment]
Yes, after more experimenting with g8 I think it's actually pretty great. It has some quirks which I think can be improved but it's better to contribute to g8 than to reinvent the wheel here.
