### ISSUE TITLE
sbt-scalafix: drop support for sbt 0.13

### ISSUE THREAD

**Issue by bjaglin** [scalacenter/scalafix#1333]
It is probably a good time to drop support for sbt 0.13 - sbt 1.0 was released 3,5 years ago.

Benefits/TODO:
- use scala 2.12 features
- get rid of the [1.0/0.13 compatibility layer](https://github.com/scalacenter/sbt-scalafix/tree/master/src/main/scala-sbt-1.0/sbt/internal/sbtscalafix)
- use slash notation (in code and in docs)
- restructure scripted to run most (all?) of them against different sbt 1.x versions, like https://github.com/thesamet/sbt-protoc/pull/196

**Comment by bjaglin** [comment]
Considering that it most likely won't be particularly harder to ship https://github.com/scalacenter/scalafix/issues/1146 with sbt 0.13 support, I think it would be nice to hold this just a little longer, so that clients stuck to sbt 0.13 can still benefit from future versions of scalafix itself. Once that's done, then I think it's really safe to drop support and leverage newer sbt features.

**Comment by mlachkar** [comment]
We can maybe close this ticket now ?

**Comment by bjaglin** [comment]
Why? The work hasn't started.

**Comment by mlachkar** [comment]
ok. I thought we dropped support of sbt 0.13 in sbt-scalafix, but I am wrong. https://github.com/scalacenter/sbt-scalafix/pull/219
We dropped support of 0.13 for testkit only.
