### ISSUE TITLE
Remove unused doesn't remove unused pattern vars when inside a method

### ISSUE THREAD

**Issue by mlachkar** [scalacenter/scalafix#1343]
To reproduce the issue:
```
  def test(): Unit = {
    example match {
      case AB(a, b) => println("Not used, wrong")
    }
  }
```
The regex used to catch the diagnostic message is too specific to values

**Comment by vincenzobaz** [comment]
My tests were not complete enough. Thank you for catching this.
Please let me know if #1345 solves it
