### ISSUE TITLE
Remove -Xfatal-warnings scalac option in scalafixEnable

### ISSUE THREAD

**Issue by fthomas** [scalacenter/scalafix#1346]
`-Xfatal-warnings` (or `-Werror`) might prevent a Scalafix rule from being applied if a project does not compile without warnings with the Scala version set by `scalafixEnable`. I noticed this while testing a Scalafix migration rule for Cats Effect (https://github.com/scala-steward-org/scala-steward/pull/1982) in Scala Steward itself. Scala Steward uses `-Xfatal-warnings` and sbt-scalafix 0.9.26 but is still on Scala 2.13.4. I tested the migration rule via `sbt ;scalafixEnable ;scalafix github:typelevel/cats-effect/v2_4_0?sha=series/2.x` and noticed that it couldn't be applied because compilation fails under Scala 2.13.5 which introduced new warnings. Scala 2.13.5 is used instead of 2.13.4 because `scalafixEnable` also changes the `scalaVersion`. If I remove `-Xfatal-warnings` from `scalacOptions` in the build, compilation succeeds and the Scalafix rule is applied.

This is not really an issue if one runs the Scalafix manually (since one can always remove that option by hand) but it is more problematic when Scalafix is used in automation. One example is when Scala Steward runs Scalafix migration rules in other projects as part of its update PRs. It currently does this by adding the latest sbt-scalafix version to the build of the project it is updating and then running `sbt ;scalafixEnable ;scalafix ...`. If that project is using `-Xfatal-warnings` it could run into the situation mentioned above which prevents the Scalafix rule from being applied.

I tried to salvage this in Scala Steward by adding another sbt command that is executed after `scalafixEnable` which removes `-Xfatal-warnings` from all sbt projects but this is unfortunately not possible due to bug in sbt: https://github.com/sbt/sbt/issues/5459. I therefore propose that [`scalafixEnable`](https://github.com/scalacenter/sbt-scalafix/blob/v0.9.26/src/main/scala/scalafix/sbt/ScalafixEnable.scala) also removes `-Xfatal-warnings` and `-Werror` from `scalacOptions` to make using sbt-scalafix easier in projects where the actual `scalaVersion` and the one set by `scalafixEnable` differ.

**Comment by bjaglin** [comment]
As [discussed on gitter](https://gitter.im/sbt/sbt?at=603e779ad71b6554cd189f3d), I think it's a good idea. I was concerned about relaxing `-Xfatal-warnings` for the entire session after `scalafixEnable`, but I think I got something decent with https://github.com/scalacenter/sbt-scalafix/pull/195. Could you confirm this PR addresses your use case?

**Comment by fthomas** [comment]
Just tested it and it works like a charm. Thank you @bjaglin!

**Comment by bjaglin** [comment]
@fthomas https://github.com/scalacenter/sbt-scalafix/pull/292 should benefit steward by avoiding some of the challenges described above, your feedback is welcome.
