### ISSUE TITLE
Discussion: Using scalafix for scala-based DSLs

### ISSUE THREAD

**Issue by soronpo** [scalacenter/scalafix#144]
In continuation to [a discussion on gitter](https://gitter.im/scalacenter/scalafix?at=59033cfd8e4b63533d11ed94), I'm opening this issue for discussion, as @olafurpg suggested.

I would like to use scalafix to do the following.
* **Provide `if` virtualization** I am working on a DSL library and need to replace all `if`s to a definition call and change their semantics (not in my library, but for the library users). Preferably I would like to limit the replacement to a specific DSL-boolean type. E.g., `if (bool : DSLBool) then {} else {}` would be replaced, while `if (bool : Boolean) then {} else {}` remains untouched. How will this interact with IDEs (IntelliJ), since `if (bool : DSLBool)` is not supposed to compile normally (I can provide a pseudo implicit conversion from `DSLBool` to `Boolean`)?
* **finite `for` unrolling** Also for my DSL library, I would like an ability to unroll (limited) finite `for` expressions. Preferably, I would like to unroll `for`s just for compilation check, but leave them rolled at byte-code. The reason for this is that the DSL library provides many compile-time checks, which aren't called due to the default run-time nature of `for` expressions.

I also want to mention that I'm considering scalafix for this because I don't want to the users of the DSL to use `@DSL` annotation explicitly all over their code. It is enough that they include the proper statements in the sbt file, and everything should work 'magically'. For this specific DSL, it is important scalafix won't break proper IDE interaction.

**Comment by olafurpg** [comment]
@soronpo Thank you for opening up this issue. After some more thinking after our last conversation, I believe scalafix is not a good fit for your use-case. Scalafix is focused on doing token-level rewrites, producing patches that respect trivia such as formatting/comments and can be committed back into VCS. Scalafix can maybe also be used as a code-generator to cross-build against source incompatible scala/library versions, although that use-case has not been explored much yet.

I believe def macros will be a better suite for you use-case. Your options are to either use scala-reflect, which has been used to implement DSLs (I personally worked on https://github.com/directembedding/directembedding, see https://geirsson.com/assets/directembedding-report.pdf). Alternatively, if you can wait, keep a close eye on the developments in https://github.com/scalamacros/scalamacros
