### ISSUE TITLE
Custom rules from plain console

### ISSUE THREAD

**Issue by arbitrary-dev** [scalacenter/scalafix#1463]
Is there a way to use OrganizeImports from plain console?

```
$ cs install scalafix

$ scalafix dependency:OrganizeImports@com.github.liancheng:organize-imports:0.5.0
Missing --rules

$scalafix dependency:OrganizeImports@com.github.liancheng:organize-imports:0.5.0 --rules OrganizeImports
error: Unknown rule 'OrganizeImports'
```

**Comment by bjaglin** [comment]
Hi @arbitrary-dev! The syntax you are trying to use is only supported with `sbt-scalafix`, the scalafix plugin for sbt. Is there something you found in the docs that confused you and could be improved?

To load community rules, the `scalafix` CLI can:
- run [simple rules from source](https://scalacenter.github.io/scalafix/docs/developers/tutorial.html#run-the-rule-from-source-code): not relevant with `OrganizeImports` as the code is spread over several files
-  use a [custom classpath for execution via `--tool-classpath`](https://scalacenter.github.io/scalafix/docs/users/installation.html#help): this requires downloading the JAR first (with coursier for example)

But in any case, you will see that using the CLI with *semantic* rules like `OrganizeImports` can be cumbersome, as you need the target sources to be compiled with semanticdb information, and the right directories to be passed as arguments. Quite often, this is done through a build tool, so if possible, I advise you to use one of the current integration instead (the official sbt plugin, or [community-maintained plugins for other build tools](https://scalacenter.github.io/scalafix/docs/users/installation.html#plugins-for-other-build-tools)).
