### ISSUE TITLE
Add a rewrite rule to add `final` to `case class`

### ISSUE THREAD

**Issue by mdedetrich** [scalacenter/scalafix#1468]
Idiomatically  `case class`es in Scala should be written as `final`. The reason why `case class`es should be final is that a lot of the features that Scala brings to the table when using `case class` (such as destructuring) relies on the generated methods not being overridden (specifically `equals`/`hashCode`). If a `case class` is not final, a user can theoretically subclass a `case class`, override something like `equals`, feed that subclasses `case class` into your code and then suddenly things break. If you need to do these things you should be using a normal `class` (of which there is no problem having it non final).

Scalafix should provide a rule out of the box that users can configure which automatically adds `final` to all `case class`es in the code.

**Comment by bjaglin** [comment]
Thanks for the suggestion! Actually, this [used to be a built-in rule](https://github.com/scalacenter/scalafix/pull/827), but it has been extracted to https://github.com/vovapolu/scaluzzi, so I suggest you to try it out and follow-up there if `MissingFinal` does not do what you need.
