### ISSUE TITLE
Scalafix on Windows: OverlappingFileLockException

### ISSUE THREAD

**Issue by etspaceman** [scalacenter/scalafix#1510]
We seem to be hitting an `OverlappingFileLockException` when the `scalafixAll --check` command is run on the cats-effect Windows CI boxes. See https://github.com/typelevel/cats-effect/runs/4564105278?check_suite_focus=true

**Comment by armanbilge** [comment]
copy-pasta b/c GH logs aren't forever :)

```
[error] java.nio.channels.OverlappingFileLockException
[error] 	at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
[error] 	at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
[error] 	at java.base/sun.nio.ch.FileChannelImpl.lock(FileChannelImpl.java:1252)
[error] 	at java.base/java.nio.channels.FileChannel.lock(FileChannel.java:1089)
[error] 	at lmcoursier.internal.shaded.coursier.paths.CachePath.withStructureLock(CachePath.java:144)
[error] 	at lmcoursier.internal.shaded.coursier.cache.CacheLocks$.withStructureLock(CacheLocks.scala:21)
[error] 	at lmcoursier.internal.shaded.coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:38)
[error] 	at lmcoursier.internal.shaded.coursier.cache.internal.Downloader$Blocking$.remote(Downloader.scala:382)
[error] 	at lmcoursier.internal.shaded.coursier.cache.internal.Downloader.$anonfun$remote$5(Downloader.scala:480)
[error] 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:659)
[error] 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
[error] 	at scala.util.Success.map(Try.scala:213)
[error] 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[error] 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[error] 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[error] 	at java.base/java.lang.Thread.run(Thread.java:833)
[error] (kernelJS / update) java.nio.channels.OverlappingFileLockException
```

**Comment by bjaglin** [comment]
Thanks for the report!

It looks related to https://github.com/coursier/coursier/issues/2018 - both sbt-scalafix and scalafix use coursier via coursier-interface 1.0.4, so I understand from that ticket that it can be a source of conflict with the usage of coursier via sbt.

[coursier-interface 1.0.5](https://github.com/coursier/interface/releases/tag/v1.0.5) was relased a few days ago, pulling-in [a lot of changes from coursier](https://github.com/coursier/coursier/compare/v2.0.15...v2.1.0-M2#). However, none of these changes seem to impact the stack trace above, so I doubt the bumps (https://github.com/scalacenter/sbt-scalafix/pull/268 & https://github.com/scalacenter/scalafix/pull/1511) will help.

Before following-up in https://github.com/coursier/coursier, could you still try to reproduce the problem with the scalafix nightlies containing the coursier-interface 1.0.5 bumps?
```scala
// project/plugins.sbt
resolvers += Resolver.sonatypeRepo("snapshots")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.9.33+12-b6b1b28d-SNAPSHOT")
dependencyOverrides += "ch.epfl.scala" % "scalafix-interfaces" % "0.9.33+12-4b7dd8bf-SNAPSHOT"
```
Thanks!

**Comment by bjaglin** [comment]
Did you get the chance to reproduce the problem on the latest versions? No need to use the snapshots mentioned above, the bumps were included in the latest stable releases.

**Comment by etspaceman** [comment]
Seems to be working on the latest sbt-scalafix! Thanks for the update

**Comment by bjaglin** [comment]
Thanks for checking!
