### ISSUE TITLE
search on scalafix documentation is not working anymore

### ISSUE THREAD

**Issue by mlachkar** [scalacenter/scalafix#1514]

**Comment by daddykotex** [comment]
With the webtools:

![Screen Shot 2022-01-10 at 15 18 26](https://user-images.githubusercontent.com/5230460/148833413-0f4c6609-45ce-4b1d-9cf4-c3bffa265d72.png)


It seems like the configuration on Algolia has changed. In text:

```
Uncaught (in promise) r {name: 'AlgoliaSearchError', message: 'Index scalafix does not exist', debugData: Array(1), statusCode: 404, stack: 'AlgoliaSearchError: Index scalafix does not exist\n…livr.net/docsearch.js/1/docsearch.min.js:3:11081)'}debugData: [{…}]message: "Index scalafix does not exist"name: "AlgoliaSearchError"statusCode: 404stack: "AlgoliaSearchError: Index scalafix does not exist\n    at p (https://cdn.jsdelivr.net/docsearch.js/1/docsearch.min.js:3:11081)"[[Prototype]]: Error
Promise.then (async)
(anonymous) @ docsearch.min.js:2
update @ docsearch.min.js:5
e @ docsearch.min.js:5
n @ docsearch.min.js:4
C.each @ docsearch.min.js:4
s.each @ docsearch.min.js:4
update @ docsearch.min.js:5
_onQueryChanged @ docsearch.min.js:5
r @ docsearch.min.js:5
a @ docsearch.min.js:5
_checkInputValue @ docsearch.min.js:5
_onInput @ docsearch.min.js:5
o @ docsearch.min.js:4
r.proxy @ docsearch.min.js:4

```

**Comment by mlachkar** [comment]
Trying to create a new index on algolia website. I don't understand what happened!

**Comment by ckipp01** [comment]
> Trying to create a new index on algolia website. I don't understand what happened!

Algolia just sent out info about this to admins (we got it for Metals), and it looks like need to migrate to an actual algolia account to get it to work. I'll forward you the email we got which should give you some insight.

**Comment by mlachkar** [comment]
So in fact there is a migration, but the issue was due to a wrong http url that was not redirecting anymore to the scalafix website! https://github.com/algolia/docsearch-configs/issues/5025
