### ISSUE TITLE
Docs point to out-of-date / broken named-literal-arguments repo

### ISSUE THREAD

**Issue by swoogles** [scalacenter/scalafix#1518]
After cloning the project referenced here:
https://scalacenter.github.io/scalafix/docs/developers/tutorial.html#import-the-build

And executing `sbt tests/test`, the results are:
```
[error] /home/bfrasure/Repositories/named-literal-arguments/scalafix/tests/src/test/scala/fix/Namedliteralarguments_Tests.scala:5:43: not found: type SemanticRuleSuite
[error] class Namedliteralarguments_Tests extends SemanticRuleSuite() {
[error]                                           ^
[error] /home/bfrasure/Repositories/named-literal-arguments/scalafix/tests/src/test/scala/fix/Namedliteralarguments_Tests.scala:6:3: not found: value runAllTests
[error]   runAllTests()
[error]   ^
[error] two errors found
[error] (tests / Test / compileIncremental) Compilation failed
```

**Comment by bjaglin** [comment]
@mlachkar it looks like https://github.com/olafurpg/named-literal-arguments needs to be adapted to https://github.com/scalacenter/scalafix/pull/1379. Could you port it to the scalacenter organization so we can iterate on it?

**Comment by mlachkar** [comment]
definitely !

**Comment by mlachkar** [comment]
The transfer is done! I will fix the tests and release a new version!
