### ISSUE TITLE
Document how to publish rules to s01.oss.sonatype.org 

### ISSUE THREAD

**Issue by ghostbuster91** [scalacenter/scalafix#1535]
I made my own scalafix rule following the official tutorial on https://scalacenter.github.io/scalafix/docs/developers/setup.html

I then setup the `scala-ci-release` plugin to publish my rule based on instructions there. As I have the sonatype account relatively short I use the new s01 shard. In order to use it I set:
```
sonatypeCredentialHost := "s01.oss.sonatype.org"
sonatypeRepository := "https://s01.oss.sonatype.org/service/local"
```

Whenever I do `sbt clean` I get:
```
[warn] Multiple resolvers having different access mechanism configured with same name 'sonatype-snapshots'. To avoid conflict, Remove duplicate project resolvers (`resolvers`) or rename publishing resolver (`publishTo`).
``` 
(multiplied by amount of defined sbt modules)

It seems to be caused by `.enablePlugins(ScalafixTestkitPlugin)` line, since when I remove it the message disappear (but obviously I don't want to remove it :) )

When I try to publish my artifacts with the `ScalafixTestkitPlugin` enabled I get following error:
```
[error] Unable to find credentials for [Sonatype Nexus Repository Manager @ oss.sonatype.org].
[error] stack trace is suppressed; run last rules2_11 / publish for the full output
[error] (rules2_11 / publish) java.io.IOException: Server returned HTTP response code: 401 for URL: https://oss.sonatype.org/content/repositories/snapshots/io/github/ghostbuster91/scalafix-unified/unified_2.11/0.0.3%2B0-08c2cfa3%2B20220206-1324-SNAPSHOT/unified_2.11-0.0.3%2B0-08c2cfa3%2B20220206-1324-SNAPSHOT.pom
```
Which is not a surprise because I don't have credentials for `oss.sonatype.org` but rather for `s01.oss.sonatype.org`.

The question is why the `sbt-ci-release` tries to publish to the old shard instead of new one despite being explicitly told to use the s01 shard.

Setting following properties on every sbt-module fixed the problem for me:
```
  sonatypeSnapshotResolver := {
    MavenRepository(
      "s01-sonatype-snapshots",
      s"https://${sonatypeCredentialHost.value}/content/repositories/snapshots"
    )
  },
  sonatypeStagingResolver := {
    MavenRepository(
      "s01-sonatype-staging",
      s"https://${sonatypeCredentialHost.value}/service/local/staging/deploy/maven2"
    )
  }
```

Here is the link to my build file: https://github.com/ghostbuster91/scalafix-unified/blob/main/build.sbt

I am not sure if this is the correct solution, but it would be great if we could document it somewhere so others won't have to figure it out.

**Comment by armanbilge** [comment]
I just ran into this too. Actually I believe the real problem is in sbt-sonatype, see:
- https://github.com/xerial/sbt-sonatype/pull/279

My PR there basically does the same thing that your workaround does 👍

**Comment by ghostbuster91** [comment]
I see, I assumed incorrectly that it is connected with scalafix somehow, since I used `sbt-sonatype` before and didn't have such problems with it (even when publishing to `s01`). But probably it was an older version of `sbt-sonatype`.

**Comment by bjaglin** [comment]
Thanks for the detailed report @ghostbuster91 and the pointer @armanbilge! Looking back, https://github.com/scalacenter/sbt-scalafix/pull/211/files#r631442979 feels too intrusive anyway, so I am reopening the issue. I'll see if https://github.com/sbt/sbt/pull/5094 can be leveraged instead.

**Comment by bjaglin** [comment]
> I'll see if https://github.com/sbt/sbt/pull/5094 can be leveraged instead.

https://github.com/scalacenter/sbt-scalafix/pull/281

**Comment by armanbilge** [comment]
> I see, I assumed incorrectly that it is connected with scalafix somehow, since I used sbt-sonatype before and didn't have such problems with it (even when publishing to s01). But probably it was an older version of sbt-sonatype.

@ghostbuster91 even though it is a problem with sbt-sonatype, you can only observe the problem in the situations when a conflict occurs.

To reproduce it independently of scalafix all you need to do is add in your build:
```scala
resolvers += Resolver.sonatypeRepo("snapshots")
```
That is sufficient to trigger a conflict and is how I discovered it.
