### ISSUE TITLE
Error information shows "update your build to use at least one Scala compiler option like -Ywarn-unused", but it is already enabled in maven

### ISSUE THREAD

**Issue by tribbloid** [scalacenter/scalafix#1536]
I'm using the command line launch:

```
$ scalafix --verbose
warning: Name RemoveUnusedImports is deprecated. Use RemoveUnused instead (since 0.6.0)
warning: Name RemoveUnusedTerms is deprecated. Use RemoveUnused instead (since 0.6.0)
error: 2 errors
[E0] The Scala compiler option "-Ywarn-unused" is required to use RemoveUnused.
To fix this problem, update your build to use at least one Scala compiler
option like -Ywarn-unused, -Xlint:unused (2.12.2 or above), or -Wunused (2.13 only)
[E1] The Scala compiler option "-Ywarn-unused" is required to use RemoveUnused.
To fix this problem, update your build to use at least one Scala compiler
option like -Ywarn-unused, -Xlint:unused (2.12.2 or above), or -Wunused (2.13 only)
```

But `-Ywarn-unused` is already enabled in maven. Is there an option to correctly identify it?

**Comment by tribbloid** [comment]
that may not be possible, the semanticDB plugin was known to cause problem in our project, but it has to be enabled for a key feature of scalafix we use (optimise imports)

Is there a way to inline it or optimise imports without semanticDB?

**Comment by bjaglin** [comment]
[Semantic rules](https://scalacenter.github.io/scalafix/docs/rules/overview.html) require semanticdb to run. You can reorganize/sort imports using https://github.com/NeQuissimus/sort-imports or even https://scalameta.org/scalafmt/docs/configuration.html#imports-expand, but semantic information is mandatory if you want more advanced behavior.

What issue did you face with the semanticdb plugin?

**Comment by bjaglin** [comment]
Let's follow up on https://github.com/scalameta/scalameta since scalafix works as intended here
