### ISSUE TITLE
Error downloading org.scalameta:semanticdb-scalac_2.13.8:4.4.28

### ISSUE THREAD

**Issue by mdedetrich** [scalacenter/scalafix#1560]
I am currently using Scalafix and when It try to update to the latest Scala versions from 2.13.6 to 2.13.8 in build.sbt and then try and load the project in `build.sbt` it fails with the following error

```
[error] (... / ssExtractDependencies) sbt.librarymanagement.ResolveException: Error downloading org.scalameta:semanticdb-scalac_2.13.8:4.4.28
[error]   Not found
[error]   Not found
[error]   not found: /home/mdedetrich/.ivy2/local/org.scalameta/semanticdb-scalac_2.13.8/4.4.28/ivys/ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/scalameta/semanticdb-scalac_2.13.8/4.4.28/semanticdb-scalac_2.13.8-4.4.28.pom
[error]   not found: https://oss.sonatype.org/content/repositories/snapshots/org/scalameta/semanticdb-scalac_2.13.8/4.4.28/semanticdb-scalac_2.13.8-4.4.28.pom
```

You can see the currently open PR at https://github.com/aiven/guardian-for-apache-kafka/pull/113 for more details.

This may be related to https://github.com/scalameta/metals/issues/2395 but not sure if its the exact same problem. For integration details of scalafix see https://github.com/aiven/guardian-for-apache-kafka/blob/main/build.sbt#L273-L276 and https://github.com/aiven/guardian-for-apache-kafka/blob/main/project/plugins.sbt#L7

**Comment by bjaglin** [comment]
It looks like you are missing `ThisBuild / semanticdbVersion := scalafixSemanticdb.revision` (see https://scalacenter.github.io/scalafix/docs/users/installation.html#sbt). Without this, the semanticdbVersion is driven by [sbt](https://github.com/sbt/sbt/blob/ba5f7527fef1fd947f372b9ed940052fe1ee1edc/main/src/main/scala/sbt/plugins/SemanticdbPlugin.scala#L29).

**Comment by mdedetrich** [comment]
This indeed did fix it, thanks
