### ISSUE TITLE
Potential new logo to use for Scalafix

### ISSUE THREAD

**Issue by bishabosha** [scalacenter/scalafix#1574]
I made this logo, inspired by the Scaladex logo, what do people think of including it? - it would be freely donated to the project
![scalafix-logo](https://user-images.githubusercontent.com/13436592/159955767-4875dde6-0a43-4700-b15b-1a91133981da.png)

**Comment by bjaglin** [comment]
LGTM :heart_eyes:

**Comment by bishabosha** [comment]
Im working on a PR to add it
