### ISSUE TITLE
Scala 3: semantic info for Infix arguments cannot be looked up

### ISSUE THREAD

**Issue by bjaglin** [scalacenter/scalafix#1594]
https://github.com/scalacenter/scalafix/blob/7cfbad5582705b11df455d8606a1007b23604ef1/scalafix-tests/shared/src/main/scala/test/SymbolTest.scala#L10-L14
```
L13: Term.ApplyInfix(_, Term.Name("shouldBe"), _, arg :: Nil)
```
Symbol lookup for `arg` fails against Scala 3.1.1 SemanticDB as the position there excludes surrounding parentheses while 2.x (scalac-semanticdb) and the parser include them

https://github.com/scalacenter/scalafix/pull/1528/files#r846793225

**Comment by tgodzik** [comment]
Good catch! Did you report it in the Scala 3 compiler?

**Comment by bjaglin** [comment]
@tgodzik to be honest, I wasn't sure what was at fault here. Is there any spec or tests in the reference implementation I could link to if I create a ticket on dotty?

**Comment by tanishiking** [comment]
I checked how the Scala3 compiler generates the SemanticDB for infix argument https://github.com/tanishiking/dotty/commit/5781617a9bd375a5c8988953deb6ed35c57f3791 (though the latest Scala3 generates it in `main` branch, there's no change around the position of symbol occurrence these days AFAIK).
But it seems like the symbol position for `arg` takes the surrounding parentheses into account.

**Comment by tanishiking** [comment]
Oh, I see, so in Scala2, 

```scala
trait SymbolTest/*<=_empty_.SymbolTest#*/ { 
  ...
  this shouldBe/*=>_empty_.SymbolTest#shouldBe().*/ (arg)/*=>_empty_.SymbolTest#arg().*/ 
} 
```

and Scala3 generates:

```scala
trait SymbolTest/*<=_empty_.SymbolTest#*/ { 
  ...
  this shouldBe/*=>_empty_.SymbolTest#shouldBe().*/ (arg/*=>_empty_.SymbolTest#arg().*/)
} 
```

**Comment by tanishiking** [comment]
I personally see the Scala3 generated symbol occurrence for `arg` seems more accurate, and it would be better to handle on the scalafix side? 🤔

**Comment by tgodzik** [comment]
Hmm... having just `arg` seems more resonable, or are we missing something? The alternative would be to change it in the parser and in semanticdb Scala 2 plugin

**Comment by rochala** [comment]
The parenthesis inclusion is done only by scalameta parser. Both scala2 and scala3 trees at compilation exclude them and properly show position for arg ( excluding the parenthesis ). Scala3 semantic db position is thou different because its based on trees from compiler.
I'm no expert but in my opinion fixing it in scala3 would be a hack.

**Comment by tanishiking** [comment]
I think scalameta parser should exclude The parentheses (if there're no special reasons), that should fix both scala2 and scala3?

**Comment by tgodzik** [comment]
> I think scalameta parser should exclude The parentheses (if there're no special reasons), that should fix both scala2 and scala3?

Looks like it! We should use the Positions suite for that, are you able to take a look in scalameta @tanishiking ?

**Comment by tanishiking** [comment]
I found some comments here https://github.com/scalameta/scalameta/blob/1a9ec6f9aa06e20bc786b5c7ef6d7aa500e59eaf/scalameta/parsers/shared/src/main/scala/scala/meta/internal/parsers/ScalametaParser.scala#L1440-L1444

**Comment by bjaglin** [comment]
Thanks @tanishiking & @tgodzik !
