### ISSUE TITLE
Publish for Scala 2.12.16, please

### ISSUE THREAD

**Issue by SethTisue** [scalacenter/scalafix#1614]
as per https://contributors.scala-lang.org/t/scala-2-12-16-release-planning/5692/8

**Comment by mlachkar** [comment]
I m starting the release!

**Comment by mlachkar** [comment]
I can do that tonight!

**Comment by bjaglin** [comment]
Blocked by https://github.com/scalameta/scalameta/issues/2770

**Comment by tgodzik** [comment]
Scala 2.12.16 is released with the newest Scalameta 4.5.9

**Comment by bjaglin** [comment]
@SethTisue scalafix-core is published, sbt-scalafix is on its way (~1h)
