### ISSUE TITLE
Add a github action for scala steward

### ISSUE THREAD

**Issue by mlachkar** [scalacenter/scalafix#1616]
- https://github.com/scalacenter/scalafix
- https://github.com/scalacenter/sbt-scalafix
- https://github.com/scalacenter/scalafix.g8
- https://github.com/scalacenter/example-scalafix-rule
- https://github.com/scalacenter/scalafix-named-literal-arguments
- https://github.com/scalacenter/sbt-scalafix-example

**Comment by bjaglin** [comment]
Could you clarify what's the intent or the problem you want to solve?

**Comment by tgodzik** [comment]
@bjaglin the public instance of scala steward is no longer running, we added additional action https://github.com/scalameta/metals/blob/main/.github/workflows/scala-steward.yml

I wonder if we could just add scalafix there? Maybe if the scalameta bot is added as a contributor here.

**Comment by bjaglin** [comment]
> I wonder if we could just add scalafix there? Maybe if the scalameta bot is added as a contributor here.

I haven't read anything else than https://github.com/armanbilge/diy-steward, but since it seems trivial to set it up, I wonder if it's not better to have it defined here?

**Comment by bjaglin** [comment]
VirtusLab started a public instance with the same conf as the original one: https://github.com/VirtusLab/scala-steward-repos/blob/main/repos-github.md
