### ISSUE TITLE
Non-descriptive errors

### ISSUE THREAD

**Issue by OlegYch** [scalacenter/scalafix#1622]
When running scalafix via sbt i get ` (Compile / scalafix) scalafix.sbt.InvalidArgument: scalafix.v1.Rule: Error reading configuration file` with no explanation what is wrong or even a stacktrace.
sbt-scalafix 0.10.1

**Comment by bjaglin** [comment]
Thanks for reporting!

I guess this comes from https://github.com/openjdk/jdk/blob/9a9add8825a040565051a09010b29b099c2e7d49/jdk/src/share/classes/java/util/ServiceLoader.java#L309 (Java 8, exact wording changed starting Java 9).

I'll check how to adapt https://github.com/scalacenter/sbt-scalafix/blob/d1abcb1defcde78b9bb03d3dae7870dddfb98229/src/main/scala/scalafix/internal/sbt/ScalafixInterface.scala#L104 to give more information.

**Comment by bjaglin** [comment]
The latest sbt-scalafix snapshot should give you a stack trace
```diff
 // project/plugins.sbt
-addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.10.01")
+addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.10.1+4-22433065-SNAPSHOT")
+resolvers += Resolver.sonatypeRepo("snapshots")
```

Can you try it out on your build so we can see what we could do in scalafix itself?

**Comment by OlegYch** [comment]
i think the jar with rules was broken somehow, can't reproduce right now
the fix looks good to me, thanks!
