### ISSUE TITLE
sbt-scalafix: default scalafixScalaBinaryVersion to scalaBinaryVersion

### ISSUE THREAD

**Issue by bjaglin** [scalacenter/scalafix#1658]
For ExplicitResultTypes to work out of the box, it would better to set by default
```
scalafixScalaBinaryVersion := scalaBinaryVersion.value
```

Current blockers:
- confirm all major rules are cross-published in _2.12 and _2.13 (no need for _3 assuming we have [an automatic fallback to _213 in reflect_3](https://github.com/scalacenter/scalafix/issues/1680))
- more actionnable message when community rules cannot be found
- https://github.com/scalacenter/scalafix/issues/1583

**Comment by ssanj** [comment]
In the short term would a note about adding the `scalafixScalaBinaryVersion` to `build.sbt` in `ExplicitResultTypes` [documentation](https://scalacenter.github.io/scalafix/docs/rules/ExplicitResultTypes.html) be of any use?

Eg.
> The ExplicitResultTypes rule needs to run with the same Scala binary version as the one used to compile target sources. Please add the following `scalafixScalaBinaryVersion` to your build.sbt file:
```
scalafixScalaBinaryVersion := scalaBinaryVersion.value //supported versions are 2.11, 2.12, 2.13
```

I stumbled across this issue recently and would have found some documentation about configuring `scalafixScalaBinaryVersion` at the location of the rule configuration helpful.

**Comment by bjaglin** [comment]
> In the short term would a note about adding the scalafixScalaBinaryVersion to build.sbt in ExplicitResultTypes [documentation](https://scalacenter.github.io/scalafix/docs/rules/ExplicitResultTypes.html) be of any use?

Feel free to open a PR to update the message in https://github.com/scalacenter/scalafix/blob/5d6b2e296c70e1666b91dd9368f7fad81106133e/docs/rules/ExplicitResultTypes.md. Remember this page is about scalafix, so your message should mention that this hint is for sbt only.

I am not familiar with community clients, but it looks like the scala binary version is not configurable for the mill and the maven ones (to be confirmed):
* https://github.com/joan38/mill-scalafix/blob/05eedb866b52fbb88070987c83d14a169a77b16d/mill-scalafix/src/com/goyeau/mill/scalafix/ScalafixModule.scala#L26
* https://github.com/evis/scalafix-maven-plugin/blob/dc5d953b9614b0883a46249e567b3929074f83fd/pom.xml#L37

**Comment by ssahayam-zd** [comment]
> Feel free to open a PR to update the [docs](https://github.com/scalacenter/scalafix/blob/5d6b2e296c70e1666b91dd9368f7fad81106133e/docs/rules/ExplicitResultTypes.md). Remember this page is about scalafix, so your message should mention that this hint is for sbt only.

Sure. The [installation page](https://scalacenter.github.io/scalafix/docs/users/installation.html#sbt) only has explicit config for SBT, so I was going to do something similar to that. 

I will mention that it's only for SBT.

**Comment by bjaglin** [comment]
fixed in https://github.com/scalacenter/sbt-scalafix/pull/419
