### ISSUE TITLE
Publish cli_3 & rules_3, built against core_2.13

### ISSUE THREAD

**Issue by mlachkar** [scalacenter/scalafix#1680]
Follows https://github.com/rvacaru/GsoC-2022-Scalafix

- Testing
  - [x] [reenable testing scala latest with Scala 3 build](https://github.com/scalacenter/scalafix/pull/1926/files#r1479349441) 
  - [x] many of tests in ScalafixArgumentsSuite rely on semanticRule, and we don't have any yet for scala 3. We need to create a simple semanticrule and test the ignored tests for scala 3 (search for "i1680" in code)
    - https://github.com/scalacenter/scalafix/pull/1756
  - [x] update [integration tests](https://github.com/scalacenter/scalafix/blob/dc2b126a35d24f427742880d60d2a6ae8be74f78/scalafix-tests/integration/src/test/scala/scalafix/tests/interfaces/ScalafixSuite.scala#L108)
- ~core_3~
  - [x] ~wait for https://github.com/scalameta/scalameta/pull/3347 acceptable to start without support of quasiquotes and getting 2.13 artifacts in the classpath?~ we'll proceed with cli_3/reflect_3/rules_3 builtcore_2.13 to unblock ExplicitResultTypes, and follow-up with core_3 in https://github.com/scalacenter/scalafix/issues/2041
- ~reflect_3~
  - [x] ~add warning that quasiquotes are not supported and that compiler behavior might be different, proposing a fallback to 2.13 artefacts (or throw an exception that cli understands, which would reboot with 2.13 automatically?)~ let's stick to reflect_2.13 instead, and follow-up in https://github.com/scalacenter/scalafix/issues/2041
- rules_3
  - [x] make sure all rules are available (even the one that is irrelevant for Scala 3) to maximise compatibility of cli_3
  - [x] start testing against 2_13 sources to maximise compatibility of cli_3
- cli_3
  - [x]  ~do we _really_ need full-cross-version in Scala 3? Consider https://www.scala-lang.org/blog/2022/08/17/long-term-compatibility-plans.html~ we do for ExplicitResultTypes to be efficient for LTS & Next, see https://github.com/scalacenter/scalafix/pull/2023#discussion_r1711317793
  - [x] build with Scala Next on top of Scala LTS, and add corresponding expect (with minor suffix) - recap with a https://github.com/dwijnand/sbt-project-graph augmented with non-standard dependencies and persist it in CONTRIBUTING.md
  - [x] require a full scala version in interfaces, falling back to Next if not provided or if we don't have the exact minor version available
  - [x] coursier lookups in should fallback to loading 2.13 artifacts for requested community rules artfacts not available in scala 3
- sbt-scalafix
  - [x] default to cli_3 when sources are in scala 3 
  - [x] provide the full scala version instead of just the binary one when loading interfaces
- Documentation
  - [ ] extensive release notes for build tools authors to provide a full scala version for scala 3

**Comment by bjaglin** [comment]
Done - demonstrated with https://github.com/scalacenter/scalafix/pull/2044
