### ISSUE TITLE
scala 3: RemoveUnused & OrganizeImports.removeUnused

### ISSUE THREAD

**Issue by bjaglin** [scalacenter/scalafix#1682]
Blocked by
- [x] https://github.com/lampepfl/dotty/pull/16157
- [x] https://github.com/lampepfl/dotty/pull/17835

**Comment by PaulCoral** [comment]
As the mentionned PR has been closed maybe this one may be relevant : lampepfl/dotty#16157

**Comment by tanishiking** [comment]
Finally https://github.com/lampepfl/dotty/pull/17835 has merged, and we'll be able to support these features using the nightly builds of Scala3 👍
