### ISSUE TITLE
Shorten fully qualified names from ExplicitReturnTypes.

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scalafix#169]
ExplicitReturnTypes currently inserts fully qualified names, even if the short name is available in scope
```scala
// before
implicit val tt = liftedType
// after
implicit val tt: slick.api.TypedType[R] = liftedType
// would be nice
import slick.api.TypedType
implicit val tt: TypedType[R] = liftedType
```

**Comment by diego-alvarez-hs** [comment]
Up! :rofl:

**Comment by olafurpg** [comment]
@diego-alvarez-hs the top priority at the moment is making ExplicitReturnTypes correct first, see https://github.com/scalacenter/scalafix/issues/254. I agree this is a blocking issue for enabling ExplicitReturnTypes in CI, however.

**Comment by olafurpg** [comment]
@diego-alvarez-hs https://github.com/scalacenter/scalafix/pull/317 adds an `explicitReturnTypes.unsafeShortenNames = true` setting which will naively remove the prefix of fully qualified names and insert imports at the top of the file. It does not take into account potential conflicts with other names in scope, that feature is blocked by https://github.com/scalameta/scalameta/issues/1075.

Adding support for conventions such as `mutable.Set` can easily be accommodated and might be a good  first-time contribution.

**Comment by diego-alvarez-hs** [comment]
just tried it, works really well!
I created https://github.com/scalacenter/scalafix/issues/329 with a small bug
