### ISSUE TITLE
Must this codebase use `sun.misc.Unsafe`?

### ISSUE THREAD

**Issue by SethTisue** [scalacenter/scalafix#1699]
I'm asking because it means that in the Scala 2 community build, we can only build Scalafix on JDK 8.

But because Metals has only partial support for JDK 8 that they may drop soon, and because Metals depends on Scalafix, it means  there isn't a JVM version I can build them both on

I am working around it at https://github.com/scala/community-build/pull/1602 by including only the bare minimum Scalafix modules in the community build, but it's a bit sad I can't include more, especially the tests.

Also, when the build here requires JDK 8, that might cause difficulty for your own contributors, who might prefer to be on JDK 11 or 17.

**Comment by SethTisue** [comment]
scalafix-testkit is affected, which means that I'm having to disable the scalafix testing subprojects in downstream repos that use it: simulacrum-scalafix,sconfig,http4s,circe,catbird,akka-http

**Comment by SethTisue** [comment]
If a solution can be found, it would be nice to also apply it over in the mdoc repo: https://github.com/scalameta/mdoc/blob/main/mdoc/src/main/scala/mdoc/internal/CompatClassloader.scala

**Comment by SethTisue** [comment]
the PR where this stuff was added was @dos65's https://github.com/scalacenter/scalafix/pull/1080

**Comment by bjaglin** [comment]
Thanks for reaching out. Sorry for the delay!

> I'm asking because it means that in the Scala 2 community build, we can only build Scalafix on JDK 8.

> Also, when the build here requires JDK 8, that might cause difficulty for your own contributors, who might prefer to be on JDK 11 or 17.

In both cases (community build & local setup), I assume there would be specific flags to prevent usage of `sun.misc.Unsafe`, as the CI (and [now](https://github.com/scalacenter/scalafix/pull/1780#issuecomment-1586191863) my local setup) can build all modules and run tests on JDK17. Could you point them out so I can get a repro?

In any case, I'll take some time to try to get rid of it since it's just a matter of time until that blows up.

**Comment by tgodzik** [comment]
I did manage to work around it with reflection in Metals, but later on we actually removed it altogether, since it turned out it was not needed since we could just load up stuff to our own classloader.

The reflection was added in https://github.com/scalameta/metals/pull/5220/files but never merged

**Comment by bjaglin** [comment]
> The reflection was added in https://github.com/scalameta/metals/pull/5220/files but never merged

Interesting hack! :+1:

**Comment by SethTisue** [comment]
after some digging, I see now that in your build, `-release:8` is used to avoid this

why it doesn't work in the community build, I'm not sure yet. I'll keep digging. sorry for the false alarm 😅

**Comment by tgodzik** [comment]
> after some digging, I see now that in your build, `-release:8` is used to avoid this
> 
> why it doesn't work in the community build, I'm not sure yet. I'll keep digging. sorry for the false alarm sweat_smile

I think `-release:8` doesn't work well with sun modules. For JDK 17 I think it's not possible use them, though somehow it works for sbt

**Comment by SethTisue** [comment]
yeah it turned out I need to remove `-release:8`, as per my remarks on https://github.com/scala/community-build/issues/1673 — thanks Tomasz for the nudge
