### ISSUE TITLE
Scala 3.3 Fewer Braces reports

### ISSUE THREAD

**Issue by carlosedp** [scalacenter/scalafix#1738]
Some syntax reports while using fewer braces syntax which will be available as default in Scala 3.3.

Config:

```
rules = [
  DisableSyntax,
  LeakingImplicitClassVal,
  NoAutoTupling,
  NoValInForComprehension,
  OrganizeImports
]

OrganizeImports.blankLines = Auto
OrganizeImports.groupedImports = Merge
OrganizeImports.expandRelative = true
OrganizeImports.removeUnused = false
OrganizeImports.groups = [
  "re:javax?\\."
  "scala."
  "scala.meta."
  "*"
]
```

Using thru the mill-scalafix plugin.

```
/Users/cdepaula/repos/scala-playground/zio-temporal-hello/client/src/Client.scala:20:5: error: outdent expected but . found
    .withTaskQueue(TemporalQueues.echoQueue)
    ^
```

The code is:

```scala
def workflowStubZIO(client: String) = ZIO.serviceWithZIO[ZWorkflowClient]: workflowClient =>
  workflowClient
    .newWorkflowStub[EchoWorkflow]
    .withTaskQueue(TemporalQueues.echoQueue)
    .withWorkflowId(s"$client-${UUID.randomUUID().toString}")
    .withWorkflowRunTimeout(2.seconds)
    .withRetryOptions(ZRetryOptions.default.withMaximumAttempts(3).withBackoffCoefficient(1))
    .build

```

another one:

```
/Users/cdepaula/repos/scala-playground/zio-temporal-hello/shared/src/MetricsApp.scala:28:7: error: identifier expected but case found
      case Method.GET -> !! / "metrics" =>
      ^^^^
```

for code:

```scala
  def apply(): Http[PrometheusPublisher, Nothing, Request, Response] =
    Http.collectZIO[Request]:
      case Method.GET -> !! / "metrics" =>
        ZIO.serviceWithZIO[PrometheusPublisher](
          _.get.map(Response.text),
        ) @@ MetricsApp.httpHitsMetric("GET", "/metrics")
```

and 

```
/Users/cdepaula/repos/scala-playground/zio-temporal-hello/shared/src/EchoActivity.scala:17:7: error: identifier expected but for found
      for
      ^^^
```

for code:

```scala
  override def echo(msg: String, client: String = "default"): String =
    val newMsg = s"ACK: $msg"
    ZActivity.run:
      for
        _ <- ZIO.logDebug(s"Received from $client, message: $msg") @@ MetricsApp.echoCalls(client)
        _ <- ZIO.logDebug(s"Reply with: $newMsg")
      yield newMsg

```

All compile fine under 3.3.0-RC3.

**Comment by bjaglin** [comment]
Fewer braces support was added in scalameta via https://github.com/scalameta/scalameta/pull/2848, and made available by default on the default Scala3 dialect with https://github.com/scalameta/scalameta/pull/2958.

https://github.com/scalacenter/scalafix/pull/1743 should therefore fix that.

**Comment by carlosedp** [comment]
Nice, do you plan to cut a release soon?
Thanks!

**Comment by bjaglin** [comment]
Sorry for the delay. I was/am waiting for the release of 2.12.18 & 2.13.11, which should happen around the same time as 3.3.0 ([RC4 seems to be finally coming soon](https://github.com/lampepfl/dotty/milestone/48)). Until then, you can use a [SNAPSHOT](https://scalacenter.github.io/scalafix/docs/users/installation.html#snapshot) to try it out, and close the issue if that solves the issue.

**Comment by carlosedp** [comment]
Thanks, I'll try via coursier with the snapshot but since I mostly use scalafix via the mill-scalafix plugin I'll have to wait for a release to send a PR to the mill plugin bumping the scalafix dep.

**Comment by tOverney** [comment]
@bjaglin  with scala 3.3.0 now out can we get a new release please?

**Comment by carlosedp** [comment]
With a new release I can also ask to bump the https://github.com/joan38/mill-scalafix plugin.

**Comment by bjaglin** [comment]
https://contributors.scala-lang.org/t/scala-2-13-11-release-planning/6088/10 is due tomorrow, so I am expecting to cut a new scalafix release by June 3rd.

**Comment by bjaglin** [comment]
Scalafix 0.11.0 is on its way to Maven central

**Comment by joan38** [comment]
This is back in 0.14.0:
```
[error] /.../Measures.scala:59:87: error: `outdent` expected but `=>` found
[error]         labelling.elemLabels.zipWithIndex.foldLeft(Set.empty): (measures, labelIndex) =>
[error]                                                                                       ^^
[error] (core / scalafixAll) scalafix.sbt.ScalafixFailed: ParseError
```

**Comment by bjaglin** [comment]
> This is back in 0.14.0:

This was cross-posted to https://github.com/scalacenter/scalafix/issues/2111#issuecomment-2610564012, let's follow-up there
