### ISSUE TITLE
Add main function using DelayedInit (extends App)

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scalafix#174]
See https://github.com/lampepfl/dotty/blob/836ec499de1d8f52de6786f6090aeb52dd128218/docs/docs/reference/dropped/delayedInit.md and https://github.com/lampepfl/dotty/issues/559

```scala
// before
object DelayedInitToMain extends App {
  println(args)
}
// after
object DelayedInitToMain {
  def main(args: Array[String]): Unit = {
    println(args)
  }
}
```

The rewrite should only trigger if `args` is accessed.

Note https://github.com/scalameta/scalameta/issues/905

**Comment by smarter** [comment]
> The rewrite should only trigger if args is accessed.

It might be better to always rewrite to avoid confusion (e.g. you start with code that uses App but doesn't use args, use the rewrite tool, and then you decide to use args, nothing will tell you it's wrong).

**Comment by olafurpg** [comment]
Good point @smarter I agree. That makes this rewrite simpler, if something extends scala.App, wrap body in main function.
