### ISSUE TITLE
sourceroot not used by cli tool

### ISSUE THREAD

**Issue by stuhood** [scalacenter/scalafix#176]
The CLI tool does not use the `sourceroot` value that is passed in, and the result is that the files that are operated on are always the ones relative to `CWD`.

The `Input` values that come from the scalameta database will be `Input.LabeledString` (afaict), with relative paths names as the labels. scalafix will need to convert these to absolute paths using the supplied `sourceroot`.

**Comment by olafurpg** [comment]
Good catch! In sbt, the working directory is the same as CWD so this didn't get caugt in tests.

The absolute path is inferred from the working directory here: https://github.com/scalacenter/scalafix/blob/13e96816fe86ca53f2335c3470efb85933c86bc4/scalafix-cli/src/main/scala/scalafix/cli/CliRunner.scala#L82

The CliRunner should instead use a `sourceroot` field passed as a constructor parameter here https://github.com/scalacenter/scalafix/blob/13e96816fe86ca53f2335c3470efb85933c86bc4/scalafix-cli/src/main/scala/scalafix/cli/CliRunner.scala#L40

I will try to take a look at this at the spree today.

PS. This reminds me scalafix should have a RemoveUnusedDefns rewrite to remove unused definitions like `resolvedSourceroot`.

**Comment by stuhood** [comment]
Thanks for #183!
