### ISSUE TITLE
Use rules defined in SBT module within a multi-module build

### ISSUE THREAD

**Issue by cchantep** [scalacenter/scalafix#1795]
Currently it's not possible to use rules defined in a SBT modules in other modules of the same multi-modules project *without publishing*, aka not possible to use inter-module dependencies (e.g. `dependsOn`).

> Local rules are not sufficient neither when rules are to be used accross several sibling modules, nor when the rules module itself needs specific `libraryDependencies`.

**Comment by bjaglin** [comment]
Hi @cchantep !

By "rule defined in SBT module", I assume you are refering to [that scenario](https://scalacenter.github.io/scalafix/docs/developers/local-rules.html#within-a-given-sub-project) (although the [other one](https://scalacenter.github.io/scalafix/docs/developers/local-rules.html#as-a-separate-sub-project) might be more maintainable if you start sharing rules across projets)? 

I might be misinterpreting your request, but considering that local rules rely on [a sbt configuration `ScalafixConfig` / `"scalafix"`](https://github.com/scalacenter/sbt-scalafix/blob/de065f31fbfade356306abdac2fcab639d871013/src/main/scala/scalafix/sbt/ScalafixPlugin.scala#L26-L27), you should already have full flexibility on dependency management.

> Local rules are not sufficient neither when rules are to be used accross several sibling modules

You should be able to use `service2.dependsOn(service1 % "scalafix->scalafix")` (see [docs](https://www.scala-sbt.org/1.x/docs/Multi-Project.html#Per-configuration+classpath+dependencies)).

> nor when the rules module itself needs specific `libraryDependencies`.

Did you try `service1 / libraryDependencies += "external" % "dependency" % "1.0.0" % ScalafixConfig` ? (see [docs](https://www.scala-sbt.org/1.x/docs/Multi-Project.html#Per-configuration+classpath+dependencies))

---

Let me know if that helps. If it does, [a PR to clarify the docs](https://github.com/scalacenter/scalafix/edit/main/docs/developers/local-rules.md) would be welcome. If it does not, a concrete example would help, to better understand your needs.

**Comment by bjaglin** [comment]
Hi @cchantep, any feedback on that?
