### ISSUE TITLE
OrganizeImports: removeUnused - implement for scala 3.3.+

### ISSUE THREAD

**Issue by ivan-klass** [scalacenter/scalafix#1820]
`-Wunused:imports` was added in scala 3.3.0 release

That means
```
OrganizeImports {
  removeUnused = true
}
```
should be available for 3.3+ also.

Can we move it forward? What is the place to start work?

Thanks

**Comment by ivan-klass** [comment]
Thanks to @liancheng for pointing me here from https://github.com/scalacenter/scalafix/issues/1820

**Comment by ivan-klass** [comment]
Sorry, it seems like should be resolved with https://github.com/scalacenter/scalafix/pull/1800.
Will track it there then

**Comment by bjaglin** [comment]
Thanks, and sorry for the little trip you had to take to come to that conclusion. I am generalizing https://github.com/scalacenter/scalafix/issues/1682 to also include `OrganizeImports.removeUnused` and help with discoverability.
