### ISSUE TITLE
Adjust the content of the LICENSE.md file to be recognized by GitHub

### ISSUE THREAD

**Issue by sideeffffect** [scalacenter/scalafix#1831]
The current file is not recognized by GitHub. See https://github.com/stkeky/best-of-scala/issues/54#issuecomment-1646222015 for details

Maybe one of these would work?
 * https://github.com/patx/pickledb/blob/master/LICENSE
 * https://github.com/IQAndreas/markdown-licenses/blob/master/bsd-3.md

**Comment by bjaglin** [comment]
Thanks for the report!
