### ISSUE TITLE
SymbolMatcher: normalized doesn't infer trailing dot when symbol contains backticks

### ISSUE THREAD

**Issue by roccojiang** [scalacenter/scalafix#1880]
When a symbol contains backticks, normalized symbol matchers do not work unless you explicitly add a trailing dot.

For example:
```scala
// Without trailing dot
val plus = SymbolMatcher.normalized("scala.Int.`+`")
plus.matches(Symbol("scala/Int#`+`(+4).")) // false, but should be true

// With trailing dot
val plus2 = SymbolMatcher.normalized("scala.Int.`+`.")
plus2.matches(Symbol("scala/Int#`+`(+4).")) // true
```

As far as I can tell from the documentation, `normalized()` should infer a trailing dot if it is omitted in any circumstance, but I may be mistaken!

**Comment by bjaglin** [comment]
Thanks for the report @roccojiang ! Could you confirm that the problem is fixed in [the SNAPSHOT being pushed in the coming minutes](https://scalacenter.github.io/scalafix/docs/users/installation.html#snapshot)? Thanks!

**Comment by roccojiang** [comment]
Can confirm that the issue is fixed now, thanks @bjaglin!
