### ISSUE TITLE
Cannot ignore DisableSyntax.regex which starts with .*

### ISSUE THREAD

**Issue by tubo28** [scalacenter/scalafix#1889]
This maybe bug report, but we cannot ignore `DisableSyntax.regex` rules with the pattern starts with `.*` by `scalafix:ok`.

It reproduces with `Main.scala` like this:

```scala
package example

object Hello extends Greeting with App {
  println(greeting)
}

trait Greeting {
  lazy val greeting: String = "hello"
  val foo = 0 // scalafix:ok
  val bar = 0 // scalafix:ok
}
```

and `.scalafmt.conf` like this:

```hocon
rules = [
  DisableSyntax
]

DisableSyntax.regex = [
  {
    id = FooChecker
    pattern = ".*foo" // somothing goes wrong; we cannot ignore this
    message = foo is bad
  }
  {
    id = BarChecker
    pattern = "bar" // ok
    message = bar is bad
  }
]
```

Then result:

```sbt
sbt:scalafixtmp> scalafix
[info] Running scalafix on 1 Scala sources
[error] /Users/user/ghq/github.com/tubo28/scalafixtmp/src/main/scala/example/Hello.scala:9:1: error: [DisableSyntax.FooChecker] foo is bad
[error]   val foo = 0 // scalafix:ok
[error] ^^^^^^^^^
[warn] /Users/user/ghq/github.com/tubo28/scalafixtmp/src/main/scala/example/Hello.scala:9:15: warning: [UnusedScalafixSuppression] Unused Scalafix suppression, this can be removed
[warn]   val foo = 0 // scalafix:ok
[warn]               ^^^^^^^^^^^^^^
[error] (Compile / scalafix) scalafix.sbt.ScalafixFailed: LinterError
[error] Total time: 0 s, completed 2023/11/09 3:01:04
```

Minimum project to reproduce this is here https://github.com/tubo28/scalafixtmp

Scala 2.13.12
Sbt: 1.9.7
Scalafix: `"sbt-scalafix" % "0.11.1"`

**Comment by bjaglin** [comment]
Thanks for the clear report!

What happens here is that the wildcard capture whitespace characters before the literal, so the suppression mechanism is not working. You can see that by looking at the carets highlighting all heading chars until `foo` in the error message.

I'll see if we could make it a bit more robust, but for the time being, if you want to catch literals ending with `foo` AND be able to suppress them, `pattern = "[^\\s]*foo"` should do the trick.

**Comment by skitanoooo** [comment]
Thank you for a work around, and I would be happy if it could be improved!

**Comment by tubo28** [comment]
Thank you for a work around, and I would be happy if it could be improved!

**Comment by bjaglin** [comment]
This should be fixed in the [latest SNAPSHOT](https://scalacenter.github.io/scalafix/docs/users/installation.html#snapshot). Let me now if that's not the case!

**Comment by tubo28** [comment]
Thank you so much!
