### ISSUE TITLE
Running Scalafix rules for a specific package

### ISSUE THREAD

**Issue by a-khakimov** [scalacenter/scalafix#1900]
Is it possible to configure Scalafix in such a way that all or some of the rules run only for a specific package (or sbt module)?

**Comment by bjaglin** [comment]
Hi @a-khakimov !

Unfortunately, strictly speaking, there is no way to target a specific package when invoking scalafix. However, there are many ways to work around this limitation:
1. the `--files` CLI flag accepts directories and the `--exclude` one allows to exclude paths based on the `nio.FileSystem.getPathMatcher` syntax (see [CLI docs](https://scalacenter.github.io/scalafix/docs/users/installation.html#help))
1. scalafix can be run a given sbt module  `foo`
   * `foo / scalafixAll`
   * `foo / scalafix` and/or `foo / Test / scalafix`
1. you can use sbt to customize the files `scalafix` and `scalafixAll` should target in module `foo`
   * customize the setting keys `foo / scalafix / unmanagedSources`  and/or `foo / Test / scalafix / unmanagedSources` using a [glob](https://www.scala-sbt.org/1.x/docs/Globs.html)

**Comment by bjaglin** [comment]
@a-khakimov can we close this?

**Comment by a-khakimov** [comment]
Yes. Thanks!
