### ISSUE TITLE
Move internal API to an 'internal' package

### ISSUE THREAD

**Issue by gabro** [scalacenter/scalafix#192]
This is an idea discussed offline with @olafurpg.

Currently private (low-level) and public (high-level) APIs are mixed, with private ones being marked as `private[scalafix]`.
While this works from a technical point of view, there's no obvious separation between the two.

(By "public"/"private" here I mean from rewrites authors' perspective)

A cleaner approach could be moving all the low-level internal stuff to an `internal` package (similarly to what Scalameta does) which would clarify the intention.

Thoughts anyone?

**Comment by xeno-by** [comment]
Can recommend to a friend. I think this has been working extremely well for us in meta.

**Comment by olafurpg** [comment]
I agree this is a good idea. We can make this refactoring as part of v0.5
