### ISSUE TITLE
sbt-scalafix: use `sbt.librarymanagement` API for `scalafixResolvers` instead of `cousierapi`

### ISSUE THREAD

**Issue by GreyPlane** [scalacenter/scalafix#1944]
When configuring custom repo for scalafix it's really awkward that I have to use to set of apis for sbt and scalafix-sbt.

It's much convenient to use the same API if possible.

**Comment by bjaglin** [comment]
Thanks for opening that @GreyPlane, this would definitely improve UX. I will gladly merge PRs automatically honoring sbt resolvers when `scalafixResolvers` is unset, and deprecating that setting key.

Implementation-wise, we should probably vendor [the sbt2coursier logic](https://github.com/coursier/sbt-coursier/blob/0255009d2b74ad5a5be222fe36da26713749884f/modules/lm-coursier/src/main/scala/lmcoursier/internal/Resolvers.scala#L164), after adapting it to the [limited API exposed by coursier-interface](https://github.com/coursier/interface/blob/8483f0bd8854e3006c3d57dc86c90c554d10d25f/interface/src/main/java/coursierapi/Repository.java). Maybe a warning could be issued for sbt resolvers that can't be converted into coursier-interface ones. FWIW, see also [this historical note](https://github.com/scalacenter/sbt-scalafix/pull/123#issuecomment-642236453) (that might not be relevant).

**Comment by GreyPlane** [comment]
Thanks, I will investigate and try to make a PR on my spare time.

**Comment by bjaglin** [comment]
Thanks to @GreyPlane, this is now available in the latest [SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/ch/epfl/scala/sbt-scalafix_2.12_1.0/0.12.0+12-18c20a67-SNAPSHOT/).
```scala
resolvers += Resolver.sonatypeRepo("snapshots")
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.12.0+12-18c20a67-SNAPSHOT")
```
