### ISSUE TITLE
RemoveUnused in scala 3.4 rewrites wildcard imports from .* to ._

### ISSUE THREAD

**Issue by Marcus-Rosti** [scalacenter/scalafix#1954]
Great that RemoveUnused works in scala 3.4! bad that it rewrites all my import syntax, any ideas there?

**Comment by bjaglin** [comment]
Hi @Marcus-Rosti! I assume you are talking about `OrganizeImports.removeUnused`? If so, did you look at https://scalacenter.github.io/scalafix/docs/rules/OrganizeImports.html#targetdialect?

**Comment by Marcus-Rosti** [comment]
yes! that worked! just a few levers of configuration to move around now, I get it.

**Comment by joan38** [comment]
I got hit by the same issue.
For those who also got this, add the following in your `.scalafix.conf`:
```
OrganizeImports.targetDialect = Auto
```
@bjaglin Why is `Auto` not the default? Anyone creating a brand new Scala 3 project get their `*` replaced by `_`.
This is not in line with the fact that `_` in imports is deprecated syntax in Scala 3.

**Comment by bjaglin-swile** [comment]
> @bjaglin Why is Auto not the default? Anyone creating a brand new Scala 3 project get their * replaced by _.
This is not in line with the fact that _ in imports is deprecated syntax in Scala 3.

Scalafix itself cannot tell if the project is cross-built, so for now I chose to keep a safe default. The client (sbt-scalafix, mill-scalafix, etc) does know, so it could inject that value.

In any case, the Scala 3 syntax is supported on latest Scala 2 version so we can probably make `Auto` the default in a couple of months, when the Scala 2 syntax is no longer supported in Scala 3.

**Comment by bjaglin** [comment]
> @bjaglin Why is Auto not the default? Anyone creating a brand new Scala 3 project get their * replaced by _.
This is not in line with the fact that _ in imports is deprecated syntax in Scala 3.

Scalafix itself cannot tell if the project is cross-built, so for now I chose to keep a safe default. The client (sbt-scalafix, mill-scalafix, etc) does know, so it could inject that value.

In any case, the Scala 3 syntax is supported on latest Scala 2 versions so we can probably make `Auto` the default in a couple of months, which is probably roughly when the Scala 2 syntax will no longer be supported in Scala 3.

**Comment by joan38** [comment]
I see, so `Auto` would not work for cross built projects.
Make sense, thanks @bjaglin !
