### ISSUE TITLE
Publish `scalafix-testkit` for Scala 2.12.20

### ISSUE THREAD

**Issue by danicheg** [scalacenter/scalafix#2065]
... which is now on Maven Cetral https://contributors.scala-lang.org/t/scala-2-12-20-release-planning/6580/6. Thanks!

For details: https://github.com/http4s/http4s/actions/runs/10786921417/job/29914639955?pr=7515#step:7:239

**Comment by danicheg** [comment]
Ah, I missed this comment https://github.com/scalacenter/scalafix/issues/2064#issuecomment-2327427237. So, okay, you can close this or leave it open until `0.12.2` is published.

**Comment by bjaglin** [comment]
Support was merged to `main` via https://github.com/scalacenter/scalafix/pull/2052. Actual release will happen within a week.

**Comment by bjaglin-swile** [comment]
scalafix 0.13.0 is on its way to Maven central

**Comment by bjaglin** [comment]
scalafix 0.13.0 is on its way to Maven central
