### ISSUE TITLE
`ch.epfl.scala:scalafix-rules_2.13:0.13.0` is missing from Maven Central

### ISSUE THREAD

**Issue by adpi2** [scalacenter/scalafix#2090]
My CI in https://github.com/scalacenter/scala3-migrate/pull/502 fails because `ch.epfl.scala:scalafix-rules_2.13:0.13.0` is missing.

https://repo1.maven.org/maven2/ch/epfl/scala/scalafix-rules_2.13/

**Comment by bjaglin** [comment]
scalafix-rules is cross-built with full version as of https://github.com/scalacenter/scalafix/pull/2034/commits/14982001eeb52c8c46a3cbfabbddc4165abd1a1d. I did not mention it in the release notes as I didn't expect any client to rely on it directly.

**Comment by bjaglin** [comment]
https://repo1.maven.org/maven2/ch/epfl/scala/scalafix-rules_2.13.15/0.13.0/
