### ISSUE TITLE
Insert missing root imports

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scalafix#21]
See https://github.com/lampepfl/dotty/pull/1693#discussion_r89087340 referring to commit https://github.com/lampepfl/dotty/pull/1693/commits/81bf07743d2f2072ce288fa033626261e6833f97

> any explicit import of a root import will disable the root import.

**Comment by cvogt** [comment]
+1million

**Comment by DanielaSfregola** [comment]
Ticket to be closed?

**Comment by gabro** [comment]
Why? I don't think this is done yet

**Comment by olafurpg** [comment]
This is a good idea. After the PR https://github.com/scalacenter/scalafix/pull/827, we are moving most built-in rules outside of the scalacenter/scalafix repository so that they can evolve at a faster pace. As long as a custom rule meet a certain level of quality, it can still 

- be automatically be included by `sbt-scalafix`
- have tab completion in the sbt shell like built-in rules
- be documented on the main Scalafix website

Ping us on Gitter if you believe your rule is good enough for inclusion. Don't hesitate to ask for help around code review or general guidance on writing/sharing custom rules.
