### ISSUE TITLE
Scalafix is not able to parse Scala 3 nightly version

### ISSUE THREAD

**Issue by WojciechMazur** [scalacenter/scalafix#2112]
scalafix fails to parse nightly version of Scala3 which differs from nightly version of Scala 3
Example of version `3.6.0-RC1-bin-20241008-3408ed7-NIGHTLY` 

Issue found by Scala 3 Open Community Build in 3 projects using automatic application of scalafix on compile: 
* gemini-hlsw/lucuma-schemas -	[Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/11531682951/job/32102782702)	
* tkrs/orcus - [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/11531682451/job/32102750477)	
* xuwei-k/unused-proto	- [Open CB logs](https://github.com/VirtusLab/community-build3/actions/runs/11531682951/job/32102794393)

**Comment by bjaglin** [comment]
Thanks for the report. We need a quickfix like https://github.com/scalacenter/scalafix/pull/2109. I'll have some time this week end hopefully.

**Comment by geminicaprograms** [comment]
Hello, any news on that front? `Scala 3.6.2` is out and `0.13.0` can't parse it either e.g. if fails on new multiple bounds syntax (the have to be enclosed with `{}`) with:
```
[error] .../Foo.scala:151:34: error: illegal start of declaration
[error]   private def bar[F[_]: { MonadThrow, Concurrent }](
[error]                                  ^^^^^^^^^^

```

**Comment by WojciechMazur** [comment]
> Hello, any news on that front? `Scala 3.6.2` is out and `0.13.0` can't parse it either e.g. it fails on new multiple bounds syntax (the have to be enclosed with `{}`) with:
> 
> ```
> [error] .../Foo.scala:151:34: error: illegal start of declaration
> [error]   private def bar[F[_]: { MonadThrow, Concurrent }](
> [error]                                  ^^^^^^^^^^
> ```

It's not related to this issue, you might be intrested in https://github.com/scalameta/scalameta/pull/4068 that introduced new givens syntax to scalameta parser used by scalafix. 

This issue was about not being able to version strings used by Scala 3 nightlies, not the Scala 3 syntax

**Comment by lenguyenthanh** [comment]
I created a new issue: https://github.com/scalacenter/scalafix/issues/2138
