### ISSUE TITLE
Scalafix doesn't respect excluded files

### ISSUE THREAD

**Issue by kmontemayor2-sc** [scalacenter/scalafix#2119]
[Sorry, creating new issue as I see the original one was closed] 

If I have the following directory structure:

```
.
└── common/
    ├── protos/
    │   ├── foo/
    │   │   └── Foo.scala
    │   └── bar/
    │       └── Bar.scala
    └── utils/
        └── Time.scala
```

Setting up my `.scalafix.conf` as follows does not filter out the generated proto files, when running `sbt scalalfixAll`

```
project.excludePaths = [
    "glob:**/protos/**.scala",
]

```

Also interestingly there seems to be some cached results that `sbt clean` mess with.

```bash
git restore .
sbt clean scalafixAll # formats the proto files
git restore .
sbt scalafixAll # Does not format
```

I also updated my `scalacOptions` with `"-P:semanticdb:exclude:.*proto/.*.scala"` which is also not seemingly taking effect.

_Originally posted by @kmontemayor2-sc in https://github.com/scalacenter/scalafix/issues/621#issuecomment-2463350137_

**Comment by bjaglin** [comment]
Hey!

> ```
> project.excludePaths = [
>     "glob:**/protos/**.scala",
> ]
> ```

I am afraid this is a scalafmt configuration syntax, unsupported on Scalafix.

> I also updated my scalacOptions with "-P:semanticdb:exclude:.*proto/.*.scala" which is also not seemingly taking effect.

Could you confirm this does not work with `protos` (plural) ?

**Comment by bjaglin** [comment]
> Also interestingly there seems to be some cached results that sbt clean mess with.
> 
> ```
> git restore .
> sbt clean scalafixAll # formats the proto files
> git restore .
> sbt scalafixAll # Does not format
> ```

Any chance you could push a repro of that project? By default, sbt-scalafix use hashing to stamp files, so I am puzzled by this behavior.

**Comment by kmontemayor2-sc** [comment]
> I am afraid this is a scalafmt configuration syntax, unsupported on Scalafix.

Oh, strange that there isn't an error when there's unknown syntax. So `-P:semabticdb:exclude:<pattern>` is the only way to exclude entire directories from scalafix?

> Could you confirm this does not work with protos (plural) ?

Uh, turns out the issue was I don't know how to use sbt and setup my `scalacOptions` incorrectly. With the below the settings the ignore is WAI

```
lazy val scalacOpts = Seq(
  // Enable unused imports warnings so scalafix OrganizeImports can remove
  // unused imports.
  scalacOptions ++= Seq(
    // scalafix only supports scala 2.12 and up, it's not that previous scala versions
    // *also* use -WUnused:imports
    if (scalaVersion.value.startsWith("2.12")) {
      "-Ywarn-unused-import"
    } else {
      "-Wunused:imports"
    },
    // Skip formatting generated proto files.
    // We use dots instead of / here since forward slash may not work on Windows.
    "-P:semanticdb:exclude:snapchat.research.gbml.*scala",
  )
)
... 
project.settings(scalacOpts)
```
> Any chance you could push a repro of that project? By default, [sbt-scalafix use hashing to stamp files](https://github.com/scalacenter/sbt-scalafix/blob/0d5967fadc99ad1293db20a76891b6f66df6788c/src/main/scala/scalafix/sbt/ScalafixPlugin.scala#L203-L208), so I am puzzled by this behavior.

Not currently, sadly. [This line](https://github.com/scalacenter/sbt-scalafix/blob/0d5967fadc99ad1293db20a76891b6f66df6788c/build.sbt#L80) wouldn't happen to make the default timestamps, would it?

**Comment by bjaglin** [comment]
> Oh, strange that there isn't an error when there's unknown syntax. So -P:semabticdb:exclude:<pattern> is the only way to exclude entire directories from scalafix?

That's the behavior of metaconfig - there is no validation unfortunately.

> Not currently, sadly. [This line](https://github.com/scalacenter/sbt-scalafix/blob/0d5967fadc99ad1293db20a76891b6f66df6788c/build.sbt#L80) wouldn't happen to make the default timestamps, would it?

Nope, this is only for tests.

Should we close this issue then?

**Comment by kmontemayor2-sc** [comment]
SG to close :) Thanks for your help!
