### ISSUE TITLE
parse error

### ISSUE THREAD

**Issue by gfrison** [scalacenter/scalafix#2139]
scala version: 3.6.2
scalafix version: 0.13.0
```scala
error: `]` expected but `:` found
[error]   type Jf[F[*] <: FunExpr[*]]    = [T:Show] => (F[T], Null) => Juro[T]
[error]                                      ^
```
I get an error on `[T:Show]` which compiles correctly

**Comment by tgodzik** [comment]
Ach, I finally got time to look at it properly and maybe you are missing something like:
```
OrganizeImports.targetDialect = StandardLayout
```
?

**Comment by gfrison** [comment]
same problem like above
```
[error] (scalafixAll) scalafix.sbt.ScalafixFailed: ParseError
```

**Comment by tgodzik** [comment]
What's the relative path of the file it fails on? Sorry for the late response, I just totally forgot I haven't commented here

**Comment by gfrison** [comment]
`reticolo/shared/src/main/scala/kubrick/reticolo/JuroFactory.scala` do you need more info?

**Comment by tgodzik** [comment]
It it's plain Scala 3 project you might need to do `OrganizeImports.targetDialect = Scala3` instead.

**Comment by gfrison** [comment]
this is the config:
```
rules = [OrganizeImports,RemoveUnused,RedundantSyntax,NoAutoTupling]
OrganizeImports.targetDialect = Scala3
```

**Comment by tgodzik** [comment]
The other option I guess is that the way you are running scalafix is not setting the binary version properly.

How are you running it?

**Comment by gfrison** [comment]
scalamft:
```
version = "3.8.3"
align.preset = more    
runner.dialect = scala3
maxColumn = 120
```

**Comment by gfrison** [comment]
I notice the problem exists also on launching `scalafmtAll`, but with version `3.8.4-RC3` (scalafmt) the error disappear.

**Comment by tgodzik** [comment]
And that would be blocked on https://github.com/scalacenter/scalafix/pull/2128

@bjaglin do you need help here? I can merge things and release new version.

**Comment by bjaglin** [comment]
@tgodzik I was hoping we could wait for the new 2.13 release, but I will tag a patch tomorrow with the latest scalameta

**Comment by bjaglin** [comment]
@gfrison can you confirm that the [latest snapshot](https://scalacenter.github.io/scalafix/docs/users/installation.html#snapshot) fixes your problem? Thanks!
