### ISSUE TITLE
RemoveUnusedImports: trailing whitespace

### ISSUE THREAD

**Issue by cvogt** [scalacenter/scalafix#216]
```
-import scalaz.concurrent.{ Future, Task }
+import scalaz.concurrent.Task
```
Task is followed by a space.

**Comment by olafurpg** [comment]
Thanks for reporting! This should be fixable, but note that RemoveUnusedImports does a best-effort only to preserve formatting. It's recommended to run formatter after the rewrite.

**Comment by gabro** [comment]
I've also noticed this

```diff
-import scala.util.control.{ NonFatal, Breaks }
+import scala.util.control. NonFatal
```

which is more annoying than the trailing whitespace.

**Comment by gabro** [comment]
A very ad-hoc (but probably reasonable) solution would be to remove all surrounding whitespaces when removing the curly braces.

**Comment by olafurpg** [comment]
I've been meaning to simplify the remove importee implementation. It shouldn't have to be this complicated.

**Comment by olafurpg** [comment]
The bug did not surface in the tests since they used `import a.{b,c}` instead of `import a.{ b, c }`.
