### ISSUE TITLE
Silent failures during semanticdb loading

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scalafix#264]
I was running a semantic scalafix rewrite on the stdlib and got this cryptic error message

```scala
java -jar ~/scalafix/scalafix-cli/target/scala-2.12/scalafix.jar -r NoAutoApply --verbose
Automatic classpath=/home/geirsson/scala/src/library/target
error: Type mismatch;
  found    : String (value: "NoAutoApply")
  expected : scalafix.rewrite.Rewrite

Unknown input 'NoAutoApply'. Expected one of: NoValInForComprehension, RemoveXmlLiterals, VolatileLazyVal, ProcedureSyntax, ExplicitUnit, DottyVarArgPattern.

Type mismatch;
  found    : String (value: "NoAutoApply")
  expected : scalafix.rewrite.Rewrite
```

The semanticdb files are there. I suspect an error happened while loading them that disappeared.

**Comment by MasseGuillaume** [comment]
Still referenced here: https://github.com/scalacenter/scalafix/blob/23299d2c343d14b097444b45986ed00eaf9aa526/scalafix-sbt/src/main/scala/scalafix/sbt/ScalafixPlugin.scala#L118

**Comment by olafurpg** [comment]
Thanks @MasseGuillaume, removed in #536
