### ISSUE TITLE
Symbol helpers

### ISSUE THREAD

**Issue by gabro** [scalacenter/scalafix#278]
I've recently found some helpers useful when working with symbols a lot:

```scala
 implicit class TermNameOps(t: Name) {
    def isSymbol(s: String)(implicit mirror: Mirror): Boolean =
      t.symbolOpt.exists(_.normalized.syntax == s)

    def isOneOfSymbols(symbols: Set[String])(implicit mirror: Mirror): Boolean =
      t.symbolOpt.exists(s => symbols.contains(s.normalized.syntax))
  }

  implicit class OptionTermNameOps(t: Option[Name]) {
    def isSymbol(s: String)(implicit mirror: Mirror): Boolean =
      t.flatMap(_.symbolOpt).exists(_.normalized.syntax == s)
  }
```

I've used them in the [cats rewrites](
https://github.com/typelevel/cats/blob/master/scalafix/rewrites/src/main/scala/fix/Cats_v1_0_0.scala#L20-L310), do you think would be worth to include them in core, @olafurpg?

**Comment by gabro** [comment]
They allow for stuff like

```
ctx.tree.collect {
  case t: Term.ApplyInfix if t.op.isOneOfSymbols(someSymbols) => // do stuff
  case t: Term.Name if t.isSymbol(someSymbol) => // do stuff
}
```

**Comment by olafurpg** [comment]
I was just writing similar helpers in collection-strawman rewrites :)

I totally agree we are missing helpers here. I can imagine scenarios when I want
- unmodified/normalized comparison
- string/Symbol comparison
- compare single symbol vs. lookup in set

It might also be nice to provide some unapply helpers so it's possible to perform these inside patterns, just to brainstorm

```scala
val To = new SymbolComparer("_root_.scala.collection.immutable.Range.to.")
// alternative ctors with Set[Symbol]/Set[String]/Symbol
....
case q"$lhs ${To()} $rhs" => q"Range.inclusive($lhs, $rhs)"
...
Name.matchesSymbol(To): Boolean
Option[Name].matchesSymbol(To): Boolean
...
To.matches(Name): Boolean
```

**Comment by olafurpg** [comment]
In what situation would you use `Option[Name].isSymbol`?

**Comment by gabro** [comment]
Here's an example:

https://github.com/typelevel/cats/blob/6b33986186aaf0ac89a51bacfd5fa791c1fe897e/scalafix/rewrites/src/main/scala/fix/Cats_v1_0_0.scala#L131-L145

**Comment by olafurpg** [comment]
I see, interesting. I think we can avoid that handling `Importee.Name/Rename` in the new `SemanticCtx.symbol(Tree)` method I'm adding. PR coming soon!

**Comment by gabro** [comment]
YAY! 🎉

**Comment by olafurpg** [comment]
Only thing missing is https://github.com/scalameta/scalameta/issues/1098 to avoid using Strings to model symbols.
