### ISSUE TITLE
More complex builds for `github:org/repo` rewrites

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scalafix#280]
Currently, github:org/repo rewrites need to fit in a single file. It would be nice if scalafix supported more complex builds to accommodate

* multiple files
* dependencies
* custom scalac options?
* generated sources (e.g., BuildInfo)

There are several ways to achieve this

* add scalafix/build.conf file that includes the build definition (files, dependencies, options). This would mean pretty much re-implementing a build tool.
* invoke sbt programmatically to builds the `scalafix/rewrites` projects from source. `sbt rewrites/fullClasspath`  will give the classpath and scalafix won't have to compile sources itself.

I'm personally leaning towards the second option. I don't have much experience with using sbt programmatically or with sbt source dependencies but if it works then it's a very powerful solution. Also, this solution would give incremental and cached compilation.

**Comment by gabro** [comment]
Yeah, let's not implement our own build tool 👍

**Comment by olafurpg** [comment]
After more thinking, here is what I think strikes a nice balance between supporting more complex builds without reinventing the wheel 

- `github:org/repo` clones org/repo with jgit
- compiles all .scala sources in the `scalafix/rules` directory (and `scalafix/rewrites` for compat with <0.5 directories)
- classload all rules in compiled sources, if there is a `/v1` suffix, classload all rules in package `rule.v1` package

This scheme scales nicely for both migration rewrites with a `/v1` suffix and non-migration rules such as `olafurpg/FinalCaseClass`, which don't have a `/v1` suffix.

This allows rules like `typelevel/cats/v1` to become more complex without requiring a publish step to maven.

**Comment by gabro** [comment]
> github:org/repo clones org/repo with jgit

👍 I would clone it with `--depth=1`

**Comment by olafurpg** [comment]
I suggest that we close this ticket with "Please publish your rule to maven central". Published rules have the same UX as built-in scalafix rules. Rules that want to enjoy the benefits of being compileable from source will need to meet the criteria

- no dependencies
- single file
