### ISSUE TITLE
Migrate build to sbt 1.0

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scalafix#281]
Now that sbt 1.0.0 final is out, I'm opening this to keep track of blocking plugins

- [x] sbt-doge (not needed anymore)
- [x] sbt-buildinfo
- [x] sbt-pgp
- [x] sbt-sonatype
- [x] sbt-dynver
- [x] sbt-scalajs (need to upgrade to scalajs 1.0 first)
- [x] sbt-scalatex (https://github.com/lihaoyi/Scalatex/pull/60)
- [x] sbt-ghpages
- [x] sbt-site (coming soon it seems)
- [x] sbt-dotty
- [x] sbt-scalajs-bundler

It would be really nice to be able to migrate to sbt 1.0.

**Comment by joan38** [comment]
I think sbt-scalajs-bundler now supports SBT 1.0

**Comment by barambani** [comment]
The support for Sbt 1.0 in sbt-scalajs-bundler is released

https://github.com/scalacenter/scalajs-bundler/blob/master/manual/src/ornate/changelog.md

**Comment by barambani** [comment]
It looks like Dotty is not yet ready (https://github.com/lampepfl/dotty/issues/3091) and the work is low priority there

**Comment by MasseGuillaume** [comment]
Almost done: https://github.com/lampepfl/dotty/pull/3441

**Comment by olafurpg** [comment]
The build is now using sbt 1.2.1 😎
