### ISSUE TITLE
SemanticCtx.denotation(Position/Name)

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scalafix#286]
I've been working with SemanticCtx for sbtfix today and I keep writing the same sequence
```
      sctx
        .symbol(r.pos)
        .flatMap(sctx.denotation)
```

It would be nice if SemanticCtx provided more utilities for this.

**Comment by gabro** [comment]
Big 👍. Something like a 'denotation' method on trees just like  'symbol' would be great
