### ISSUE TITLE
Rename Rewrite to Checker/Rule?

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scalafix#293]
Following discussion in https://github.com/scalacenter/scalafix/pull/291#issuecomment-323002649.

Now that rewrites can emit linter warnings, the name "Rewrite" may be confusing for linters that don't rewrite. Would it make sense to rename `scalafix.Rewrite` to `scalafix.rule`?

**Comment by olafurpg** [comment]
After having looked around names clang-tidy, fb infer and pylint use, I think a more appropriate name for a scalafix rewrite would be a "Checker".

**Comment by gabro** [comment]
Just to throw another one in the mix, [eslint](https://eslint.org/) uses Rule and rules can be "fixable". But I'm totally ok with Checker

**Comment by olafurpg** [comment]
Interesting. I think `Rule` is equally fine then.

Question is, what should `Rewrite.rewrite` become then?
```scala
Rewrite.rewrite
Checker.check
Rule.rule ?
Rule.check ?
Rule.apply ?
```

**Comment by xeno-by** [comment]
I vote for Checker.check.

**Comment by gabro** [comment]
Ok, let the bike shedding begin! 🚲 

`Checker` is ok, but I would expect a checker to only check, not to actually do anything.

`Rule` is instead more "prescriptive": here's the rule, and you can either:
- check it
- apply a fix

`Rule.check`
`Rule.fix`

(this follows eslint's convention)

**Comment by olafurpg** [comment]
Rule it is! We discussed this at the Scala Center meeting yesterday and we were unanimously in favor of Rule.fix/Rule.check over Checker. PR coming soon!
