### ISSUE TITLE
Publish sonatype SNAPSHOT on merge

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scalafix#311]
This should be simple to configure since CI already knows how to publish non-SNAPSHOT. This would make it possible for people to try out newly merged features without a tag push.

**Comment by xeno-by** [comment]
Looks like we've gone full circle on prerelease builds. Snapshots on every merge > Stable prereleases on every merge > Stable prereleases every now and then > Snapshots on every merge :)

**Comment by olafurpg** [comment]
After some consideration I am more in favor of cutting regular releases more frequently, it's only a tag push away.
