### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException:

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scalafix#319]
Caught while running on akka

```
error: Failed to fix /Users/ollie/dev/akka/akka-bench-jmh/src/main/scala/akka/stream/NewLayoutBenchmark.scala
java.lang.ArrayIndexOutOfBoundsException: -1
	at scala.meta.tokens.Tokens.apply(Tokens.scala:30)
	at scalafix.util.TokenList.prev(TokenList.scala:57)
	at scalafix.internal.patch.ImportPatchOps$.loop$1(ImportPatchOps.scala:44)
	at scalafix.internal.patch.ImportPatchOps$.fallbackToken(ImportPatchOps.scala:46)
	at scalafix.internal.patch.ImportPatchOps$.superNaiveImportPatchToTokenPatchConverter(ImportPatchOps.scala:88)
	at scalafix.patch.Patch$.semanticApply(Patch.scala:177)
```

**Comment by ag91** [comment]
Hi, we were trying to reproduce this on the akka's commit c8748e8cf0, but we were unsuccessful.
However, this issue is due to how scala meta Tokens are used: the length used by scalafix.util.TokenList does not have the usual definition https://github.com/scalameta/scalameta/blob/1af15eb96c30c437d1b4aa57aca1740a36ed44a4/scalameta/tokens/shared/src/main/scala/scala/meta/tokens/Tokens.scala#L31

**Comment by olafurpg** [comment]
Thanks for investigating this @ag91 how do you think `length` should be implemented?

**Comment by ag91** [comment]
Hi, I think that usual definition of length comes with a contract: length cannot be less than 0.
However, I am suggesting to not assume this contract, and handle this case in the scalafix.util.TokenList. 
Ideally we can raise the issue to the Scalameta maintainer and see if it was intended.

**Comment by olafurpg** [comment]
I'm a Scalameta maintainer and I'm happy to merge a PR updating the implementation to `max(0, end - start)`, we can release the fix this week in the upcoming 2.0.2. Would you be interested in sending a PR?

**Comment by ag91** [comment]
Of course we (with @goldenzero) will send a PR today.

**Comment by ag91** [comment]
We have investigated further and we now believe that this error belongs to scalafix.util.TokenList only. 
I think that using max for scalameta's length is still a good idea, but we could not find an erroneous test case. Do you think is still worth opening a pull request for scalameta?
