### ISSUE TITLE
ExplicitImplicit: allow to omit types for local implicit vals

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scalafix#34]
Type annotations for local implicit vals are optional for local implicit vals, see https://github.com/lampepfl/dotty/pull/1785

```scala
def foo = {
  // this is OK
  implicit val localImplicit = 2
}
```
ExplicitImplicit should have a flag to not insert type annotations for local implicit vals.

**Comment by erikwj** [comment]
Is this the expected behaviour? 

```
object ExplicitImplicit {
  
  implicit val objectImplicitInt: Int = 2 // is ok
  implicit val objectInt = 2 // => this requires Type
  
  def explicitReturnType = {
    // this is OK
  	implicit val LocalImplicit: Int = 2
  }
  
  
  def foo = {
    // this is OK
    implicit val localImplicit = 2
  }
}
```

Should be fixed into: 

```
object ExplicitImplicitFixed {
  
  implicit val objectImplicitInt: Int = 2 // this is OK
  implicit val objectInt: Int = 2 // => this is OK
  
  def explicitReturnType = {
    // this is OK
  	implicit val LocalImplicit: Int = 2
  }
  
  
  def foo = {
    // this is OK
    implicit val localImplicit = 2
  }
}
```

**Comment by erikwj** [comment]
And is it correct that this relates to ExplicitResultTypes?

**Comment by olafurpg** [comment]
Correct @erikwj If the definition can't be globally referenced (like `localImplicit` in `foo`) then it does not need be annotated with a result type.

**Comment by erikwj** [comment]
I'll give it a try the coming weeks, see if I can add this to the lib

**Comment by olafurpg** [comment]
Very cool @erikwj I think it's actually possible to implement this in a very simple way: skip the rule if the definition symbol is an instance of `scala.meta.Symbol.Local`. You can get the symbol with `name.symbol` if you have `import scalafix.syntax._` and an `implicit SemanticdbIndex` in scope.

Some context, the `isLocal` method here is essentially wrong, it should check against `Symbol.Local`
https://github.com/scalacenter/scalafix/blob/769df495896253ad985a7b068acdbf0bbadbb2a1/scalafix-core/shared/src/main/scala/scalafix/internal/rule/ExplicitResultTypes.scala#L115

We can do that by passing in `Name` for each of the definitions in 
https://github.com/scalacenter/scalafix/blob/769df495896253ad985a7b068acdbf0bbadbb2a1/scalafix-core/shared/src/main/scala/scalafix/internal/rule/ExplicitResultTypes.scala#L128-L136

For val/var, you can pattern match to get `.pats.head.name` (`.pats` is a `List[Pat.Var]` to encode syntax like `val a, b = 2`)

**Comment by erikwj** [comment]
Wow @olafurpg that's a big help. This Friday I'll give it a first try.

**Comment by erikwj** [comment]
@olafurpg Why doesn't this https://github.com/erikwj/scalafix/blob/7702cf7746bf248701af393f0a19ab4df2f2bedc/scalafix-tests/output/src/main/scala/test/explicitResultTypes/ExplicitResultTypesBase.scala#L10   need an explicit resulttype?

**Comment by olafurpg** [comment]
@erikwj Literals are classified as "simple" and are therefore skipped https://github.com/scalacenter/scalafix/blob/7702cf7746bf248701af393f0a19ab4df2f2bedc/scalafix-core/shared/src/main/scala/scalafix/internal/rule/ExplicitResultTypes.scala#L109

**Comment by erikwj** [comment]
@olafurpg I think I fixed it except for the flag. Should this come from global scalafix config, or tight to this rule. Any examples of a rule using flags? Thx

**Comment by olafurpg** [comment]
Cool @erikwj ! Do you mean the option to skip local implicits? Configuration for ExplicitResultType is done here
 https://github.com/scalacenter/scalafix/blob/598c54c93c07a98b77108954ee3dc2ed68c23c00/scalafix-core/shared/src/main/scala/scalafix/internal/config/ExplicitResultTypesConfig.scala#L9

We can add a field `skipLocalImplicits: Boolean = true` and that will be picked up during initialization of the rule https://github.com/scalacenter/scalafix/blob/598c54c93c07a98b77108954ee3dc2ed68c23c00/scalafix-core/shared/src/main/scala/scalafix/internal/rule/ExplicitResultTypes.scala#L34

**Comment by erikwj** [comment]
Thanks, could have found that myself ... 
Will add it
