### ISSUE TITLE
ctx.removeTokens(Seq[Token]) instead of ctx.removeTokens(Tokens)

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scalafix#344]
This should be a source compatible change since Tokens <: Seq[Token]

**Comment by barambani** [comment]
Hi @olafurpg I'm giving a look at this. Do you think that also 

```
def toks(t: Tree): Tokens
```

should return a `Seq[Token]` or changing `removeTokens` is enough ?

**Comment by barambani** [comment]
I got my answer from Travis. I'll fix it. Thanks

**Comment by gabro** [comment]
Yep :) Thanks!
