### ISSUE TITLE
Configurable NoInfer

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scalafix#347]
It should be possible to provide custom symbols that should not be inferred by the compiler, for example any2stringadd.

```
NoInfer.extraSymbols = [
  "_root_.scala.Predef.any2stringadd."
]
```

**Comment by gabro** [comment]
I would make it entirely configurable with a default. If you customize it, you also need to provide the rest of them. This enables user to remove some of the default ones if they wish so.

**Comment by olafurpg** [comment]
Pending fix in https://github.com/scalacenter/scalafix/pull/355

**Comment by MasseGuillaume** [comment]
Implemented in https://github.com/scalacenter/scalafix/pull/398
