### ISSUE TITLE
Doc refers to scalafix 0.5.0-5-afe851e3

### ISSUE THREAD

**Issue by eed3si9n** [scalacenter/scalafix#360]
## steps

open https://scalacenter.github.io/scalafix/

## problem

it refers to 

```scala
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.5.0-5-afe851e3")
```

## expectation

```scala
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.5.0")
```

**Comment by olafurpg** [comment]
Thanks for reporting! This is a regression from https://github.com/scalacenter/scalafix/pull/359 which got merged last night.
