### ISSUE TITLE
semanticdb-sbt instruction

### ISSUE THREAD

**Issue by eed3si9n** [scalacenter/scalafix#361]
## steps

https://scalacenter.github.io/scalafix/#semanticdb-sbt

## problem

> semanticdb-sbt is a Scala 2.10 compiler plugin that extracts semantic information from the sbt compiler. To enable semanticdb-sbt,

```scala
// ~/.sbt/0.13/plugins/plugins.sbt
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.5.0-5-afe851e3")
```

```scala
// ~/.sbt/0.13/build.sbt
import scalafix.sbt.ScalafixPlugin.autoImport._
sbtfixSettings // enable semanticdb-sbt for sbt metabuilds.
```

I am not sure if that would actually inject semanticdb on the metabuild.
Plus it's global.

## suggestion

Here's something that seems to work for me:

Add `project/scalafix.sbt` to your build:

```scala
libraryDependencies += compilerPlugin("org.scalameta" % "semanticdb-sbt" % "0.4.0" cross CrossVersion.full)
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.5.0")
```

**Comment by olafurpg** [comment]
Thanks for reporting! iiuc, the suggested workaround would mean that `project/*.sbt` files would not be compiled with the semanticdb plugin?

I totally agree that enabling sbt-scalafix globally is a bad idea, at least with the current impl. A per-project installation is desirable. I think we can provide two different installation instructions and explain the tradeoffs between the two. wdyt?

**Comment by eed3si9n** [comment]
> iiuc, the suggested workaround would mean that project/*.sbt files would not be compiled with the semanticdb plugin?

Isn't that same for current putting it in global plugin? If you want the `project/*.sbt` to compile with a complier plugin, you'd probably need to make a symbolic link for `project/project/scalafix.sbt` from `project/scalafix.sbt`.

**Comment by olafurpg** [comment]
Support for semantic rewriting of *.sbt is quite fragile and barely supported at the moment. I won't have time to work so I think it's best to remove this feature instead of advertise a half-working solution. It will still be possible to do syntactic rules for *.sbt files.
