### ISSUE TITLE
Created semantic patch without extending SemanticRule

### ISSUE THREAD

**Issue by abeln** [scalacenter/scalafix#372]
I have a rule that seems (to me) like it's syntactic and not semantic: [code](https://pastebin.com/eMPfbbNc).

However, when I test it, I get an exception saying that one of the patches (the added import statement) is semantic. Should it be possible to create a semantic patch without extending SemanticRule?

```
[info] Nullify_Tests:
[info] - scala/ca/uwaterloo/cs/nullify/NullifyTest.scala *** FAILED ***
[info]   scalafix.internal.util.Failure$Unsupported: Semantic patches are not supported without a SemanticdbIndex: List(AddGlobalImport(DenullifyWrapper3571.denullify))
[info]   at scalafix.patch.Patch$.apply(Patch.scala:158)
[info]   at scalafix.testkit.SemanticRuleSuite.$anonfun$runOn$1(SemanticRuleSuite.scala:131)
[info]   at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:12)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
[info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[info]   ...
[info]   Cause: java.lang.UnsupportedOperationException: Semantic patches are not supported without a SemanticdbIndex: List(AddGlobalImport(DenullifyWrapper3571.denullify))
[info]   at scalafix.internal.util.Failure$Unsupported.<init>(Failure.scala:29)
[info]   at scalafix.patch.Patch$.apply(Patch.scala:158)
[info]   at scalafix.testkit.SemanticRuleSuite.$anonfun$runOn$1(SemanticRuleSuite.scala:131)
[info]   at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:12)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:1
```

**Comment by abeln** [comment]
If I remove the added import statement, the test passes.

**Comment by ShaneDelmore** [comment]
AddGlobalImport is a semantic operation.

**Comment by olafurpg** [comment]
`addGlobalImport(Importer)` is a syntactic operation since it doesn't require access to symbols. Scalafix should not fail here.

**Comment by abeln** [comment]
Hmm, even `RuleCtxImpl` says AddGlobalImport is a syntactic operation
https://github.com/scalacenter/scalafix/blob/f095438f25a050bebf635415f92f5f7a54cdbd26/scalafix-core/shared/src/main/scala/scalafix/internal/rule/RuleCtxImpl.scala#L72

The code in `ImportPatchOps` that converts a "high-level" AddGlobalImport patch into a sequence of `TokenPatch`es uses the `semanticDbIndex`, suggesting that it's in fact a semantic operation.
https://github.com/scalacenter/scalafix/blob/f095438f25a050bebf635415f92f5f7a54cdbd26/scalafix-core/shared/src/main/scala/scalafix/internal/patch/ImportPatchOps.scala#L72

Which one is it?

**Comment by ShaneDelmore** [comment]
@olafurpg Thanks for the clarification.  I have been under the mistaken impression AddGlobalImport was semantic for a while now.

**Comment by olafurpg** [comment]
@ShaneDelmore there are two overloads of addGlobalImport, one syntactic and one semantic 

https://github.com/scalacenter/scalafix/blob/d511c19c5e98dfd501a848bea194994e26ac686e/scalafix-core/shared/src/main/scala/scalafix/patch/PatchOps.scala#L25

https://github.com/scalacenter/scalafix/blob/d511c19c5e98dfd501a848bea194994e26ac686e/scalafix-core/shared/src/main/scala/scalafix/patch/PatchOps.scala#L90

**Comment by olafurpg** [comment]
I opened #382 to fix this issue https://github.com/scalacenter/scalafix/pull/382
