### ISSUE TITLE
addLeft's implementation doesn't match its specification

### ISSUE THREAD

**Issue by abeln** [scalacenter/scalafix#373]
PatchOps.addLeft claims to add a string to the *first* token of the tree: https://github.com/scalacenter/scalafix/blob/f095438f25a050bebf635415f92f5f7a54cdbd26/scalafix-core/shared/src/main/scala/scalafix/patch/PatchOps.scala#L52

However, the implementation in `RuleCtxImpl` adds the string to the *last* token:

```
def addLeft(tree: Tree, toAdd: String): Patch =
  toks(tree).lastOption.fold(Patch.empty)(addLeft(_, toAdd))
```
https://github.com/scalacenter/scalafix/blob/f095438f25a050bebf635415f92f5f7a54cdbd26/scalafix-core/shared/src/main/scala/scalafix/internal/rule/RuleCtxImpl.scala#L88

Should that be `headOption` instead of `lastOption`? If so, I'd be happy to send a PR.
If not, IMO we should update the comment to reflect what the code is doing.

**Comment by gabro** [comment]
I think you're right, it should be `headOption`. It's probably a copy-paste went bad from `addRight` and we never realized since the `addLeft` overload that accepts a `Tree` has never been used.

Unless @olafurpg has something to say about this, you can send a PR to fix this :)
