### ISSUE TITLE
Crossbuilding with SBT 1.0

### ISSUE THREAD

**Issue by joan38** [scalacenter/scalafix#374]
Hi,

That would be cool to crossbuild with SBT 1.0.

We currently have a dependency on sbt-dotty as far as I understand in https://github.com/scalacenter/scalafix/issues/281, but if we upgrade to 0.13.16 we should be able to cross build?

Cheers

**Comment by gabro** [comment]
For some reason I thought this was already implemented. #375 should do the trick
