### ISSUE TITLE
Consider renaming RuleCtx 

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scalafix#379]
Following up on discussion with @gabro. It's not clear that RuleCtx is the context for a single source file. Some alternative names that might be clearer

- FileContext
- DocumentContext

**Comment by gabro** [comment]
Following this spirit, I would probably start looking for a new home for the concrete implementation of PatchOps. 

Those patch ops are not really about the current file context, are they?

**Comment by olafurpg** [comment]
I've thought about moving PatchOps too, I think it could be a good move as well. The original motivation to put patch ops under RuleCtx was because 

- Tree.tokens takes an implicit Dialect which I thought was necessary from RuleCtx. I'm no longer sure if it's actually necessary, however.
- I thought a few patch ops would need access to configuration. However, most of them don't need access to configuration options so maybe we can let the ones that do accept configuration accept take them in as method parameters.

I would love to have PatchOps be an object with only static methods. This deserves another issue however.

**Comment by olafurpg** [comment]
I'm tempted to rename to `Context`, it leaves it sufficiently open but already greatly improves on readability compared to RuleCtx

**Comment by olafurpg** [comment]
An interesting suggestion from @gabro while discussing offline. Rename `RuleCtx` to `Document`. 

```scala
// before
ctx.tree.collect { ... }
// before
document.tree.collect { ... }
```

I like the idea. The only downside I see is the conflict with `scala.meta.Document` which may cause headaches for `import scalafix._; import scala.meta._`. Given that `scala.meta.Document` will go away soon I think using `scalafix.Document` might be a good idea down the road. I propose to let this renaming wait for a while longer.

**Comment by olafurpg** [comment]
PR #737 introduces `scalafix.v1.Doc` and `scalafix.v1.SemanticDoc` to replace `RuleCtx`. The shorthand "Doc" was chosen instead of "Document" to avoid conflicts with the old `scala.meta.Document` (now moved to `scalafix.v0.Document`). There is plenty of time to rename `Doc`/`SemanticDoc` to something more self-explanatory, any suggestions? If no suggestions we can close this ticket.

**Comment by olafurpg** [comment]
`RuleCtx` is `SemanticDoc` in scalafix.v1! Only a handful of days left to suggest  an alternative before v0.6.0-RC1

**Comment by ShaneDelmore** [comment]
Is It SyntacticDoc or just Doc for syntactic rewrites?

**Comment by olafurpg** [comment]
It's a good question, I've been leaning towards `SyntacticDoc` lately. Currently, it's only `Doc` but it's maybe a bit too short 🤔

**Comment by ShaneDelmore** [comment]
Either works for me, just wanted to make sure there was a way to tell Syntactic rules apart.

**Comment by gabro** [comment]
One day I will win this battle and convince @olafurpg to add the remaining letters to all those words

- SemanticDoc -> SemanticDocument
- Doc -> SyntacticDocument
- Mod -> Modifier

😇

**Comment by ShaneDelmore** [comment]
@olafurpg sees your wasted characters and counters with:
Import.{SemanticDoc => sd, SyntacticDocument => d}

**Comment by olafurpg** [comment]
I'm sold on 

- SyntacticDocument
- SemanticDocument

The reason I originally used `Doc` was in order to avoid ambiguous references with `scala.meta.Document` when importing `meta._, v1._`. Will go ahead with this rename today!
