### ISSUE TITLE
Consider moving PatchOps out of RuleCtx

### ISSUE THREAD

**Issue by gabro** [scalacenter/scalafix#380]
Following a discussion in https://github.com/scalacenter/scalafix/issues/379#issuecomment-332743569 it would probably make sense to move the path operations into a static object, rather than having them on the `ctx` instance.

If there are ops that require configuration, we can pass it as a parameter.

**Comment by olafurpg** [comment]
This was fixed in #737, the `PatchOps` methods now live a simple defs on the `Patch` object.
https://github.com/scalacenter/scalafix/blob/264a8ffc15e74c5ce994d913786bb9ffd4ea5929/scalafix-core/shared/src/main/scala/scalafix/patch/Patch.scala#L114-L169
