### ISSUE TITLE
Website chores

### ISSUE THREAD

**Issue by gabro** [scalacenter/scalafix#393]
- [x] add `noPublish`
- [x] use 2.12 for building the website (so that apidocs are for 2.12, which is much nicer)
- [ ] test against 404 links in CI (maybe using something like http://digitaldrummerj.me/jekyll-validating-links-and-images/ or https://www.npmjs.com/package/broken-link-checker)
- [ ] get prettier thumbnail 

<img width="647" alt="screen shot 2017-10-21 at 12 06 17" src="https://user-images.githubusercontent.com/1408093/31850749-44c2446c-b658-11e7-951c-2ba7eea5e156.png">

**Comment by olafurpg** [comment]
The website has now been ported to docusaurus! We still haven't integrated 404 link checking, but mdoc does validate that local hyperlinks point to existing sections :)
