### ISSUE TITLE
FileNotFoundException when passing an absolute path to "file:"

### ISSUE THREAD

**Issue by dwijnand** [scalacenter/scalafix#417]
If I invoke `scalafix file:/d/sbt/scalafix/rules/src/main/scala/fix/sbt_v1_1.scala` I get:

```
error: java.io.FileNotFoundException: /d/sbt-travisci/d/sbt/scalafix/rules/src/main/scala/fix/sbt_v1_1.scala (No such file or directory)
```

Scalafix 0.5.3

**Comment by olafurpg** [comment]
Thank you for reporting! This got fixed yesterday in https://github.com/scalacenter/scalafix/pull/408 😄  I'm hoping to get a new release out tomorrow.

**Comment by gingerkirsch** [comment]
Hello, I am still facing this issue at moment https://gist.github.com/gingerkirsch/06b38ff5d8fdaa2e2c01808e31940712

**Comment by ShaneDelmore** [comment]
Your example has file:file: instead of just file: @gingerkirsch

**Comment by gingerkirsch** [comment]
That is my problem @ShaneDelmore . I typed file: in the initial command once and got file:file: instead.
I tried in all possible ways, here more two without any file:
https://gist.github.com/gingerkirsch/bfff601879e84f031ae8ca2240083e4e
I think the "file:" is broken

**Comment by olafurpg** [comment]
@gingerkirsch are you able to reproduce outside of sbt?

```
coursier launch ch.epfl.scala:scalafix-cli_2.12.4:0.5.10 --main scalafix.cli.Cli -- file:...
```

@MasseGuillaume can you take a look?

**Comment by olafurpg** [comment]
@gingerkirsch what happens if you run `scalafixCli -r file:/...` from sbt?

**Comment by gingerkirsch** [comment]
Outside of sbt file not found - https://gist.github.com/gingerkirsch/fa607e0de4c4fe8765ccefcdc2d87ad2
From sbt also not found and path is rewritten with file:file: 
https://gist.github.com/gingerkirsch/68c213497d5eece28e49cb4e3078df93

**Comment by olafurpg** [comment]
That looks like a bug indeed @gingerkirsch Can you take a look @MasseGuillaume ?

**Comment by olafurpg** [comment]
@gingerkirsch I am able to reproduce the bug in sbt-scalafix but not with the cli. Your cli gist is missing the `-r` flag so `file:/...` is interpreted as the filename that you are fixing. It works with the cli with `scalafix -r file:rules/src/... <files-to-fix>`.

The culprit is likely this line here https://github.com/scalacenter/scalafix/blob/56fa55f691a8acf602fe00f8195c394925fccb24/scalafix-sbt/src/main/scala/scalafix/internal/sbt/ScalafixCompletions.scala#L141

The test doesn't seem to check against `file:file://` https://github.com/scalacenter/scalafix/blob/56fa55f691a8acf602fe00f8195c394925fccb24/scalafix-sbt/src/test/scala/scalafix/internal/sbt/ScalafixCompletionsTest.scala#L190

**Comment by gingerkirsch** [comment]
@olafurpg yes it does work this way and applies the rule, however, I get "No semanticdb associated"
https://gist.github.com/gingerkirsch/ba8a0e58e6b121c9a5d932788effb5e2
I am trying a very simple example at moment and apply it to input folder so the diff would be little to analyze https://github.com/gingerkirsch/scalafix but same happens on other source folders.
What am I missing?
I've found a similar issue https://github.com/scalacenter/scalafix/issues/331, maybe it has to do with versions again?

**Comment by MasseGuillaume** [comment]
@olafurpg 

I just tested locally and the completion for `--rules file:/<TAB>` works fine


```
> scalafix --rules <TAB>
--auto-suppress-linter-errors                                                 
--diff                                                                        
--diff-base                                                                   
--files                                                                       
--help                                                                        
--rules                                                                       
--test                                                                        
--verbose                                                                     
DisableSyntax           -- Linter that reports an error on a configurable s   
ExplicitResultTypes     -- Rewrite that inserts explicit type annotations f   
LeakingImplicitClassVal -- Add private access modifier to val parameters of   
NoAutoTupling           -- Rewrite that inserts explicit tuples for adapted   
NoValInForComprehension -- Rewrite that removes redundant val inside for-co   
ProcedureSyntax         -- Rewrite that inserts explicit : Unit = for soon-   
RemoveUnusedImports     -- Rewrite that removes unused imports reported by    
RemoveUnusedTerms       -- Rewrite that removes unused locals or privates b   
file:                                                                         
github:                                                                       
http:                                                                         
https:                                                                        
replace:                                                                      
scala:  
```

```
> scalafix --rules f<TAB>
```

inserts `ile:`

```
> scalafix --rules file:<TAB>
.git                          .git/COMMIT_EDITMSG           
.git/HEAD                     .git/branches                 
.git/config                   .git/description              
.git/hooks                    .git/index                    
.git/info                     .git/info/exclude             
.git/logs                     .git/logs/HEAD                
.git/logs/refs                .git/logs/refs/heads          
.git/logs/refs/heads/master   .git/objects                  
.git/refs                     .gitignore                    
build.sbt                     project                       
src                           src/main                      
src/main/scala                src/main/scala/Main.scala     
target    
```

```
> scalafix --rules file:/<TAB>
/bin         /bin/sh      /boot        /dev         /dev/dm-0    /dev/vcs3    
/dev/vcs4    /dev/vcs5    /dev/vcs6    /dev/vcs7    /dev/vcsa3   /dev/vcsa4   
/dev/vcsa5   /dev/vcsa6   /dev/vcsa7   /etc         /home        /nix         
/proc        /root        /run         /sys         /tmp         /usr         
/var   
```

```scala
// /home/gui/example-scalafix-rule/scalafix/rules/src/main/scala/fix/Examplescalafixrule_v1.scala
package fix

import scalafix.v1
import scalafix.v0

class Syntactic extends v1.SyntacticRule("SyntacticRule") {
  override def fix(implicit doc: v1.Doc): v1.Patch = {
    if (doc.input.text.contains(s"// v1 $name!")) v0.Patch.empty
    else v0.Patch.addRight(doc.tree, s"// v1 $name!\n")
  }
}
```

```
> scalafix --rules file:/home/gui/example-scalafix-rule/scalafix/rules/src/main/scala/fix/Examplescalafixrule_v1.scala
[success] Total time: 1 s, completed Aug 31, 2018 12:42:33 AM```

**Comment by olafurpg** [comment]
@MasseGuillaume I am able to reproduce the bug 
```
sbt:sbt-scalafix> scalafix  file:/Users/ollie/dev/example-scalafix-rule/scalafix/rules/src/main/scala/fix/Examplescalafixrule_v1.scala
[error] (Compile / scalafix) java.nio.file.NoSuchFileException: /Users/ollie/dev/sbt-scalafix/file:/Users/ollie/dev/example-scalafix-rule/scalafix/rules/src/main/scala/fix/Examplescalafixrule_v1.scala
```

I'll try to fix it 💪
