### ISSUE TITLE
Failure on website/scalaunidoc:unidoc

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scalafix#423]
When running `sbt website/makeMicrosite` on the master branch the task `website/scalaunidoc:unidoc` fails.

**Comment by gabro** [comment]
The CI seems to be fine with it, which version of Scala are you seeing this on?

**Comment by MasseGuillaume** [comment]
On scalafix itself. I cloned a fresh repo and it worked. It's probably a scaladoc comment I added on my branch that make it crash.

**Comment by gabro** [comment]
Cool, so this is a false alarm?

**Comment by MasseGuillaume** [comment]
Yup ;-). Is there a way we can improve this error? I only know it's related to scaladoc comments because @olafurpg told me so.

**Comment by gabro** [comment]
That seems like a unidoc-specific issue. I'm not sure we can intercept it and print something better.
