### ISSUE TITLE
List rules in the classpath

### ISSUE THREAD

**Issue by gabro** [scalacenter/scalafix#429]
Suggested at https://gitter.im/typelevel/cats-dev?at=5a0a99a8614889d4757a4a50

If library authors distribute scalafix rules via maven, it would be nice to allow users to discover the ones available in the classpath.

**Comment by olafurpg** [comment]
This sounds similar to what me and @ShaneDelmore discussed about the other day. The general idea was to have a convention to put a file like `/scalafix/Rules.scala` in the jar resources, and scalafix would lookup that file in each of the jars in the provided --classpath. `Rules.scala` would be classloaded as a scalafix plugin https://github.com/scalacenter/scalafix/issues/304 so it can delegate to multiple rules, even defined in other files. Once we have plugins working, it should be possible to explore the loaded rules from the cli or sbt plugin with tab completion, and once we get #422 we can display descriptions alongside the rules.

**Comment by olafurpg** [comment]
Fixed in #825 See https://github.com/scalacenter/scalafix/blob/43edb901c956c5b50d29ebd0a4bb2c463832268b/scalafix-interfaces/src/main/java/scalafix/interfaces/ScalafixMainArgs.java#L124-L130

Next step is #822 to support tab-completion for those rules.
