### ISSUE TITLE
Document + Report when a rules does not have a default constructor.

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scalafix#432]
I'm running `unit/testOnly scalafix.tests.rule.SemanticTests` and a test fails with:

```
[info] - scala/test/DisableSyntax.scala *** FAILED *** (7 milliseconds)
[info]   java.lang.IllegalStateException: Type mismatch;
[info]   found    : String (value: "DisableSyntax")
[info]   expected : scalafix.rule.Rule
```

This is due to not having an empty constructor:

```scala
final case class DisableSyntax(config: DisableSyntaxConfig) extends Rule("DisableSyntax") with Product {
  // ...
}
```

The error reported should be something along those lines:

```
Cannot instantiate `DisableSyntax`. `Rule`s need default parameters for all fields and `SemanticRule`s need default parameters for all fields except `SemanticdbIndex`.
```

**Comment by MasseGuillaume** [comment]
It's reported here correctly but it does not flow back to the user:

https://github.com/scalacenter/scalafix/blob/f16cc22a66fb71fa9db2f3b02960daab6d5adcce/scalafix-core/shared/src/main/scala/scalafix/internal/config/ScalafixMetaconfigReaders.scala#L101

**Comment by olafurpg** [comment]
I agree the error message is confusing and the website should document more clearly the requirement that rules must have an empty argument constructor (and default parameter values are not enough!).
