### ISSUE TITLE
Add a way to customize LintMessage

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scalafix#439]
Related: https://github.com/scalacenter/scalafix/issues/436#issue-274638213

**Comment by olafurpg** [comment]
Can you give more details? I don't think we need a new field to LintMessage, we can use the existing `.message` and `category.explanation`.

**Comment by MasseGuillaume** [comment]
@olafurpg for example: https://github.com/scalacenter/scalafix/pull/443

**Comment by olafurpg** [comment]
Has this been fixed with CustomMessage @MasseGuillaume ?

**Comment by MasseGuillaume** [comment]
Yup
