### ISSUE TITLE
Testkit: Alternative way to assert rules

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scalafix#440]
Related: https://github.com/scalacenter/scalafix/issues/436#issuecomment-345193468

```scala
Await.result(longComputation)// assert: Disable.Await.result
```

to

```scala
Await.result(longComputation)
/*
^ DisableSyntax.Await.result

Are you sure that you want to use Await.ready? In most cases, you should use ThreadUtils.awaitReady instead.
If you must use Await.ready, wrap the code block with
// scalafix:off DisableSyntax.Await.result
Await.ready(...)
// scalafix:on DisableSyntax.Await.result
*/
```

I think we should add an alternative way to test lint message by asserting the caret position and the message content. This is also really helpful to test custom messages: #439.

@olafurpg is concern that the test suite becomes too verbose.

@gabro WDYT ?

**Comment by olafurpg** [comment]
My personal view is that testing the actual message content is not necessary since messages are typically only string literals with minimal splicing. You can manually check how the message looks by skipping an `// assert` and testkit prints the message out to the console just like the cli does.

**Comment by MasseGuillaume** [comment]
Just to clarify I don't want to change the current method of asserting in testkit. I want to provide an additional way to assert.

**Comment by olafurpg** [comment]
I may have misunderstood you @MasseGuillaume, I think adding a `/* assertMessage */` could be a nice addition.

```scala
object Disable {
  Await.result(...) /* assertMessage: Await.result is disabled
  ^
Explanation: Are you sure that you want to use Await.ready? In most cases, you should use ThreadUtils.awaitReady instead.
If you must use Await.ready, wrap the code block with
// scalafix:off DisableSyntax.Await.result
Await.ready(...)
// scalafix:on DisableSyntax.Await.result
*/

```

**Comment by MasseGuillaume** [comment]
Fixed in: https://github.com/scalacenter/scalafix/pull/448
