### ISSUE TITLE
Sponsorship of Vladimir for Functional Programming features

### ISSUE THREAD

**Issue by fommil** [scalacenter/scalafix#451]
I am donating $4k of the (future) profits from [Functional Programming for Mortals with Scalaz](https://leanpub.com/fpmortals/) to Vladimir Polushin (@vovapolu) to improve scalafix, specifically for use in principled Functional Programming libraries and applications. Vladimir has already proven to be a capable developer and has delivered on two Scala Google Summer of Code projects and has been the [ENSIME sponsored developer](http://ensime.org/sponsor/) for several months.

A wise man once said that the more you learn about Scala, the more you learn what **not** to write. Much of the knowledge of what not to write can be codified in scalafix, a Scala Center project, often with automated rewrite rules. Although the goal of the [wartremover](https://github.com/wartremover/wartremover) project was similar, to restrict the developer to a safe subset of the Scala language, it is burdened by limitations of the compiler API that are only overcome by scala.meta and scalafix.

My priorities in the two months of Vladimir's time that I am funding are:

- to implement new linters that I specifically wish to use (note that `Disable` is similar, but not the same as requiring certain methods to be called inside `IO`) [scalazzi tickets](https://github.com/scalacenter/scalafix/issues?utf8=%E2%9C%93&q=scalazzi)
- to migrate the core wartremover warts to scalafix https://github.com/scalacenter/scalafix/issues/529
- to ensure that the scalafix sbt plugin runs performantly on an sbt 1.0 build and respects per project and config scoping rules #461 

If you would like to continue funding Vladimir, I urge you to contribute on bountysource, a sponsorship programme has been set up at:

  https://salt.bountysource.com/teams/scalafix

// @ClaireNeveu

**Comment by olafurpg** [comment]
Woot! I'm am thrilled @fommil. Thank you.

I hope this inspires more people to invest in Scala developer tooling, it's a ripe area sorely missing more funding.

I am eager to help Vladimir succeed in this project. I have seen him do great work in ENSIME (and scalafmt!), I'm excited to see what he will contribute to scalafix. I am happy to discuss more details over video chat if you want.

**Comment by gabro** [comment]
Much ❤️ and thank you @fommil! I'm a big fan of linters and I'm thrilled to see scalafix become a standard tool for Scala programmers in that area

**Comment by fommil** [comment]
Closing in preference for the detailed tickets under the "Sponsored" label https://github.com/scalacenter/scalafix/issues?utf8=%E2%9C%93&q=label%3Asponsored+
