### ISSUE TITLE
Get IntelliJ working for the new build

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scalafix#456]
In #454 we refactored the build to escape the wrath of `++` and sbt-doge. Now the entire build stays within the task graph, even for cross-builds. This new build is significantly easier to reason about and is less fragile, but it seems it's no longer possible to run the  tests or compile the project from IJ.

Here's how my "Modules" looks like

![screen shot 2017-11-25 at 09 34 36](https://user-images.githubusercontent.com/1408093/33228825-e70ac696-d1c3-11e7-87f4-4bbbdaeef7dd.png)

No matter if I reload, IJ still says build.sbt has changed and requires a refresh

![screen shot 2017-11-25 at 09 35 06](https://user-images.githubusercontent.com/1408093/33228832-fdc5a57c-d1c3-11e7-9f98-9f94a1aba588.png)

When trying to run the tests from IJ, I get a missing dependency error
![screen shot 2017-11-25 at 09 24 55](https://user-images.githubusercontent.com/1408093/33228835-0bfc28dc-d1c4-11e7-9a18-2906859116d8.png)
even if `difflib` is a dependency of `diff-sources` (but it's not a dependency of `diffJVM~1`
![screen shot 2017-11-25 at 09 36 41](https://user-images.githubusercontent.com/1408093/33228848-3464b140-d1c4-11e7-99b0-360f33313a1f.png)

It seems `BuildInfo` in src_managed of the `unit` project is neither picked up
![screen shot 2017-11-24 at 16 17 57](https://user-images.githubusercontent.com/1408093/33228852-48e6ace0-d1c4-11e7-86cc-45b173e2f1e2.png)
I was able to fix this by manually adding `src_managed` to "Sources` of `unit-sources` project
![screen shot 2017-11-25 at 09 38 30](https://user-images.githubusercontent.com/1408093/33228870-71ec9a0a-d1c4-11e7-9add-7e967d4399cf.png)

cc/ @jastice any idea what is happening?

**Comment by jastice** [comment]
I reproduced the problem, it seems to be that `sourceDirectories`  in sbt are configured to be a subdirectory of `.cross`:
```
[IJ]> unit/sourceDirectories
[info] * /Users/jast/playspace/scalafix/.cross/unit/src/main/scala-2.12
[info] * /Users/jast/playspace/scalafix/.cross/unit/src/main/scala
[info] * /Users/jast/playspace/scalafix/.cross/unit/src/main/java
[info] * /Users/jast/playspace/scalafix/scalafix-tests/unit/src/main/scala
[info] * /Users/jast/playspace/scalafix/.cross/unit/target/scala-2.12/src_managed/main
```
... while actually they are under the root. IntelliJ uses the `sourceDirectories` setting to mark directories appropriately. Not sure what you're doing here :)

**Comment by olafurpg** [comment]
Can you explain how you would expect sourceDirectories to look like?

```
[master] scalafix: show coreJVM/sourceDirectories
[info] * /Users/ollie/dev/scalafix/.cross/core/jvm/src/main/scala-2.12
[info] * /Users/ollie/dev/scalafix/.cross/core/jvm/src/main/scala
[info] * /Users/ollie/dev/scalafix/.cross/core/jvm/src/main/java
[info] * /Users/ollie/dev/scalafix/.cross/core/shared/src/main/scala-2.12
[info] * /Users/ollie/dev/scalafix/.cross/core/shared/src/main/scala
[info] * /Users/ollie/dev/scalafix/scalafix-core/shared/src/main/scala
[info] * /Users/ollie/dev/scalafix/scalafix-core/jvm/src/main/scala
[info] * /Users/ollie/dev/scalafix/.cross/core/jvm/target/scala-2.12/src_managed/main
[master] scalafix: show coreJVM/sourceDirectory
[info] /Users/ollie/dev/scalafix/.cross/core/jvm/src
```

We have this unorthodox setup to avoid `++`. Our build has a mix of 2.10 only, 2.11/2.12 cross-build and dotty only projects. Compile in some 2.11/2.12 cross-built projects have task depend on compile in dotty/2.10 only projects, which triggered intellij to fail update.

**Comment by jastice** [comment]
For IDEA to pick up the directory with `BuildInfo` as source dir, either you would have to configure sbt-buildinfo to generate the file to `<build root>/.cross/unit/target/scala-2.12/src_managed/main`, or add the directory that it is generated to the `sourceDirectories`, i.e. `<build root>/target/scala-2.12/src_managed/main`

**Comment by olafurpg** [comment]
Thanks for the input @jastice The build seems to import fine now for some reason, no idea what changed.
