### ISSUE TITLE
moar output on lint failures

### ISSUE THREAD

**Issue by fommil** [scalacenter/scalafix#460]
Some thoughts:

- the format should match what scalac outputs so that regex based file/line detection still works in a multitude of tools, c.f. https://github.com/ensime/emacs-sbt-mode/issues/130
- including the column information would be :100:  `pos.startColumn` is missing here https://github.com/scalacenter/scalafix/blob/0566b480109c449f84e0733f2d200806fd89752c/scalafix-core/shared/src/main/scala/org/langmeta/internal/ScalafixLangmetaHacks.scala#L15

**Comment by olafurpg** [comment]
can you give an example how the messages should be formatted? The current format tries to mimic scalac messages

**Comment by fommil** [comment]
Hmm,  something is missing or https://github.com/ensime/emacs-sbt-mode/blob/master/sbt-mode.el#L217-L226 would pick it up.

Some thoughts:

- we're expecting to see sbt's `[error]` or whatever at the beginning of the line
- maybe missing a colon *after* the line number?

**Comment by olafurpg** [comment]
> maybe missing a colon after the line number?

That could be fixed while we add the column number.

> we're expecting to see sbt's [error] or whatever at the beginning of the line

I'm on the fence of adding that gutter, I find it quite annoying.

**Comment by fommil** [comment]
I guess the gutter is another consequence of using a bootstrapped cli tool instead of going via sbt internals? In that case I think detecting sbt and mimicking would be good.

**Comment by olafurpg** [comment]
It should be possible to pass in the sbt logger instead of using System.out in the sbt plugin. The cli accepts a PrintStream.

**Comment by fommil** [comment]
don't cross the streams

**Comment by olafurpg** [comment]
I opened #467 to fix the missing column number, we can add the `[error/warn]` gutter in a separate PR if that is needed to parse the output from the sbt plugin.

**Comment by fommil** [comment]
did you create a ticket for the gutter?

The new output still isn't detected with the emacs scala compiler rules

```
core/src/main/scala/org/ensime/core/javac/JavaCompletionsAtPoint.scala:333:7: error: [NoInfer.any2stringadd] Inferred any2stringadd
      t.asElement.getSimpleName + (t.getTypeArguments.asScala match {
      ^
```

**Comment by olafurpg** [comment]
It wasn't clean if the gutter was necessary, let me reopen this ticket and fix it quickly

**Comment by olafurpg** [comment]
Would it be possible to update the emacs scala compiler rules to ignore a missing `[error]` gutter? scalafix now reports errors using the same format as scalac

**Comment by fommil** [comment]
@olafurpg and vim, and sublime, and atom, and vscode, and jedit, and, and, and, and...

This is not really about Emacs per se but about retaining backwards compatibility with the multitude of tooling out there that is already dependent on a stable output format.

**Comment by olafurpg** [comment]
The output format of scalafix is identical to the format from scalac, which is arguably more stable than from sbt. sbt's output can be modified by sbt plugins like in https://github.com/Duhemm/sbt-errors-summary. With dotty the output changes as well https://scastie.scala-lang.org/OGBOYH82RS6GgkIrmqKbuA

```scala
-- [E007] Type Mismatch Error: /tmp/scastie1950099040170226781/src/main/scala/main.scala:2:17 
2 |    val x: Int = ""
  |                 ^^
  |                 found:    String("")
  |                 required: Int
  |                 
```

Sure we can adapt the scalafix output but I urge you to consider making it easier to update the regexp in the emacs/vim/atom integrations. I don't use those integrations so I don't even know how to validate if a fix is solid or not. This will continue to be a struggle.

**Comment by fommil** [comment]
I am not involved with any of the editors other than Emacs, so you'll have to find out who is managing them and ask their maintainers to change their parsers. I could change the `sbt-mode` detector (which is a specific detector to the sbt build tool, not scala) but it will probably introduce lots of new false positives and probably also slow down sbt output because we won't get early regex misses on arbitrary user output.

Surely there is a way to make output in sbt go through their logger such that the gutter is added?

**Comment by olafurpg** [comment]
> Surely there is a way to make output in sbt go through their logger such that the gutter is added?

Yes, this should be much easier in sbt 1.0 where we don't need to fiddle with classloaders. I think that would be the best solution to fix this problem without adding a special "sbt mode" to scalafix. sbt 0.13 will then have to live without the `[error]` gutter. I opened #491 to track this, I suppose we can close this ticket then?

**Comment by fommil** [comment]
I don't care about 0.13 anymore :stuck_out_tongue:
