### ISSUE TITLE
configureForConfigurations is a bit clunky for large projects

### ISSUE THREAD

**Issue by fommil** [scalacenter/scalafix#461]
It seems to assume that every `Project` has all the configurations.

It would be easier to use if there was a `scalafixSettings` method that could be called `inConfig`, which could be part of the standard boilerplate when adding a test config to a project.

**Comment by olafurpg** [comment]
Did you try ?

```scala
lazy val projectA = project.settings(scalafixConfigure(Test))
lazy val projectB = project.settings(scalafixConfigure(Compile))
```

`scalafixConfigure` returns a list of settings
```
    def scalafixConfigure(configs: Configuration*): Seq[Setting[_]]
```

it works this way instead of through `inConfig()` because I wanted `scalafix` to have the following behavior

- unscoped `scalafix` runs on all enabled  configs
- scoped `scalafix:config` runs only for `config`

I wasn't able to get that working with `inConfig`.

**Comment by fommil** [comment]
In fact... I wonder if it's possible to create a `addCommandAlias` that knows about all non-hidden configurations in a build. That would allow you to easily ship the `fix` command alias as stock.

**Comment by fommil** [comment]
some more details... it's pretty normal in a build to have something like this

```
implicit class IntegrationTestOps(p: Project) {
    def enableIntegrationTests: Project =
      p.configs(It)
        .settings(
          inConfig(It)(
            Defaults.testSettings ++ sensibleTestSettings ++ Seq(
              javaOptions ++= Seq("-Xms1400m", "-Xmx1400m")
            )
          )
        )
  }
```

and the developers can put everything in here that integration tests should enable. There are similar methods for other test configs, and it is in here that the scalafix settings would be applied.

This is all, of course, a workaround to the fact that nobady cares about https://github.com/sbt/sbt/issues/2534, except me.
