### ISSUE TITLE
drop-in feature

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scalafix#462]
@olafurpg suggested adding a new mode for scalafix to drop in existing code base. The idea is to selectively enable scalafix for the new code.

The implementation is powered by a diff algorithm. Version control software can easily produce a diff given a start revision. For example in git: `git diff HEAD..90f1e7b4b764fb80b6692be6284ba28e00eeff26`. From this unified diff, we can find a list of ranges where we can enable scalafix.

**Comment by MasseGuillaume** [comment]
It looks like java difflib throws out a lot of useful information.

This is the signature of the function:
```public static Patch<String> parseUnifiedDiff(List<String> diff)```
https://github.com/KengoTODA/java-diff-utils/blob/master/src/main/java/difflib/DiffUtils.java#L170

it does not handle multiple files. and throws away the filenames.

Since we need to support both Scala and Scala.js. I think it makes sense to implement our own parser.

**Comment by olafurpg** [comment]
Here is a WIP unified diff parser I was planning to use for `scalafmt --diff` https://github.com/olafurpg/scalafmt/blob/d0f50e6183e9e3de5f3479512e6bef79c746c214/core/src/main/scala/org/scalafmt/diff/FileDiff.scala

**Comment by olafurpg** [comment]
Fixed in #472
