### ISSUE TITLE
publishSigned no longer works

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scalafix#468]
```
sbt diffJVM/publishSigned
... 
[error] (diffJVM/*:publishSigned) java.io.IOException: PUT operation to URL https://oss.sonatype.org/content/repositories/snapshots/ch/epfl/scala/scalafix-diff_2.12/0.5.6/scalafix-diff_2.12-0.5.6-sources.jar failed with status code 400: Bad Request
```

Can you reproduce @MasseGuillaume ? Any chance this is related to the build refactoring?

**Comment by olafurpg** [comment]
Do you have credentials to publish artifacts under ch.epfl.scala with your sonatype account? If so, you can run it as publishSigned and sign with your personal pgp key.

**Comment by MasseGuillaume** [comment]
I found the problem: https://travis-ci.org/scalacenter/scalafix/builds/310055243#L3104-L3105

We are not getting SONATYPE_USERNAME and SONATYPE_PASSWORD from the env variable anymore.
https://github.com/scalacenter/scalafix/pull/470/files#diff-fdc3abdfd754eeb24090dbd90aeec2ceR414

**Comment by olafurpg** [comment]
Are you sure? I can reproduce this problem locally so I doubt it's travis related

**Comment by fommil** [comment]
looks like you're publishing final versions to the snapshot repo, are you sure your repo-switching logic is correct?

BTW, this is how I get creds in my builds https://gitlab.com/fommil/sbt-sensible/blob/master/src/main/scala/SonatypePlugin.scala#L101-114

**Comment by MasseGuillaume** [comment]
the scmInfo is empty also for some reason.

**Comment by MasseGuillaume** [comment]
I'm running a git bisect to see what happened.

**Comment by olafurpg** [comment]
I think publishSigned stopped after the build refactoring

**Comment by MasseGuillaume** [comment]
okay I figured it out.

the globalSetting from https://github.com/scalacenter/scalafix/blob/b9398ec880e7817e3a5f9358a2192efd99b6e6bf/project/ScalafixBuild.scala#L163

are not applied for some reason. I moved everything back to the projectSettings and everything works fine now.

**Comment by olafurpg** [comment]
What happens if you move those to `buildSettings`?
