### ISSUE TITLE
Get SemanticTest running in intellij 

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scalafix#49]
It should be possible to replace the `exposePaths` hack in build.sbt with 
https://github.com/sbt/sbt-buildinfo

**Comment by olafurpg** [comment]
A nice side effect of the tests cleanup in #165 is that we no longer use the hacky `exposePaths` trick, build info generates all the necessary file path strings. This means the scalafix-testskit tests should run cleanly in IntelliJ with full support for breakpoints and everything. NOTE however, you need to run `sbt test:compile` via the terminal first to trigger the BuildInfo code generation.

I tried to run [SemanticTests](https://github.com/scalacenter/scalafix/blob/db6152304aaef19c4a8ba4fc77b732264bf52fec/scalafix-tests/unit/src/test/scala/scalafix/tests/SemanticTests.scala) but I get a cryptic "Error:Module 'unit' production: java.lang.NullPointerException".  I have little experience compiling projects from IntelliJ. @ShaneDelmore Could you maybe checkout master and try running SemanticTests.scala from intellij?

**Comment by olafurpg** [comment]
I just successfully ran SemanticTests via intellij

![screen shot 2017-08-16 at 10 31 36](https://user-images.githubusercontent.com/1408093/29354536-2420d070-826e-11e7-91f8-fbe1d50c4467.png)

I had to specify the output path in the Project Structure but otherwise I didn't need any custom setup. You still need to run `sbt test:compile` once to generate the BuildInfo objects.

**Comment by ShaneDelmore** [comment]
@olafurpg I see I missed your message to test this out previously.  Sorry about that but thanks for verifying it works.

**Comment by olafurpg** [comment]
No worries @ShaneDelmore ! I miss messages in my inbox all the time 😅
