### ISSUE TITLE
Configurable --output-format sbt/scalac/json/html/emacs/...

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scalafix#491]
See #460. Currently, the output from sbt-scalafix does not include a [error] gutter which is used to detect messages for editor integrations with emacs/vim/atom/...

In sbt 0.13 we classload scalafix, which makes it annoying to use the proper sbt logger to report info/error/warning. In sbt 1.0 we should however not need classloading so it should be easier. A rewrite of sbt-scalafix inspired by https://github.com/scalameta/scalafmt/pull/1085 might actually be in order.

**Comment by vovapolu** [comment]
:smirk: looks like a work for me

**Comment by olafurpg** [comment]
Relevant: http://rubocop.readthedocs.io/en/latest/formatters/ It would be nice if scalafix had configurable formatters. The `[error]` gutter could be part of that. Another option could  be to emit json so tools don't need regexes that break on scalafix upgrades.

**Comment by fommil** [comment]
emitting json would be great, we need to get scalac to do that also. But:

1. we still need to support the old formats, so the regexes don't go away. It's https://xkcd.com/927/
2. this is a lot of work, multiplied by the number of editors. So support will be very slow and very gradual.

**Comment by olafurpg** [comment]
With configurable formatting we can also be compatible with existing tools, for example rubocop has `--format emacs` http://rubocop.readthedocs.io/en/latest/formatters/#emacs-style-formatter

**Comment by fommil** [comment]
All I need is `[info] ` at the start of the lines... anything else is overengineering at this stage.

**Comment by olafurpg** [comment]
The `[error]` gutter is already implemented and merged as part of https://github.com/scalacenter/scalafix/pull/587 It's not released yet.

**Comment by fommil** [comment]
sweeet

**Comment by olafurpg** [comment]
That PR doesn't implement any other format, but adding new --format is a matter of adding a new `case object` and handler for it.
