### ISSUE TITLE
Disable reports errors on symbol signatures

### ISSUE THREAD

**Issue by vovapolu** [scalacenter/scalafix#493]
I want to disable usage of some class `Foo`, so I write 
```
rule = Disable
Disable.symbols = [mypackage.Tests.Foo]
```
and corresponding test
```
package mypackage

object Tests {
  class Foo
  class Bar extends Foo // assert: Disable.Foo
}
```

But that test throws a strange error 
```
_root_.mypackage.Tests.Foo#`<init>`()V.:1: error: [Disable.Foo] Foo is disabled
(): Foo
    ^
```
that's impossible to catch.

**Comment by olafurpg** [comment]
Thanks for reporting! This is indeed a bug, it seems `Disable` runs on resolved names in
- the source file
- inferred synthetics
- symbol signatures (https://github.com/scalacenter/scalafix/blob/f095438f25a050bebf635415f92f5f7a54cdbd26/scalafix-core/shared/src/main/scala/scalafix/internal/util/EagerInMemorySemanticdbIndex.scala#L27)

It should not run on symbol signatures.
 This means we should update this line here https://github.com/scalacenter/scalafix/blob/b48d7f0c57c310ff8c86e77f11ed4fe05432ad02/scalafix-core/shared/src/main/scala/scalafix/internal/rule/Disable.scala#L34
to only visit `.names` and `.synthetics` of each document (skipping `.symbols.foreach(_.denotation...)`)
