### ISSUE TITLE
scalafix-cli should support `project.exclude/includeFilters`

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scalafix#498]
Similar to scalafix http://scalameta.org/scalafmt/#project 

This complements #496 since not everyone use sbt-scalafix.

This also complements semanticdb-scalac `-P:semanticdb:exclude/include` https://github.com/scalameta/scalameta/releases/tag/v2.1.0

**Comment by mlachkar** [comment]
Seems to have been implemented in https://github.com/scalacenter/scalafix/commit/f4f7c6ffd3c8f9377dd9229a10a4cb4bb3c3f33b
