### ISSUE TITLE
Move metaconfig extensions upstream

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scalafix#499]
https://github.com/scalacenter/scalafix/blob/a59dee66da747966eab318dd69e73bebb6fd0d76/scalafix-core/src/main/scala/scalafix/internal/config/MetaconfigPendingUpstream.scala

**Comment by olafurpg** [comment]
The TODO was removed in #836 It's not clear how to upstream all of those features since many of them are scalafix specific.
