### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scalafix#504]
Currently, scalafix has no benchmarks to measure performance implications of the design we use to execute rules. The main overhead comes from compilation so it hasn't really been a big concern. However, in #503 we may be introducing a decent amount of overhead to implement `// scalafix:off` for rewrites. I have ideas to optimize the implementation in #503, but I don't want to pre-maturely optimize and I don't want to optimize the code without measuring first the speedups.

**Comment by MasseGuillaume** [comment]
It would be nice to provide this for testkit users such that they can test the performance of their rewrites.

**Comment by olafurpg** [comment]
Seems we havn't had the need for benchmarks so far. We can pick this up again if users report performance issues.
