### ISSUE TITLE
DiffAssertions should show Hunk header

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scalafix#505]
we do `.drop(3)` to remove the Hunk header.

```
=======
=> Diff
=======
--- original
+++ revised
@@ -9,3 +9,2 @@
∙
-
```

vs

```
=======
=> Diff
=======
∙
-
```

**Comment by olafurpg** [comment]
I agree this is a good idea 👍

**Comment by olafurpg** [comment]
Fixed a while ago https://github.com/scalacenter/scalafix/blob/dcaad372cef100e76efd4d106b15f3a3ee2740c3/scalafix-testkit/src/main/scala/scalafix/testkit/DiffAssertions.scala#L32
