### ISSUE TITLE
Testkit pick up deleted test

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scalafix#510]
Steps:

* run testkit, tests pass
* add input + output
* run testkit
* delete input + output (FooBar)

Result:

tests fails

```
 java.lang.RuntimeException: Missing expected output file for test scala/test/FooBar.scala
```

Expected:

tests pass

Workarround:

`rm target/scala-2.12/classes/META-INF/semanticdb/scala/test/FooBar.semanticdb`

**Comment by olafurpg** [comment]
The semanticdb-scalac plugin should remove semanticdb files for removed files but that could have a bug. An alternative workaround in testkit would be to check if the input file is removed then ignore "Missing expected output file for test scala/test/FooBar.scala" errors

**Comment by olafurpg** [comment]
This is fixed in the latest testkit. Previously, testkit ran tests based on existing `*.semanticdb` files and mapped those to `*.scala` files. Now, testkit instead discovers tests from `*.scala` files and maps those to `*.semanticdb` files.
