### ISSUE TITLE
Document that Dotty* rules may produce invalid Scala 2.x code

### ISSUE THREAD

**Issue by hepin1989** [scalacenter/scalafix#519]
```
object MatchList extends App {
  // #snip
  def processItems(items: List[String]): Unit = {
    items match {
      case List("apple", "ibm")         ⇒ println("Apples and IBMs")
      case List("red", "blue", "white") ⇒ println("Stars and Stripes...")
      case List("red", "blue", _*)      ⇒ println("colors red, blue,... ")
      case List("apple", "orange", otherFruits @ _*) ⇒
        println("apples, oranges, and " + otherFruits)
    }
  }
  // #snip
}
```

is rewrite to 
```
object MatchList extends App {
  // #snip
  def processItems(items: List[String]): Unit = {
    items match {
      case List("apple", "ibm")         ⇒ println("Apples and IBMs")
      case List("red", "blue", "white") ⇒ println("Stars and Stripes...")
      case List("red", "blue", _*)      ⇒ println("colors red, blue,... ")
      case List("apple", "orange", otherFruits :  _*) ⇒
        println("apples, oranges, and " + otherFruits)
    }
  }
  // #snip
}
```

with scala 2.12.4

which is not compile-able then

**Comment by marcelocenerine** [comment]
[DottyVarArgPattern](https://scalacenter.github.io/scalafix/docs/rules/DottyVarArgPattern) is the rule performing this rewrite. This is intended for Dotty migration afaik. Try not to specify this rule in your config

**Comment by olafurpg** [comment]
Correct, this rewrite is working as intended. It's a dotty specific rewrite which produces code which does not compile with Scala 2.x. I've updated the title of this issue to clarify the docs.

**Comment by hepin1989** [comment]
@olafurpg @marcelocenerine Thank you for that information.

**Comment by olafurpg** [comment]
Thanks for reporting! The dotty rules have been moved out of the scalafix repo so that they can evolve at a different pace than Scalafix APIs.
