### ISSUE TITLE
exclude covariant and contravariant types

### ISSUE THREAD

**Issue by fommil** [scalacenter/scalafix#524]
As per [Type Variance](https://leanpub.com/fpmortals/read#leanpub-auto-scalaz-data-types), the scalaz community has decided that covariance and contravariance is not worth the effort and would rather stick to invariant type parameters.

It would be good to be able to opt-in to enforce this rule. The explanation can link to my book to avoid repetition.

**Comment by vovapolu** [comment]
```
DisableSyntax.noCovariantTypes = true
DisableSyntax.noContravariantTypes = true
```

**Comment by fommil** [comment]
Very nice!

**Comment by fommil** [comment]
It would be good if the error message referred to the online chapter of my book, explaining why it is banned.

**Comment by olafurpg** [comment]
A lint message can include a detailed explanation under `lint.explain=true` https://github.com/scalacenter/scalafix/blob/325ad576a7c4c5e8a5286195a1a83d091c77ac2d/scalafix-core/shared/src/main/scala/scalafix/lint/LintCategory.scala#L13
