### ISSUE TITLE
ban use of val in abstract things

### ISSUE THREAD

**Issue by fommil** [scalacenter/scalafix#525]
https://github.com/wartremover/wartremover/issues/397

Far too many initialisation bugs. Even in OOP, `val` is an implementation detail, and the interface should use `def`.

**Comment by vovapolu** [comment]
Hmm, can you provide some examples of "abstract things" except `trait`s?

**Comment by fommil** [comment]
`trait` and `abstract class`

**Comment by vovapolu** [comment]
just `val` within `trait`s and `abstract class`es?
