### ISSUE TITLE
Wartremover migration 

### ISSUE THREAD

**Issue by vovapolu** [scalacenter/scalafix#529]
Migrate all the [wartremover warts](http://www.wartremover.org/doc/warts.html). https://github.com/wartremover/wartremover/tree/master/core/src/test/scala/wartremover/warts

This ticket should also summarise how to use the migrated version.

`Unsafe` warts

- [x] Any (`NoInfer.symbols = ["scala.Any"]`)
- [x] AsInstanceOf (`Disable.symbols = ["scala.Any.asInstanceOf"]`)
- [x] EitherProjectionPartial (`Disable.symbols = ["scala.util.Either.LeftProjection.get", "scala.util.Either.RightProjection.get"]`)
- [x] IsInstanceOf (`Disable.symbols = ["scala.Any.isInstanceOf"]`)
- [ ] TraversableOps (huge list of all overridden methods for now) 
- [ ] NonUnitStatements (https://github.com/scalacenter/scalafix/pull/554) (Blocked by absence of `Term.tpe`)
- [x] Null (`DisableSyntax.keywords = [null]`)
- [x] OptionPartial (`Disable.symbols = ["scala.Option.get", "scala.Some.get", "scala.None.get"]`)
- [x] Product (`NoInfer.symbols = ["scala.Product"]`)
- [x] Return (`DisableSyntax.keywords = [return]`)
- [x] Serializable (`NoInfer.symbols = ["java.io.Serializable"]`)
- [x] StringPlusAny (`NoInfer.symbols = ["scala.Predef.any2stringadd"]`)
- [x] Throw (`DisableSyntax.keywords = [throw]`)
- [x] TryPartial (`Disable.symbols = ["scala.util.Try.get", "scala.util.Failure.get", "scala.util.Success.get"]`)
- [x] Var (`DisableSyntax.keywords = [var]`)

and others

- [x] AnyVal (`NoInfer.symbols = ["scala.AnyVal"]`)
- [ ] ArrayEquals (Blocked by absence of `Term.tpe`)
- [x] DefaultArguments (`DisableSyntax.noDefaultArgs = true`)
- [x] Enumeration (`Disable.symbols = ["scala.Enumeration"]`)
- [x] Equals (`Disable.symbols = ["java.lang.Object.equals", "java.lang.Object#`==`", "java.lang.Object.eq", "java.lang.Object.ne"]`)
- [ ] ExplicitImplicitTypes (`ExplicitResultTypes` rewrites such cases, we can add option to limit ourselves only to `impilicit`s)
- [x] FinalCaseClass (
(note that scalaz 7.3 has a valid usecase for this... worth special casing. See use in `scalaz.ISet.Tip`) ( `rules = [MissingFinal]`)
- [x] FinalVal (`DisableSyntax.noFinalVal = true`)
- [ ] ForbidInference (no docs on http://www.wartremover.org/doc/warts.html)
- [x] ImplicitConversion (`DisableSyntax.noImplicitConversion = true`)
- [ ] ImplicitParameter (It has quite a lot of specific cases, probably connected with https://github.com/scalacenter/scalafix/issues/526)
- [ ] JavaConversions (another huge list or not?) (Blocked by absence of `Term.tpe`)
- [x] JavaSerializable (`NoInfer.symbols = ["java.io.Serializable"]`)
- [x] LeakingSealed (`rules = [MissingFinal]`)
- [ ] MutableDataStructures (one more huge list? `Disable.symbols = [""scala.collection.mutable"]`)
- [ ] Nothing  (`NoInfer.symbols = ["scala.Nothing"]`, but this also blocks things like `Left("error")`, cause it's actually `Left[String, Nothing]("error")`)
- [x] Option2Iterable (`NoInfer.symbols = ["scala.Option.option2Iterable"]`)	
- [ ] Overloading (arguable rule, need to discuss with @olafurpg or @fommil)
- [ ] PublicInference
- [ ] Recursion
- [x] ToString  (`Disable.symbols = ["java.lang.Object.toString"]`)
- [x] While (`DisableSyntax.keywords = [while]`)

See my [blog post](https://vovapolu.github.io/scalafix/2018/02/03/scalafix-wartremover.html) and [example repo](https://github.com/vovapolu/ScalafixWartremov) for this task.

**Comment by gabro** [comment]
This is really exciting @vovapolu, I've been wanting something like this since forever :)! Can you maybe link to the existing issues @fommil has already opened?

**Comment by fommil** [comment]
@gabro this is about migration, new warts get their own tickets ;-)

I don't have label permissions, so if somebody could add a "Sponsorship" label to all of these tickets and PRs that'd be awesome.

**Comment by olafurpg** [comment]
I have sent you @fommil and @vovapolu a collaborator invitation so you can label and assign issues!

**Comment by gabro** [comment]
> this is about migration, new warts get their own tickets

I think the list in the OP still overkaps with the ones you opened, like 

- Ban guards in pattern matches over sealed traits. needs more investigating
- Ban val in traits.
- Exclude covariant and contravariant types

**Comment by fommil** [comment]
oh, yeah the original list was a mission statement. Now drilling down. It's because github issues doesn't do "convert to epic".

**Comment by gabro** [comment]
Yeah, GitHub could really use something like that. (At work we work around it with browser extensions and a couple of bots).

Thanks for taking care of this!

**Comment by fommil** [comment]
@gabro oh, I just read this ticket and I see what you mean :smile: ok this was supposed to be a list of *existing* wartremover warts, not the new ones. I'll update it (which will be very confusing for everybody reading our comments)

**Comment by dwijnand** [comment]
> Yeah, GitHub could really use something like that.

I think GitHub projects map this, if you're happy to call this sponsored effort a "project".

**Comment by fommil** [comment]
@dwijnand we did that in ensime and nobody knew where to look. It's a great feature, but it's just not visible enough.

**Comment by MasseGuillaume** [comment]
May I also suggest an Wartremover plugin? It's basically a sbt plugins that reads Wartremover sbt setting and create a .scalafix.conf

**Comment by fommil** [comment]
@MasseGuillaume nice idea! It's not something I think we'll have time to include in the sponsorship, but maybe deserves a ticket for anybody who wants it that badly.

**Comment by olafurpg** [comment]
Why do you say that JavaConversions and TraversableOps are blocked by Term.tpe? Synthetics contains implicit conversions and head/tail/init methods can be detected with symbols.

Also, what is the difference between `DiscardedValues` and scalac -Ywarn-value-discard?

```
-Ywarn-value-discard     -- Warn when non-Unit expression results are unused
```

**Comment by vovapolu** [comment]
>Why do you say that JavaConversions and TraversableOps are blocked by Term.tpe?

Hmm, yeah you're right. I was just thinking about more clever way to block them, e.g. `Seq.head` and `List.head` are different things, so we could detect the type of left expression, the name of method and block them without a huge list of all overridden head/tail/init.

**Comment by olafurpg** [comment]
We recently added `Denotation.overrides` to semanticdb, which allows you to find the symbol of the overridden method. It's quite primitive for now, but these capabilities will get more powerful in the coming months.

**Comment by fommil** [comment]
I'm happy at this point that the important warts have been migrated, closing! We can create separete (unsponsored) tickets for the remainder if anybody wants to contribute them.
