### ISSUE TITLE
Security vulnerability for rules over HTTP

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scalafix#532]
We should not allow rules from the HTTP protocol (HTTPS is ok). The only counterexample would be from a trusted network, for example, a company intranet. We can add a --unsecure and add a warning.

**Comment by olafurpg** [comment]
Sure, we can remove "http" from here https://github.com/scalacenter/scalafix/blob/8263bb3ee9aa2f86285a35f08c550982f894b556/scalafix-reflect/src/main/scala/scalafix/internal/reflect/ScalafixCompilerDecoder.scala#L35

**Comment by olafurpg** [comment]
Let's leave it up to the user to decide whether to compile rules from source via http URLs or not. There may be valid reasons to use http URLs, for example in a company intranet as you say.
