### ISSUE TITLE
RemoveUnusedImports with non-binpacked selectors can produce trailing comma syntax errors

### ISSUE THREAD

**Issue by ches** [scalacenter/scalafix#535]
Multi-line imports (produced by default scalafmt configuration when max columns are exceeded) can result in scalafix changes like this when unused imports are removed:

```diff
import org.example.dto.{
   Allocation,
   ExperimentAllocation,
-  ExperimentAllocationReport
+
 }
```

Obviously, this won't compile (and the remnant newline is undesirable to boot).

And another corner case, the last remaining import in braces:

```diff
-import org.example.some.long.line.{
-  MSSQLControlExperimentRepository,
+import org.example.some.long.line.
+
   MSSQLRepository
-}
+
```

**Comment by ches** [comment]
Sorry, I see the latter one is a documented caveat. It does compile, so the former one is the severe case.

**Comment by olafurpg** [comment]
Thank you for reporting! I am able to reproduce, I will take a look.

**Comment by olafurpg** [comment]
Pending fix in https://github.com/scalacenter/scalafix/pull/537

**Comment by ches** [comment]
Thanks for the quick fix!
