### ISSUE TITLE
DisableUnless docs

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scalafix#541]
The DisableUnless rule has no docs. @vovapolu Can you please add a section explaining how it works and which configuration options are supported?

See 

-
 https://github.com/scalacenter/scalafix/blob/master/website/src/main/resources/microsite/data/rules.yml
- https://github.com/scalacenter/scalafix/tree/master/website/src/main/tut/docs/rules

**Comment by vovapolu** [comment]
I can also add https://vovapolu.github.io/scalafix/2017/12/14/scalafix-fp-alpha.html :)
