### ISSUE TITLE
Make val field in implicit class private

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scalafix#542]
I just observed that the `val` field in an implicit class is accesible as an extension method
```scala
scala> implicit class XtensionString(val str: String) extends AnyVal {
     |   def doubled = str + str
     | }
defined class XtensionString

scala> "message".str
res0: String = message
```
A workaround to prevent this is to make the field private
```scala
scala> implicit class XtensionString(private val str: String) extends AnyVal
```
It would be nice to have a scalafix rule to automatically fix this.

Context: https://gitter.im/scala/contributors?at=5a4e57685355812e57502b5b

**Comment by LeonardMeyer** [comment]
I took a stab at this. Can't really test for now because of #547 but will do.

I do have one question though : Why does `Ctor.Primary` of ScalaMeta has a `List[List[Term.Param]]` ? Why two levels ?

**Comment by olafurpg** [comment]
Cool @LeonardMeyer ! I will try to take a look at #547 in the coming week.

Primary constructors can be curried which are represented as `List[List[Term.Param]]`
```scala

@ show(q"class A(a: Int)(b: String)".ctor)
Ctor.Primary(
  List(),
  _,
  List(
    List(Term.Param(List(), Term.Name("a"), Some(Type.Name("Int")), None)),
    List(Term.Param(List(), Term.Name("b"), Some(Type.Name("String")), None))
  )
)
```

**Comment by LeonardMeyer** [comment]
I literally realized this right before coming back here 😄 By the way, even private won't help with something like this : 

```
  class A(val str: String) {
    def doubled: String = str + str
  }

  implicit class B(override val str: String) extends A(str)

  "test".str  //visible
```

**Comment by LeonardMeyer** [comment]
I have a question but nobody seemed active on Gitter so I'll repeat it here : can someone explain to me how tests are configured ? I understand comments play a role in it but I can't figure it out. All I saw was [this](https://scalacenter.github.io/scalafix/docs/rule-authors/setup#scalafix-testkit) but it's pretty vague about configuration...
