### ISSUE TITLE
More flexible tree rewriting rules?

### ISSUE THREAD

**Issue by erik-stripe** [scalacenter/scalafix#550]
Hi folks,

Apologies if I misunderstood the documentation/examples, but I didn't see an obvious way to pattern match trees and then produce new (potentially unrelated) trees using subtrees that were bound during the match.

Here's a fairly concrete example:

```scala
// before
_root_.scala.Predef.doubleWrapper($x).min($y)

// after
_root_.java.lang.Math.min($x, $y)
```

Is there a preexisting rule that does this? If not, do you think it's possible to define a rule like this?

**Comment by gabro** [comment]
In the specific case, I would do something like

```scala
val richDoubleMin = SymbolMatcher.normalized(Symbol("_root_.scala.runtime.RichDouble.min."))
ctx.tree.collect {
  case t @ Term.ApplyInfix(lhs, richDoubleMin(_), targs, List(rhs)) =>
    ctx.replaceTree(t,  q"_root_.java.lang.Math.min($lhs, $rhs)".syntax)
  }.asPatch
}
```

This will rewrite

```scala
1.2 min 2.2
```

to

```scala
_root_.java.lang.Math.min(1.2, 2.2)
```

In the above example, the quasi-quote is re-using the matched sub-trees. Is that what you were looking for?

**Comment by erik-stripe** [comment]
Yes, I think I can use that to write the rules I want.

Thanks for your help!

**Comment by gabro** [comment]
Cool. I'm going to close this, if you have have further problems we can re-open it.

**Comment by olafurpg** [comment]
@erik-stripe tree rewriting facilities are still quite primitive, beware that `.syntax` on synthetic trees (quasiquotes) will not preserve comments or formatting in the spliced tree nodes. There is no "easy way" to implement a robust rewrite yet, the token api forces you on a much lower level 

* replace `min` with `,`
* add `Math.min(` to left argument
* add `)` to right argument

I'm aiming to work on https://github.com/scalacenter/scalafix/issues/502 in the coming few weeks which should hopefully make tree rewriting more robust.
