### ISSUE TITLE
Invalid rewrite for ProcedureSyntax

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scalafix#557]
input:

```scala
trait FSM[S, D] extends Actor with Listeners with ActorLogging {
  implicit final def total2pf(transitionHandler: (S, S) ⇒ Unit): TransitionHandler =
    new TransitionHandler {
      def isDefinedAt(in: (S, S)) = true
      def apply(in: (S, S)) { transitionHandler(in._1, in._2) }
    }
}
```

https://github.com/akka/akka/blob/f890bc6abf8f2911147b2523f68b9956d1c7b84a/akka-actor/src/main/scala/akka/actor/FSM.scala#L494

result:

```scala
-      def apply(in: (S, S)) { transitionHandler(in._1, in._2) }
+      def apply(in: (S, S): Unit =) { transitionHandler(in._1, in._2) }
```

**Comment by olafurpg** [comment]
Nice catch! ProcedureSyntax was the first scalafix rule, and may be using slightly outdated tricks to find tokens to edit, etc.

**Comment by gabro** [comment]
I also expect this to be fairly easy to fix, so I'm adding the `good first issue` label just in case.

**Comment by olafurpg** [comment]
Nice idea @gabro ! A good place to start looking into this is to reproduce the bug with a unit test here https://github.com/scalacenter/scalafix/blob/00199145261b958fb12cf256773c2ed08f336359/scalafix-tests/input/src/main/scala/test/ProcedureSyntax.scala#L19

The expected output should be here
