### ISSUE TITLE
Feedback from Sam Halliday

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scalafix#559]
Before I forget, feedback from @fommil on gitter https://gitter.im/scalacenter/scalafix?at=5a60da3bce68c3bc74d3d282

Some of these are duplicates to existing issues 

- [ ] ability to ignore generated (expanded macros) code, sbt-scalafix
- [ ] ignore imports for Disable and DisableUnless, cc/ @vovapolu 
- [x] better config format for DisableUnless
- [x] canonical way to add scalafix to alternative test configs
- [ ] output in sbt should look exactly like scalac output, including `[error]` gutter
- [ ] support exclude / include format in symbol lists (disable and disableunless). e.g. exclude "scala" (and its children) but then allow "scala.Int"

**Comment by fommil** [comment]
final two are

- https://github.com/scalacenter/scalafix/issues/461
- https://github.com/scalacenter/scalafix/issues/491

**Comment by MasseGuillaume** [comment]
I renamed to Feedback from Sam Halliday to avoid confusion with the Single Abstract Mehod (SAM) rule :P.

**Comment by fommil** [comment]
I broke everything out into separate tickets to track what is and isn't part of a potential final 2 weeks of sponsorship.
