### ISSUE TITLE
Make ADT traits extend Product With Serializable

### ISSUE THREAD

**Issue by LeonardMeyer** [scalacenter/scalafix#560]
As requested on [gitter](https://gitter.im/scalacenter/scalafix?at=5a60d9c4ce68c3bc74d3cf57) and as explained [here](https://stackoverflow.com/questions/36525804/scala-case-class-extending-product-with-serializable). 

So basically all :
```scala
sealed trait A
```
should go to :
```scala
sealed trait A extends Product with Serializable
```

There's several way to go about this :

1. Do it regardless of the number of children ? 
2. Unsealed trait too ?
3. Linting or rewriting ?

IMO unsealed is a bad idea for several reason : Firstly because ADTs are (I hope) rarely split across several files. Secondly, while I'm not that familiar with scalafix API, I guess this will complicate things for a questionable added value.

**Comment by olafurpg** [comment]
Thanks for reporting! This is a good candidate for a custom rule outside of the Scalafix repo. In the following weeks, we will be working on moving rules outside of the core repo and make sure that running external rules has the same nice user experience as running builtin rules.
