### ISSUE TITLE
Stop automatic installation of semanticdb-scalac

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scalafix#589]
Currently, sbt-scalafix automatically `addCompilerPlugin(semanticdb-scalac)` and `scalacOptions += "-Yrangepo"`. This automatic setup does not work for builds that use `libraryDependencies :=` or `scalacOptions :=`.  I propose we stop with the automatic installation and recommend users to manually setup the compiler plugin
```scala
addCompilerPlugin("org.scalameta" % "semanticdb-scalac" % scalafixScalametaVersion.value  % cross CrossVersion.full)
scalacOptions += "-Yrangepos"
```
Alternatively, it's possible to configure this step with the `scalafixEnable` command for a single sbt session.

**Comment by MasseGuillaume** [comment]
@olafurpg why we don't reuse the logic of `scalafixEnable`? If `semanticdb-scalac` don't add it, etc.

**Comment by olafurpg** [comment]
We currently enable the settings from `scalafixEnable` in ScalafixPlugin. The problem is that many build.sbt override the settings defined by ScalafixPlugin, making the setup break. The `scalafixEnable` command bypasses this problem because you have to run it manually in the sbt shell after the build is loaded.
