### ISSUE TITLE
SemanticdbIndex.denotation(Symbol) is incorrect for Symbol.Local

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scalafix#596]
`EagerInMemorySemanticdbIndex` collects all the symbols independently from the input. However, the symbol is only valid for a given input.

**Comment by olafurpg** [comment]
Pending fix in https://github.com/scalameta/scalameta/pull/1252

**Comment by xeno-by** [comment]
Another attempt at fixing the issue: https://github.com/scalameta/scalameta/pull/1253.
