### ISSUE TITLE
Disable symbol should consider the OOP hierarchy

### ISSUE THREAD

**Issue by fommil** [scalacenter/scalafix#597]
If I disable `scala.Option.get`, I would expect it to ban uses of `scala.None.get`, although I may want an include rule to allow `scala.Some.get`.

Similarly, I would expect that banning `java.lang.Object.equals` would ban all overriding implementations of `equals`.

**Comment by fommil** [comment]
also, if I block a package, e.g. `scala.collection.mutable`, I expect it to block instantiations of `ListBuffer` so we should also be considering the package parents as well. Unless we go for a regex/wildcard-based approach to consider this.

**Comment by olafurpg** [comment]
@MasseGuillaume recently added Denotation.overrides to semanticdb which would make it possible to implement this feature.

**Comment by vovapolu** [comment]
@fommil `Denotation.overrides` requires special compiler flag. Olaf also said semanticdb is going to make things easier :)

**Comment by olafurpg** [comment]
Why close this @fommil ?

**Comment by fommil** [comment]
Isn't this in the pr?

**Comment by olafurpg** [comment]
It's not merged yet, I prefer to close tickets after merge.

**Comment by vovapolu** [comment]
See https://github.com/scalacenter/scalafix/pull/655

**Comment by olafurpg** [comment]
It's possible to use `scala.meta.internal.semanticdb3._` to inspect OO hierarchies by looking for `CLASS_INFO_TYPE` and `.parents` as is done in PrettyType for ExplicitResultTypes

https://github.com/scalacenter/scalafix/blob/8d9750d89703c67f094a573c589447071b8dba57/scalafix-core/shared/src/main/scala/scalafix/internal/util/PrettyType.scala#L188-L194

Note that the `semanticdb3.Type` API is internal and awkward to use, we have plans to expose a nice ADT but I can't give a timeline on when that will happen.

Anyways, if someone wants to take a stab at this, feel free to experiment with it in the scalafix repo using PrettyType as inspiration 😊

**Comment by olafurpg** [comment]
Moved to https://github.com/vovapolu/scaluzzi/issues/4 where `Disable` is now hosted
