### ISSUE TITLE
New DisableConfig format

### ISSUE THREAD

**Issue by vovapolu** [scalacenter/scalafix#598]
Currently `Disable` rule is quite simple and has several issues (see https://github.com/scalacenter/scalafix/issues/559). We can change its behavior so that it would combine the old one with flexible settings and `DisableUnless`. 

Olaf suggested the following format for the updated rule:
```
Disable.symbols = [
  { 
    symbols = [
      {
         symbol = "blah"
         message = "blah blah blah"
      }, 
     "foo",
     "bar"
    ]
    unlessInsideBlock = "IO"   // just new name for unless from DisableUnless
    unlessSynthetic = true     // this option turns on/off the blocking of generated code
  }
]
```

**Comment by olafurpg** [comment]
Fixed in #601
