### ISSUE TITLE
use kind-projector syntax sugar

### ISSUE THREAD

**Issue by fommil** [scalacenter/scalafix#608]
https://github.com/non/kind-projector

e.g. rewrite

```scala
val convert = new (IList ~> List) {
  def apply[A](fa: IList[A]): List[A] = fa.toList
}
```

to

```scala
val convert = λ[IList ~> List](_.toList)
```

and similar at the type level.

**Comment by olafurpg** [comment]
This is a good candidate for a custom rule outside of the Scalafix repo. In the following weeks, we will try to move rules outside of the core repo and make sure that running external rules has the same nice user experience as running builtin rules.
