### ISSUE TITLE
ExplicitUnit should be merged into ProcedureSyntax

### ISSUE THREAD

**Issue by eed3si9n** [scalacenter/scalafix#617]
### steps

Run ProcedureSyntax

```scala
  abstract class Structural extends { def f() }
```

### problem

No changes.

### expectation

```scala
  abstract class Structural extends { def f(): Unit }
```

**Comment by eed3si9n** [comment]
I first thought it's the problem with structural types, but it seems that ProcedureSyntax doesn't handle procedure declarations.

### steps 2

```scala
  trait T { def gaa }
```

### problem 2

No changes.

### expectation 2

```scala
  trait T { def gaa: Unit }
```

**Comment by eed3si9n** [comment]
Hmm. ok so there is a rule for this but it's a separate one called `ExplicitUnit`?
Why was it separated? Aren't these called procedures in SLS?

**Comment by olafurpg** [comment]
ExcplicitUnit should probably be merged into ProcedureSyntax and deprecated. There is no good reason to separate them except I wasn't aware of procedural declarations in the early scalafix days.
