### ISSUE TITLE
scalafix:ok on object/classes/traits/etc

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scalafix#627]
I expect the following to ignore the linting:

```scala
object A {
  val a = null
} // scalafix:ok DisableSyntax.keywords.null
```

```
[fast2] Running DisableSyntax
/home/gui/fast2/src/main/scala/a.scala:4:11: error: [DisableSyntax.keywords.null] null is disabled
  val a = null
          ^
/home/gui/fast2/src/main/scala/a.scala:5:3: warn: [UnusedScalafixSupression.Disable] This comment does not disable any rule
} // scalafix:ok DisableSyntax.keywords.null
  ^
```

**Comment by marcelocenerine** [comment]
The bug is actually in scalameta. I will open a PR there to address this.

**Comment by olafurpg** [comment]
Can you elaborate on what the bug is @marcelocenerine ?

**Comment by marcelocenerine** [comment]
Similar to https://github.com/scalameta/scalameta/issues/897, but affecting comments at the bottom of a file. I have a fix already but wanted to add more tests before opening a pr (hopefully tonight)
