### ISSUE TITLE
Progress bar when running from sbt

### ISSUE THREAD

**Issue by dwickern** [scalacenter/scalafix#629]
The progress bar doesn't seem to work from sbt. It prints one line with some arbitrary progress number each time.
```
> scalafixCli 
[info] Running scalafix .....
[scratch] Running Disable
[scratch] Running Disable (96.36 %, 53 / 55)

Completed [scratch] Running Disable
[success] Total time: 5 s, completed Feb 22, 2018 2:24:30 PM
```
This confused me since I thought it meant 96% of the files passed the linter.

**Comment by olafurpg** [comment]
Thanks for reporting! The progress bar reports the number of processed files, regardless if those files contain linter violations or not. I will change the behavior to skip the progress bar unless `scalafixVerbose := true`.
