### ISSUE TITLE
Removing scalacOptions in 0.5.7 disable scalafix.

### ISSUE THREAD

**Issue by rossoha** [scalacenter/scalafix#638]
If you download  https://github.com/scalacenter/scalafix-sbt-example  and change scalafix version to 0.5.7, then remove `scalacOptions += "-Ywarn-unused-import"`  from `build.sbt`, it will not produce any changes.

**Comment by olafurpg** [comment]
Thanks for reporting! What is your expected behavior? RemoveUnusedImports requires -Ywarn-unused-import as documented here https://scalacenter.github.io/scalafix/docs/rules/RemoveUnusedImports

**Comment by olafurpg** [comment]
Yup, it should report an error in this case.
