### ISSUE TITLE
Link @deprecated annotation to rewrite rule

### ISSUE THREAD

**Issue by ShaneDelmore** [scalacenter/scalafix#64]
Consider creating a way to link the @deprecated to a rewrite allowing users of scalafix to automatically remove usage of the deprecated syntax.

**Comment by olafurpg** [comment]
I think this is a brilliant idea! Some quick thoughts

- The compile task in sbt returns an `Analysis` which may contain deprecated compiler warnings

```
      compile.value.infos.allInfos.values.head.reportedProblems
      compile.value.infos.allInfos.values.head.unreportedProblems
```

- Alternatively, in NscSemanticApi, we might be able to extract the compilation warnings from `g.reporter`. This might require hijacking the reporting during initialization.

As for what the library authors write in the deprecated.message field. We'd nice some syntax that's
- lightweight (easy to read/write, doesn't pollute console during compile)
- powerful (possible to model things such as lists)
- not custom/hacky (please don't create yet another configuration language)

My vote goes for hocon. But I'm interested to hear what other folks think.

**Comment by olafurpg** [comment]
Currently blocked by https://github.com/scalameta/scalameta/issues/759

**Comment by olafurpg** [comment]
Deprecation messages are now included in the SemanticDB thanks to https://github.com/scalameta/scalameta/pull/1079 it is possible to implement a `FixDeprecations` rule that acts on reported deprecation warnings.
