### ISSUE TITLE
Please add support for sbt 1.0

### ISSUE THREAD

**Issue by petro-semeniuk-da** [scalacenter/scalafix#643]
Hi there

I tried to use scalafix by adding just two plugins (as per documentation):
```
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.5.10")
addCompilerPlugin("org.scalameta" % "semanticdb-sbt" % "0.6.0" cross CrossVersion.full)
```

however on sbt compile step I'm getting:
```
[warn]     ::::::::::::::::::::::::::::::::::::::::::::::
[warn]     ::          UNRESOLVED DEPENDENCIES         ::
[warn]     ::::::::::::::::::::::::::::::::::::::::::::::
[warn]     :: org.scalameta#semanticdb-sbt_2.12.4;0.6.0: not found
[warn]     ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]     Note: Unresolved dependencies path:
[warn]         org.scalameta:semanticdb-sbt_2.12.4:0.6.0 (/Users/petrosemeniuk/src/da/spider/da-scala/project/plugins.sbt#L15-16)
[warn]           +- default:da-scala-build:0.1.0-SNAPSHOT (scalaVersion=2.12, sbtVersion=1.0)
[error] sbt.librarymanagement.ResolveException: unresolved dependency: org.scalameta#semanticdb-sbt_2.12.4;0.6.0: not found
[error]     at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:331)
```

**Comment by gabro** [comment]
The documentation may be a bit miseleading, but you don't need `semanticdb-sbt` unless you're trying to migrate from sbt 0.13 to sbt 1.0.

It seems you're already using sbt 1.0, so you can't just remove the `semanticdb-sbt` plugin, as it's essentially an experimental workaround for the lack of Scalameta support in Scala 2.10 (used by sbt 0.13)

**Comment by gabro** [comment]
@olafurpg do you think it's worth to add a note in the documentation saying something along these lines

> You only need `semanticdb-sbt` if you intend to use the `Sbt1` rule to migrate from sbt 0.13 to sbt 1.0

?

**Comment by gabro** [comment]
@olafurpg do you think it's worth to add a note in the documentation saying something along these lines

> You only need `semanticdb-sbt` if you intend to use the `Sbt1` rule to migrate from sbt 0.13 to sbt 1.0

?

**Comment by petro-semeniuk-da** [comment]
Ok, so I left in my plugins.sbt only following line:
```
addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.5.10")
```

on executing `sbt compile` I'm getting:

```
[info] Done compiling.
[error] sbt.librarymanagement.ResolveException: unresolved dependency: org.scalameta#semanticdb-scalac_2.12.3;2.1.7: not found
[error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:331)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:205)
```

**Comment by olafurpg** [comment]
@petro-semeniuk-da what happens if you upgrade to scala 2.12.4? Alternatively, `scalafixEnable` is a command that sets scalaVersion for you.

**Comment by gabro** [comment]
Ok, that's a different problem.

The only versions supported at the moment are 2.12.4 and 2.11.12.

**Comment by olafurpg** [comment]
> do you think it's worth to add a note in the documentation saying something along these lines

@gabro We should probably just remove semanticdb-sbt, it's an unmaintained project that. It's been in the backlog to simplify it with https://github.com/scalacenter/scalafix/issues/589 but I'm currently working first on scoping for ExplicitResultTypes.

I just looked at the sbt-scalafix installation instructions and they are quite confusing. I think

**Comment by olafurpg** [comment]
Opened https://github.com/scalacenter/scalafix/pull/644 to remove semanticdb-sbt and sbtfix from the docs.

**Comment by olafurpg** [comment]
sbt-scalafix used to print a warning when the scalaVersion didn't match an exact supported version, but it seems that got removed at some point. Would it be worth adding it back to give users some hints what might be wrong?

**Comment by petro-semeniuk-da** [comment]
@gabro  @olafurpg thanks much for the help.

+1 for documentation update and making it print nice error on scala version mismatch.
