### ISSUE TITLE
Remove semanticdb-sbt integration

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scalafix#645]
Currently, scalafix supports semantic rewriting of sbt sources through semanticdb-sbt. This functionality does not work so well and its implementation is no longer being improved. Given that it's still a maintenance burden to upgrade semanticdb-sbt https://github.com/scalameta/semanticdb-sbt/pulls?q=is%3Apr+is%3Aclosed
<img width="456" alt="screen shot 2018-03-05 at 10 52 23" src="https://user-images.githubusercontent.com/1408093/36968606-520db92e-2063-11e8-8618-a745cbc197c2.png">

we should remove this integration.

* [ ] upgrade to sbt 0.13.17

**Comment by xeno-by** [comment]
😍
