### ISSUE TITLE
Import shadowing

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scalafix#65]
See https://github.com/samuelgruetter/srewrite/blob/06b2beaca98b7bbabc26d6936057c70b4dc2b456/test/importShadowing.scala

I'd be curious to know how many files are affected by this.

**Comment by paulp** [comment]
Many, many files will be affected if you do not track which namespaces are actually populated by each import. Have a look at the ammonite issues for more. It's super unfortunate everyone has to reproduce scala's import logic from scratch; nobody has yet gotten it right.

**Comment by paulp** [comment]
Now that I'm at a keyboard, see [here](https://issues.scala-lang.org/browse/SI-7953), and [here](https://github.com/lihaoyi/Ammonite/issues/199), and here's a test case.
```scala
package p1 {
  class Order
}

package p2 {
  object Order {
    def apply(x: p1.Order): Unit = println("ok!")
  }
}
// Welcome to Scala version 2.11.7 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_72).
// Type in expressions to have them evaluated.
// Type :help for more information.
//
// scala> import p1._, p2._ ; Order(new Order)
// ok!
```

**Comment by olafurpg** [comment]
> It's super unfortunate everyone has to reproduce scala's import logic from scratch

Indeed, to my best knowledge, there is no public api in the compiler to reproduce the context that holds which symbols are in scope at each position. There's a WIP PR in #42 that tries to reuse as much as possible from the compiler APIs (e.g., owner chains) to reproduce this context.

As for this particular rewrite, the challenge is to either

- find a way to automatically rewrite the code to compile in dotty (might be hard to cover all cases) or
- find the places where this happens and and report a helpful error message on how to manually fix it

**Comment by paulp** [comment]
For reference, the relevant code is [lookupSymbol](https://github.com/scala/scala/blob/2.12.x/src/compiler/scala/tools/nsc/typechecker/Contexts.scala#L994-L1175).

**Comment by olafurpg** [comment]
I am no longer able to reproduce the compile error for Dotty, the linked example works the same in scalac and dotc.

Dotc: https://scastie.scala-lang.org/ixI7VqH6Rfq8sXUeCnHuhA
Scalac: https://scastie.scala-lang.org/TJlVlkmUQluJ9JY7K6Y5Vw

Thank you for the `lookupSymbol` link @paulp, it was informative.
