### ISSUE TITLE
Explicit return types on public members

### ISSUE THREAD

**Issue by fommil** [scalacenter/scalafix#651]
Much like the explicit implicits rule, it would be good to force all public members to declare their type.

Type inference on public methods is a scala feature i do not agree with.

1. It makes it hard to read code
2. In slows down the compiler, especially IDEs which must do large inferences instead of local
3. The inferred type looks into the binary api and locks the implementer.

**Comment by olafurpg** [comment]
Did you try the configuration options? https://scalacenter.github.io/scalafix/docs/rules/ExplicitResultTypes#examples It's possible to opt-into public and non-implicit members.

btw, the `unsafeShortenNames` options is about to get a whole lot easier in the coming few weeks. Been working on it for over 2 months now!

**Comment by fommil** [comment]
@olafurpg but this is for implicits? I'm saying to add different behaviour for non-implicits :smile: 

They'd probably need different config. I might want `private implicit val`  to have explicit types, but not a regular `private` member or locally scoped thing.

**Comment by olafurpg** [comment]
> but this is for implicits?

That's for non-implicits.

>  I might want private implicit val to have explicit types, but not a regular private member or locally scoped thing.

ExplicitResultTypes has no config to opt-out of implicits.

**Comment by fommil** [comment]
wait, what? You're saying these options

```
ExplicitResultTypes.memberKind = []
ExplicitResultTypes.memberVisibility = []
```

are for non-implicits? :dizzy_face:

**Comment by olafurpg** [comment]
The following should be what you are looking for
```
ExplicitResultTypes.memberKind = [Def, Val, Var]
ExplicitResultTypes.memberVisibility = [Public, Protected]
```

**Comment by olafurpg** [comment]
Seems it wasn't clear from the docs, we should explain those are for **non-implicits**

**Comment by fommil** [comment]
![](https://media.giphy.com/media/DYH297XiCS2Ck/giphy.gif)

**Comment by olafurpg** [comment]
unsafeShortenNames will get better soon too 😉
