### ISSUE TITLE
Snapshots are noisy when used in sbt-scalafix

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scalafix#658]
While using a snapshot version of scalafix there are tons of logs with
```
Downloading https://repo1.maven.org/maven2/org/scalameta/metacp_2.12/3.5.0-72-74924a4a-SNAPSHOT/metacp_2.12-3.5.0-72-74924a4a-SNAPSHOT.pom
```
even if nothing is downloaded.

**Comment by fommil** [comment]
it's not just noisy, it looks like it's hitting the network.

**Comment by olafurpg** [comment]
There are probably missing some settings in https://github.com/scalacenter/scalafix/blob/306b4611b602e2bf54dbcfcd8dc48857ade9af60/scalafix-sbt/src/main/scala/scalafix/internal/sbt/ScalafixJarFetcher.scala to configure ttl.

**Comment by olafurpg** [comment]
Can you validate if this is fixed in #690 @fommil ?

**Comment by fommil** [comment]
maybe a bit better, but still a big regression to the last stable release...

```
java.lang.OutOfMemoryError: Java heap space
Dumping heap to java_pid30192.hprof ...
```

**Comment by fommil** [comment]
but at least the noise has gone away.

**Comment by fommil** [comment]
I still get the noise.

**Comment by olafurpg** [comment]
Let's see setting ttl fixes the issue https://github.com/scalacenter/scalafix/pull/695

**Comment by olafurpg** [comment]
Can you validate if 0.6.0-M3-5-c55a0b83-SNAPSHOT fixes the problem?

**Comment by fommil** [comment]
yeah, it does... but all the `Running` / `Completed` noise is back :sob:
