### ISSUE TITLE
ImplicitParameters: ban everything except typeclasses

### ISSUE THREAD

**Issue by fommil** [scalacenter/scalafix#661]
@vovapolu I think you tried to touch on this in your recent PR

It would be great to have a rule that complains when using an implicit for anything other than a typeclass, e.g. for a configuration or "context". `MonadReader` / `ReaderT` is a far superior alternative.

The only problem is, I have no idea how to tell if something is a typeclass. We could guess and say "having one type hole" but we'd need to consider things like `MonadError[F[_], Err]` so it's about one type hole at the point of use, not the point of definition.

**Comment by edmundnoble** [comment]
There's a warning for this in WartRemover, called `ImplicitParameters`.

**Comment by fommil** [comment]
@edmundnoble yeah, but it doesn't work.

**Comment by fommil** [comment]
is this then just a dupe of #529 ?

**Comment by edmundnoble** [comment]
What do you mean? It works for me.

**Comment by fommil** [comment]
ok, closing as a dupe of #529 if that's what the mega wartremover ticket is about.

**Comment by olafurpg** [comment]
Sounds similar to wartremover `ImplicitParameters` http://www.wartremover.org/doc/warts.html A simple trick might be to prohibit implicit term parameters of shape `F` (no Type.Apply)

**Comment by fommil** [comment]
yeah, that's probably enough.

**Comment by fommil** [comment]
oh, hold on, we closed that big ticket and said we'd create new tickets for things that were not covered in the original pass. Opening again!

**Comment by edmundnoble** [comment]
WartRemover goes a step further; it disallows implicit term parameters even with `Type.Apply`, as long as none of the type parameters were introduced by the method in question.

**Comment by fommil** [comment]
Requiring the type to be introduced by the method is too harsh. If the class can introduce it too, all the better, but i suspect the single hole rule would need to be lifted.

**Comment by edmundnoble** [comment]
@olafurpg Sure:
```scala
class DoSomething[C] {
  def doIt(implicit ev: Monoid[C]): C = ???
}
```
@fommil I think that's acceptable. I think as long as at least one type parameter of the `Type.Apply` is a type variable or type member, it's a valid use of type classes.

**Comment by olafurpg** [comment]
Thanks for the example @edmundnoble That should be possible to support by querying if the kind of all type arguments are `TYPE_PARAMETER` or not https://github.com/scalameta/scalameta/blob/master/semanticdb/semanticdb3/semanticdb3.md#symbolinformation

**Comment by fommil** [comment]
I was thinking about the TypeClass trait in dotty...

Actually, having a cats.TypeClass, scalaz.TypeClass and simulacrum.TypeClass (or whatever) dummy trait with a single type parameter is really great idea from a tooling perspective, with literally nothing else in it.

We're currently trying to figure out how to implement the rule "implicits should only be used for typeclasses" but how do we detect typeclasses? So if there was even a convention we could follow, it would help a lot.

**Comment by olafurpg** [comment]
This is a good idea. After the PR https://github.com/scalacenter/scalafix/pull/827, we are moving most built-in rules outside of the scalacenter/scalafix repository so that they can evolve at a different pace than Scalafix APIs. As long as a custom rule meets a certain level of quality, it can still 

- be automatically be included by sbt-scalafix
- have tab completion in the sbt shell like built-in rules
- be documented on the main Scalafix website

Ping us on Gitter if you believe your rule is good enough for inclusion. Don't hesitate to ask for help around code review or general guidance on writing/sharing custom rules.
