### ISSUE TITLE
matching on unsealed interface

### ISSUE THREAD

**Issue by fommil** [scalacenter/scalafix#670]
when providing a pattern match on an unsealed interface, it would be good to request that the developer provides a catch-all clause. This is particularly important for cases where users expect to provide a partial but the underlying api expects a total function, like when matching on `Throwable`.

Bad:

```scala
  def foo(t: Throwable): Boolean = t match {
    case i: IllegalArgumentException => true
  }
```

I don't want to say "good" but you know what I mean

```scala
  def foo(t: Throwable): Boolean = t match {
    case i: IllegalArgumentException => true
    case _: Throwable => false
  }
```

**Comment by olafurpg** [comment]
Thanks for reporting! I believe this functionality should belong in the compiler, which already has advanced infrastructure for exhaustivity checking.

**Comment by fommil** [comment]
But it only exhaustively checks when the input is sealed. I don't think the compiler team would be interested in adding support for this in the general case as it would break too much code.

**Comment by olafurpg** [comment]
I agree this is a good rule and it does not necessarily have to live in the compiler.

My reasoning to close this ticket is related to https://github.com/scalacenter/scalafix/pull/722#pullrequestreview-117521985 In the long term, I envision that rules like this can live in a separate 3rd party library. I would prefer to invest more resources into making it easier to install/maintain/share/run 3rd party rules than continue to add more functionality into the core. The core should IMO only contain the most generic rules like `ExplicitResultTypes` and `OrganizeImports` (once implemented), which either require internal APIs or custom additions to the patch system.

**Comment by Daenyth** [comment]
Is anyone aware of a third-party implementation of this rule that's reusable?
