### ISSUE TITLE
weird search results....

### ISSUE THREAD

**Issue by fommil** [scalacenter/scalafix#676]
I tried a few search results and am very disapointed by the results... is scaladex broken right now?

- json => giving me random libraries rather than the big hitters like: argonaut, circe, spray-json, play-json, jsoniter, upickle, ensime-json, etc etc
- emacs => these are nothing to do with emacs. Where are the emacs scala packages, CLI tools, and, of course, ensime?
- xml => where is any of the recent work on getting rid of literals and replacing with string interpolation, or jon pretty's xylophone, or (my) xmlformat?
- typeclass derivation => where is shapeless and scalaz-deriving?
- monad => what, is, going, on

**Comment by olafurpg** [comment]
Wrong repo 😜

**Comment by fommil** [comment]
GOD DAMN YOU GOOGLE AUTOCOMPLETE!!!!
