### ISSUE TITLE
Disable should not operate on the package part of an FQN

### ISSUE THREAD

**Issue by fommil** [scalacenter/scalafix#680]
I am not sure if this is a feature or a bug... but it is certainly unexpected

This config

```
      {
        regex = {
          includes = [
            "java.*"
          ]
          excludes = [
            "fommil.*"
            "scalaz.*"
            "java.lang.String"
            "java.time.Instant"
            "java.net.URI"

            # package prefixes are needed
            "java"
            "java.lang"
            "java.net"
            "java.time"
          ]
        }
        message = "Untrusted code, wrap with IO or add to the excludes list in scalafix.conf"
      }
```

will block the allowed `java.time.Instant` without the section marked "package prefixes are needed".

It's an easy workaround, but the semantics feel weird to me. I am happy enough with the workaround, but I think it would be best if packages were not part of the disable check ... only symbols and types in those packages.

**Comment by fommil** [comment]
The correct fix is to use `java.time.Instant#`

**Comment by fommil** [comment]
Nope, seems even with that we still need to keep

```
           "java"
```

**Comment by fommil** [comment]
Actual workaround (until #700 is fixed) is to add all packages to the `excludes` with line start/end terminators, e.g.

```
            "^\\Qjava.\\E$"
            "^\\Qjava.lang.\\E$"
            "^\\Qjava.time.\\E$"
            "^\\Qjava.net\\E$"
```

**Comment by olafurpg** [comment]
Superseded with #715, the proposed solution there should address this issue with a more hopefully more intuitive UX compared to regexp and also better performing backing implementation.
