### ISSUE TITLE
noValInAbstract exceptions

### ISSUE THREAD

**Issue by fommil** [scalacenter/scalafix#684]
it would be good to allow `noValInAbstract` if the val is lazy. No rewrite, because often `def` is better.

**Comment by fommil** [comment]
also might be worth allowing if it's `override val` and the parent field is a `val`. Although I'm in two minds about that... requiring a `// scalafix:ok` at least indicates that you've thought about it.

**Comment by fommil** [comment]
`val` in trait can be needed for stable types, e.g. https://github.com/alexknvl/leibniz/blob/master/src/main/scala/leibniz/Sigma.scala#L5 but arguably a `// scalafix: ok` (with a comment #702) should suffice to indicate that the developer has thought about it.

Another case is when the `val`'s body either does not refer to any other values or methods in the trait (or its mixins) or only refers to values defined in the `abstract class` constructor // suggested by @pjrt.

**Comment by dsilvasc** [comment]
@fommil was this closed after being implemented or just lost interest?

**Comment by olafurpg** [comment]
@dsilvasc please open a separate issue if you want to discuss this ticket
