### ISSUE TITLE
scalafixCli configuration scoping rules are wrong

### ISSUE THREAD

**Issue by fommil** [scalacenter/scalafix#692]
if we add a custom test configuration, e.g. integrationtest or user provided, the cli seems to run on the `test` configuration regardless.

The expectation is that invoking `it:scalafixCli` or `resilience:scalafixCli` should **only** run scalafix for that test configuration.

**Comment by olafurpg** [comment]
The relevant piece of code is here

https://github.com/scalacenter/scalafix/blob/17f51b73c5589cded98aa4efe36be4507b53f43c/scalafix-sbt/src/main/scala/scalafix/sbt/ScalafixPlugin.scala#L213

inside of a `Def.taskDyn`. I would love help in this area how to make this work correctly. Any idea @dwijnand ?

**Comment by dwijnand** [comment]
where is `scalafixConfigure`?

**Comment by olafurpg** [comment]
This is from a pre-release that is not documented on the website. The way to add a new configuration is

https://github.com/scalacenter/scalafix/blob/17f51b73c5589cded98aa4efe36be4507b53f43c/scalafix-sbt/src/main/scala/scalafix/sbt/ScalafixPlugin.scala#L55-L72

```scala
  override def projectSettings: Seq[Def.Setting[_]] =
Seq(Compile, Test).flatMap(inConfig(_)(scalafixConfigSettings))
```

**Comment by olafurpg** [comment]
Do we need to pass around a `ScopeFilter` explicitly to make this work?

**Comment by dwijnand** [comment]
at a guess.. `inConfig` can't see through `taskDyn`? 😒

**Comment by olafurpg** [comment]
That would be my guess, I would be impressed if it did see through it. `scalafixConfigSettings` could require `scalafixConfigSettings(Compile)` in order to build the `ScopeFilter`.

**Comment by olafurpg** [comment]
I agree this is an important issue we should address before v0.6 stable @fommil Now that the sbt plugin finally uses a richer API (not just basic cli anymore) we can look into this next

**Comment by olafurpg** [comment]
I believe this issue is fixed after https://github.com/scalacenter/sbt-scalafix/pull/20, but I don't use this feature myself so can't be 100%. Copy-pasting commit message:

Previously, the scalafix command invoked an unscoped `compile` inside a
dynamic task. Now, the plugin scopes the command to the configuration.
This commit adds a scripted tests to test configurations in isolation
and it seems to work according to the expectations in the linked ticket:

> "invoking it:scalafixCli or resilience:scalafixCli should only run
>  scalafix for that test configuration"

Happy to iterate further if necessary.
