### ISSUE TITLE
multiple scalafix:ok will fail

### ISSUE THREAD

**Issue by fommil** [scalacenter/scalafix#694]
because there are two `scalafix:ok` markups, both get ignored.

```scala
  val map: mutable.Map /* scalafix:ok */ [String, Data] = mutable.Map.empty /* scalafix:ok */

```

**Comment by olafurpg** [comment]
Can you please include more details even if it feels like spelling out the problem. 

* What is your configuration?
* What is the expected output?
* What is the obtained output?

**Comment by fommil** [comment]
yeah, sorry, it's difficult because this is a proprieatry codebase. Roughly the config is just `Exclude.symbols` but I think this is relevant to any two rules on the same line. I've also seen it with `DisableSyntax.keywords` for e.g. a var that is set to null like

```
var foo: String = null
```

with the `scalafix:ok` after `var` and `null`.

**Comment by olafurpg** [comment]
I was able to reproduce with this test case

```scala
/* ONLY
rules = Disable
Disable.ifSynthetic = [
  "scala.Any"
]
*/
package test

class DisableIfSynthetic {
  val x =  // assert Disable.Any
    null.asInstanceOf[Any]
}
```

There seems to be a bug in how ContextTraverser uses `allDisabledSymbols` here https://github.com/scalacenter/scalafix/blob/6d48e0c419a63956274cfcc8e9bb23601c75ccfa/scalafix-core/shared/src/main/scala/scalafix/internal/rule/Disable.scala#L138

Could you take a look @vovapolu ?

**Comment by olafurpg** [comment]
Whoops, wrong ticket, sry 😅 Removing comment above

**Comment by marcelocenerine** [comment]
The root cause is basically the same as in #693. The following test reproduces it:

```scala
/*
rules = Disable
Disable.symbols = [
  scala.collection.mutable
]
*/
package test.escapeHatch

import scala.collection.mutable

object OverlappingExpressionToggles {

  val map: mutable.Map[String, String] /* scalafix:ok */ = mutable.Map.empty /* scalafix:ok */
}

```

output:

```
scala/test/escapeHatch/OverlappingExpressionToggles.scala:13:60: error: [Disable.mutable]:
mutable is disabled
  val map: mutable.Map[String, String] /* scalafix:ok */ = mutable.Map.empty /* scalafix:ok */
                                                           ^
```

Both switches overlap and interfere with each other.

@fommil as a potential workaround, you can keep only the last `/* scalafix:ok */` as it disables the rules for the entire expression.

I'm working on a fix which should address both issues.
