### ISSUE TITLE
regexes should be interpreted as "match exactly"

### ISSUE THREAD

**Issue by fommil** [scalacenter/scalafix#700]
The following regexes

```scala
includes = "\\Qjava.\\E.*"
excludes = "\\Qjava.\\E"
```

result in a no-op because they are interpreted as sub pattern matches, which came up in #680 

This is very unsurprising, I think it would be best if regexes were interpreted as "match exactly" which can be implemented by adding `^` / `$` to the front/end of the string (if not already present).

**Comment by olafurpg** [comment]
Superseded by #715
