### ISSUE TITLE
Disable.symbols should disable both explicits and synthetics

### ISSUE THREAD

**Issue by fommil** [scalacenter/scalafix#703]
I'm trying to construct rules to `Disable` calls to `apply` on the stdlib collections, e.g.

```scala
val thing = List("foo")
thing(0)
```

but these only show up under synthetics in the semanticdb and I have to use these synthetic rules instead...

```
   "scala.collection.MapLike#apply(K)."
   "scala.collection.LinearSeqOptimized#apply(Int)."
```

Is this a bug or is there an explanation for it?

I expected to be able to ban them from `Disable.symbols`.

**Comment by olafurpg** [comment]
`Disable.ifSynthetic` should catch those, iirc, I proposed to @vovapolu to make

- Disable.symbols work on synthetics + explicits
- Disable.ifSynthetic work on synthetics only
- Disable.ifExplicit work on explicits only

**Comment by fommil** [comment]
interesting. I think that would be good. Shall we redefine this ticket to mean that?

**Comment by fommil** [comment]
the workaround is to import a file in both blocks.

**Comment by olafurpg** [comment]
Updated the title. @vovapolu would you be interested in taking on this issue? 😄

**Comment by fommil** [comment]
(you forgot to save the update)

**Comment by olafurpg** [comment]
whoops, done.

**Comment by olafurpg** [comment]
Moved to https://github.com/scalacenter/scalafix/issues/703
