### ISSUE TITLE
explicit return type: some failures

### ISSUE THREAD

**Issue by fommil** [scalacenter/scalafix#705]
The explicit return types that I manually added in this branch

  https://gitlab.com/fommil/scalaz-deriving/merge_requests/131

caused failures inside the rule. They are all localised to a single file. Although I initially thought that the problem might be related to HKT or type lambdas, I am now unsure as there were problems with methods returning `Option[B]`. Could be related to class nesting?

**Comment by olafurpg** [comment]
Can you link to the log entries with the failures? I couldn't find them from the merge request

**Comment by fommil** [comment]
if you back out the changes to `OneAndLazy.scala` you'll see them, I didn't keep a log
