### ISSUE TITLE
Adding a trait to a class

### ISSUE THREAD

**Issue by ghidei** [scalacenter/scalafix#717]
Is there an API for doing this? My solution to do this "manually" works in isolation but when it messes up other patches when concatenated with them.

**Comment by olafurpg** [comment]
Thanks for reporting! 

Here's a commit doing the reverse https://github.com/olafurpg/scalafix/commit/c8c58318227467a85e522bc2e7abc9d2c584dcf0 it's tricky if you want to handle all cases.

This would be a good candidate for the patch api

- `addTemplateParent(Template, parent: Init): Patch`
- `removeTemplateParent(parent: Init): Patch`

Those could be high-level patches to accommodate composing multiple rules that add/remove template parents.

**Comment by olafurpg** [comment]
Following up comment on gitter, this was resolved by using `addRight` instead of `replaceTree`. The patch api is sorely missing documentation for how to compose more complex transformations, but that is a separate ticket.
