### ISSUE TITLE
Rewrite that replace Some() constructor by Option() constructor

### ISSUE THREAD

**Issue by joan38** [scalacenter/scalafix#721]
```
val a = Some(hey)
```
should be rewrote:
```
val a = Option(hey)
```
Since the `Some()` constructor is not safe.

I'm happy to take a shot to this one when I will have time.

**Comment by olafurpg** [comment]
This is a good idea! I'll copy-paste my review from #722 

I am a bit on the fence to include this rule into the core. In the long term, I envision that domain specific rules like this rule will live as 3rd party modules and the core contains only the most generic rules like ExplicitResulTypes and OrganizeImports (once it's implemented).

I admit the process has been unclear so far on what rules are added to core repo and which ones are not. I have probably been too relaxed in the past and merged more than I should have, which is not sustainable.

I'm sorry, but I recommend you host this rule in a separate repo using the g8 template https://scalacenter.github.io/scalafix/docs/rule-authors/setup#scalacenterscalafixg8 I know it's more inconvenient to share/run such rules than have them builtin but I hope to make that workflow more ergonomic in the future.
