### ISSUE TITLE
Procedure syntax bug

### ISSUE THREAD

**Issue by joan38** [scalacenter/scalafix#730]
```
def hey(f: String => Unit = _ => ()) = ???
```
is rewritten:
```
def hey(f: String => Unit = _ => (): Unit =) = ???
```
The workaround is having in input:
```
def hey(f: String => Unit = _ => {}) = ???
```

**Comment by olafurpg** [comment]
Thanks for reporting! I am unable to reproduce

```scala
cat p.scala

object a {
   def hey(f: String => Unit = _ => ()) = ???
   def hey(f: String => Unit = _ => ()) { println(1) }
}
➜  target git:(add-used-config-to-docs) coursier launch ch.epfl.scala:scalafix-cli_2.12.4:0.6.0-M5 -- -r ProcedureSyntax --stdout p.scala

object a {
   def hey(f: String => Unit = _ => ()) = ???
   def hey(f: String => Unit = _ => ()): Unit = { println(1) }
}
```

Can you include more information about your setup?

**Comment by joan38** [comment]
Sorry my example is probably not good.
This is happening here: https://github.com/apache/kafka/blob/trunk/core/src/main/scala/kafka/server/ReplicaManager.scala#L474

**Comment by olafurpg** [comment]
What version are you using? Some ProcedureSyntax bugs were fixed recently, I am unable to reproduce with the latest milestone

```
coursier launch ch.epfl.scala:scalafix-cli_2.12.4:0.6.0-M5 -- -r ProcedureSyntax --stdout p.scala

object a {
   def hey(f: String => Unit = _ => ()): Unit = { println(1) }
}
```

PS. Keep in mind that the latest stable version v0.5.10 is quite far behind the current master. I hope to get v0.6 stable out soon but we are still blocked by a few more refactorings.

**Comment by joan38** [comment]
I was using scalafix 0.5.10 indeed. So this is probably fixed already.
