### ISSUE TITLE
MissingFinal.noLeakingSealed is ignored

### ISSUE THREAD

**Issue by fommil** [scalacenter/scalafix#755]
in 0.6.0-M9 in https://gitlab.com/fommil/scalaz-deriving/ the missing `sealed` rule is triggering on some files.

However, it's not possible to fix this because of a bug in scalac where SAM types cannot be used on sealed traits.

Unfortunately the documented config to disable this rule is ignored.

The workaround is to use `// scalafix:ok` on a case by case basis (which is probably the correct thing to do).

**Comment by olafurpg** [comment]
Can you explain what the obtained/expected behavior is? Is `MissingFinal` reporting an error when it shouldn't? Can you point to the file in scalaz-deriving where this happens?

**Comment by fommil** [comment]
the obtained behaviour is the rule is triggering, despite being disabled.

the expected behaviour is for it not to fire.

the file/line is https://gitlab.com/fommil/scalaz-deriving/blob/master/examples/xmlformat/src/main/scala/xmlformat/DerivedXDecoder.scala#L50-51 but you'd have to run it in the whole project to see that, no?

**Comment by gaelrenoux** [comment]
The MissingFinal.noLeakingCaseClass configuration value is ignored as well. The rule triggers wether I put true or false.

**Comment by olafurpg** [comment]
Thanks for reporting! The `Disable` rule has now moved to a separate repo and I've reported this issue here https://github.com/vovapolu/scaluzzi/issues/2
