### ISSUE TITLE
Make Patch.isEmpty return false if the patch produces an empty diff

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scalafix#772]
I'm using `ctx.replaceSymbols` to replace some symbol. I would like to know if the patch replaced something to add an additional import. 

`Patch.nonEmpty` only check if the `Patch` is the `EmptyPatch`, this is a bit counter-intuitive. I would rename this `isEmptyPatch`. I think the semantic of `isEmpty` should be: did it changed something?

**Comment by ShaneDelmore** [comment]
What I have been doing for now is:

val patches: Seq[Patch] = tree.collect(emitPatches)
val patchesWithImportIfNeeded = if (patches.nonEmpty) (importPatch +: patches) else patches
patchesWithImportIfNeeded.asPatch

**Comment by olafurpg** [comment]
This is a good idea @MasseGuillaume I agree that the contract of `Patch.isEmpty` should be that it returns true when the patch produces an empty diff.

@ShaneDelmore That trick won't work for builtin patches like `replaceSymbol` that are applied "at the end of the world" (after the rule has finished processing).

**Comment by olafurpg** [comment]
In order to implement this functionality the `isEmpty` method would need to accept an implicit `SemanticDoc` argument to apply the patch meaning it can't be used for syntactic ruesl. I propose we keep `isEmpty` unchanged and introduce another method `producesEmptyDiff(implicit doc: SemanticDoc)`. WDYT?

**Comment by MasseGuillaume** [comment]
@olafurpg What about this idea, It was suggested by @Duhemm:

```scala
trait SemanticDoc
trait Patch

trait Low {
  implicit class SyntaxticPatchExtensions(patch: Patch) {
    def isEmpty: Boolean = true
  }
}

trait High extends Low {
  implicit class SemanticPatchExtensions(patch: Patch)(implicit doc: SemanticDoc) {
    def isEmpty: Boolean = false
  }
}

object A extends High

import A._

val p = new Patch{}
p.isEmpty // true
implicit val doc = new SemanticDoc{}
p.isEmpty // false
```

**Comment by olafurpg** [comment]
I prefer not to use advanced tricks like that in the public API. Let's keep it simple and explicit when you intend to compute the diff or check if `Patch == EmptyPatch`

**Comment by olafurpg** [comment]
There is no need for this method to be an extension method when it can be a concrete method on Patch

```scala
sealed abstract class Patch {
  def producesEmptyDiff(implicit sdoc: SemanticDoc) = ???
}
```

**Comment by MasseGuillaume** [comment]
I wanted to keep the same name `isEmpty`. It's ambiguous if you don't use the extension method trick.

**Comment by olafurpg** [comment]
I think it's better to have a separate name if the underlying implementation is significantly different: one method does `this == EmptyPatch` while the other computes `TokenPatch` (which can potentially be an expensive operation). My suggestion is `producesEmptyDiff` but I'm open for alternative names, maybe `isEmptyDiff`?
