### ISSUE TITLE
Document how to write symbolic symbol identifiers

### ISSUE THREAD

**Issue by NeQuissimus** [scalacenter/scalafix#777]
I would like to declare a `safeBlock` for `scalaz.\/` like so:

```
...
  {
    safeBlocks = [
      "scalaz/Maybe.attempt",
      "scalaz/Maybe.fromTryCatchNonFatal",
      "scalaz/Maybe.fromTryCatchThrowable",
      "scalaz/\/.fromTryCatchNonFatal", 
      "scalaz/\\/.fromTryCatchThrowable" # Here I try escaping the \, adding more \ does nothing
    ]
    symbols = [
      {
        regex = {
          includes = [
            # should live in a common file so we don't need to duplicate
            "^\\Qjava/net/URLEncoder#\\E.*$"
            "^\\Qjava/net/URLDecoder#\\E.*$"
          ]
          excludes = [
          ]
        }
        message = "Deterministic method is not total, must be called via Maybe.attempt"
      }
    ]
  }
...
```

I receive the following feedback

```bash
./scalafix --version
0.6.0-M12

./scalafix --verbose --config ./scalafix.conf .
error: 2 errors
[E0] java.lang.IllegalArgumentException: invalid symbol format
scalaz//.fromTryCatchNonFatal.
       ^

[E1] java.lang.IllegalArgumentException: invalid symbol format
scalaz/\/.fromTryCatchThrowable.
```

I thought I may have to escape the `\` but to no avail, the result is the same.

Replacing `\/` and my escaped variants with any symbolic identifier causes the same error.
It would seem that only alphanumeric identifiers are allowed (?)

**Comment by olafurpg** [comment]
Thanks for reporting! Symbolic identifiers need to be backticked as

```
scalaz.`\/`
```

This requirement is not documented on the website so I've updated the title of this issue to focus on documentation.

Please note that the scaluzzi project is using the latest unstable v0.6 milestone, it's recommended to stay on v0.5 until a stable v0.6 release is out.

**Comment by gabro** [comment]
Is this still relevant? I don't think there are any rules left that require a symbol configuration, maybe this needs to be documented in scaluzzi?

**Comment by olafurpg** [comment]
That's true, there are no rules that expose raw symbols to users. I kept this issue open since I was planning to write a dedicated section on `Symbol` but that can be tracked separately.
