### ISSUE TITLE
Expose more handlers in `ScalafixMainCallback`

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scalafix#784]
In #783 we introduce a programmatic API to hook into the linter reporting pipeline. It would be great to extend the capabilities to additionally support hooking into how files are fixed with access to the file contents before/after. For example, this could allow clients to interactively ask the user which patches to apply before writing to files.

cc/ @MasseGuillaume

**Comment by MasseGuillaume** [comment]
For example:

![eclipse rename preview](https://help.eclipse.org/luna/topic/org.eclipse.jdt.doc.user/gettingStarted/images/rename_cu_preview_dialog.png)

**Comment by olafurpg** [comment]
Closing as "unclear". Let's reopen this discussion once there is a concrete use-case like "Use Scalafix from the IDE".
