### ISSUE TITLE
Print more advanced types in the new synthetics printer

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scalafix#785]
While upgrading to Scalameta v4.0-M8 I took a shortcut and only handled `s.TypeRef` in the type printer. This is a reminder to complete the printer by handling all cases properly.

**Comment by MasseGuillaume** [comment]
Is it possible to convert to a scalameta tree and use the pretty printer we already have?

For example:

```scala
message TypeSignature {
  Scope type_parameters = 1;
  Type lower_bound = 2;
  Type upper_bound = 3;
}
```

vs

```scala
Decl.Type(mods: List[Mod],
                  name: scala.meta.Type.Name,
                  tparams: List[scala.meta.Type.Param],
                  bounds: scala.meta.Type.Bounds) extends Decl with Member.Type
```

**Comment by olafurpg** [comment]
It won't work to translate first to `scala.meta.Tree` since legacy `Denotation.names` and `Synthetics.text` require positions of symbol appearances. I agree it's undesirable to have duplicate work here, but most of the printer's code is adjusted from `metap` sources so it didn't take a long time to write. The legacy `v0` API shouldn't live long, it's primarily intended to make it easier for people to upgrade to v1

**Comment by olafurpg** [comment]
Closing as wontfix. The legacy API is only there to smoothen the migration path to the new `v1.SType` https://github.com/scalacenter/scalafix/blob/c29f576accb4cff77a596c9c933cb16932373e8c/scalafix-core/src/main/scala/scalafix/v1/SType.scala
