### ISSUE TITLE
Scalafix-testkit testOnly

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scalafix#791]
I'm using this pattern to test only one file:

```scala
class ScalafixTests extends scalafix.testkit.SemanticRuleSuite {
  // runAllTests()
  // to run only one test:
  testsToRun.filter(_.path.testPath.toNIO.getFileName.toString.stripSuffix(".scala") == "TupleNZippedSrc213.scala" ).foreach(runOn)
}
```

I would prefer to have this from the sbt prompt:

We can add the task: `scalafix-test` and use it like this:

`scalafix-tests/scalafix-test fix/TupleNZippedSrc213`

Ideally, we can add autocompletion. `scalafix-tests/scalafix-test fix/Tuple<tab>`

**Comment by olafurpg** [comment]
There is a built-in feature in scalatest that does this: `tests/testOnly -- -z TupleN` will run tests matching the regexp `TupleN`. I don't think there is a need for a custom scalafix solution here

**Comment by olafurpg** [comment]
This feature is not necessary since it's solved by the scalatest `-z` flag

**Comment by MasseGuillaume** [comment]
@olafurpg we should mention this trick in the documentation.

**Comment by olafurpg** [comment]
Sounds good @MasseGuillaume
