### ISSUE TITLE
Add code coverage

### ISSUE THREAD

**Issue by MasseGuillaume** [scalacenter/scalafix#797]
scoverage + coverall can help us identified untested code. For example, LegacyCodePrinter was untested.

**Comment by olafurpg** [comment]
PR closed with explanation https://github.com/scalacenter/scalafix/pull/800#pullrequestreview-147523184 I wish coverage tooling was more reliable so that we could enable it for every PR.

**Comment by olafurpg** [comment]
Let's give coverage a try and if it misbehaves we remove it #804
