### ISSUE TITLE
unable to disable string interpolation

### ISSUE THREAD

**Issue by fommil** [scalacenter/scalafix#803]
I want to disable the default string interpolation.

metap tells me that it is this symbol

```
[52:20..52:21) => scala/StringContext#s().
```

but this rule fails to work in either `Disable.symbols` or `Disable.ifSynthetic`

```
  {
    symbol = "scala/StringContext#s()."
    message = "use the safe `z`, `cord` and `str` interpolators"
  }
```

**Comment by olafurpg** [comment]
Thanks for reporting! This is a great ticket with minimal reproduction :)

I've moved the issue to https://github.com/vovapolu/scaluzzi/issues/1 where `Disable` and `MissingFinal` are now hosted as part of an effort to stabilize the scalafix project.
