### ISSUE TITLE
Scalafix cli doesn't release memory of files processed.

### ISSUE THREAD

**Issue by ShaneDelmore** [scalacenter/scalafix#810]
I attempted to run a syntactic scalafix lint on a large number of files using the coursier bootstrap and noticed that memory usage kept increasing until at 10GB of RAM used I killed it.  

The rule I ran was a silly test lint shown here:
```
//file DisablePrintln.scala
import scala.meta._
import scalafix.lint.LintMessage
import scalafix.v0._

/*
class DisablePrintln() extends Rule("DisablePrintln") {
  val errorSeverityRequired = 
    LintCategory.error("Remember to remove debugging printlns before committing code")

  override def fix(ctx: RuleCtx): Patch =
    ctx.tree.collect {
      case t @ Term.Name("println") =>
        ctx.lint(LintMessage("use logging instead of println", t.pos, errorSeverityRequired))
    }.asPatch
}

```

Then run via scalafix cli installed via coursier
```
coursier bootstrap ch.epfl.scala:scalafix-cli_2.11.12:0.6.0-M12 -f --main scalafix.cli.Cli -o scalafix
```

Then run against a large repo using:
```
./scalafix --rules=file:DisablePrintln.scala --test .
```

I was able to successfully run the rule on all code using the workaround of calling scalafix cli once per top level directory in the repo:
```
ls -d */ | xargs -I _ ./scalafix --rules=file:DisablePrintln.scala --test _
```

**Comment by olafurpg** [comment]
Thanks for reporting! To reproduce with M15

```
git clone https://github.com/olafurpg/scala-repos.git
cd scala-repos
coursier launch ch.epfl.scala:scalafix-cli_2.12.6:0.6.0-M15 --main scalafix.v1.Main -- -r ProcedureSyntax --verbose repos
```

I profiled memory usage and have some interesting results, 
<img width="595" alt="screen shot 2018-08-24 at 08 56 45" src="https://user-images.githubusercontent.com/1408093/44569806-dcade500-a77b-11e8-9d7e-c7fb3c184c83.png">

The hotspot is `unsafeHandleFile`, where we both parse sources and feed them to rules

https://github.com/scalacenter/scalafix/blob/1d9d6105e3580cd4ec85e531376a1608122fdb1c/scalafix-cli/src/main/scala/scalafix/internal/v1/MainOps.scala#L182-L239

Some thoughts

- the cli doesn't clear the evil global meta cache (https://github.com/scalameta/scalameta/issues/1068). I've fixed this locally, re-ran the cli and the new memory profile indicates many long-living references to `Token.{Space,Ident,...}` that previously accounted for ~300-400mb ram are no longer there. This might fix the main problem of growing heap size.
- Detection of comment suppression is responsible for ~30% of allocations. I think we can probably get that close to ~0% if we shirt-circuit that analysis when there is no comment token that starts with `// scalafix:`. I opened https://github.com/scalacenter/scalafix/issues/811 to track this idea.

I think it would be good to get both of those fixed merged and released. Then you can do another run to see if the problem has been fixed. WDYT @ShaneDelmore ?

**Comment by olafurpg** [comment]
I just released M16. Please give it a try and report back how it works. I'm happy to iterate more on improving performance.

I recommend using the --verbose option to see progress for long-running jobs.

**Comment by ShaneDelmore** [comment]
Thanks for the ridiculously fast response time.  I’ll test out M16 today.

**Comment by ShaneDelmore** [comment]
\o/ Not only does the new version resolve the memory error, it's much, much faster.  
On a test corpus/laptop that took 65m to process the xargs version, it took 8 minutes to process using M16, and 2 minutes after I modified the above rule to first check if the ctx.text contained "println".

**Comment by olafurpg** [comment]
That's amazing! @ShaneDelmore Thank you for reporting back ❤️
