### ISSUE TITLE
java.util.ServiceConfigurationError: scalafix.v1.Rule: Provider fix.MyRule_v1 not a subtype

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scalafix#819]
This error happens when we have `object MyRule_V1 extends Rule` and it should be `class MyRule_v1 extends SemanticRule`. We should document this since it took me a moment to understand what's going on.

**Comment by vito-c** [comment]
This caught me up for a bit when I was playing with scalafix. The main issue is that you can NOT have rules that are objects be the same definition as output/input objects with the same definitions... eg:
```
rules:
  package fix.my
  object Foo_v1 extends SemanticRule("fix.my.Foo_v1") {
  }
  package fix.my
  object Bar_v1 extends SemanticRule("fix.my.Bar_v1") {
  }
```
and
```
input/output:
  package fix.my
  object Foo_v1 {
  }
  package fix.my
  object Bar_v1 {
  }
```
will result in the error above so for my i/o I just change the objects to `Foo, Bar` and it worked... I can't remember if it was showing up with a single rule.
