### ISSUE TITLE
sbt: report helpful error message when running semantic rules with semanticdb disabled

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scalafix#847]
Currently, running a semantic rule without having SemanticDB enabled results in a verbose and cryptic error
```
> myproject/scalafix RemoveUnusedImports
[error] SemanticDB not found: META-INF/semanticdb/src/main/scala/...
[error] SemanticDB not found: META-INF/semanticdb/src/main/scala/...
[error] SemanticDB not found: META-INF/semanticdb/src/main/scala/...
[error] SemanticDB not found: META-INF/semanticdb/src/main/scala/...
...
```

The sbt plugin should abort the task early on in this case with a helpful error message since it knows whether semanticdb-scalac is enabled and if the rule is semantic.

**Comment by gabro** [comment]
As suggested in #845, I would link to the relevant docs page (or directly provide help inline as suggested by @MasseGuillaume)

**Comment by olafurpg** [comment]
The scalafix cli cannot include sbt-specific instructions but we could customize the error message for sbt here https://github.com/scalacenter/sbt-scalafix/blob/066b1133d38fc5dbb8ab595f7e7e7fbe73b78948/src/main/scala/scalafix/sbt/ScalafixPlugin.scala#L110
