### ISSUE TITLE
Broken example link

### ISSUE THREAD

**Issue by smlance** [scalacenter/scalafix#848]
The example link (https://github.com/scalacenter/scalafix/tree/master/scalafix-core/shared/src/main/scala/scalafix/internal/rule) under https://scalacenter.github.io/scalafix/docs/rule-authors/tutorial#example-rules is broken.

**Comment by olafurpg** [comment]
Thanks for reporting! The links have been fixed in current master but the new docs haven't deployed yet. The website will update more regularly after the v0.6 release comes out.
