### ISSUE TITLE
Add --syntactic option to ignore semantic rules

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scalafix#850]
It would be nice if the cli supported a --syntactic flag to skip over semantic rules. This would be nice in combination with #844 and for example when running scalafix on sbt sources in `*.sbt` and `project/**/*.scala`.

**Comment by ShaneDelmore** [comment]
I would definitely use this. Great idea.

**Comment by olafurpg** [comment]
The idea I have is that --syntactic means semantic rules in .scalafix.conf will be ignored. Is that how you expected it to work? I'm curious about your use-case @ShaneDelmore

**Comment by ShaneDelmore** [comment]
Exactly.  That way if users have set scalafix rules, say lints, all could run in CI but in git hook just fast syntactic rules could run.
