### ISSUE TITLE
Simplify github: expansion rules

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scalafix#860]
While writing the new tutorial for rule authors I got frustrated by the complicated expansion rules for the `github:org/repo` scheme

- doing `org/repo` without a version should work but it currently doesn't
- the filename for `org/repo/v1` becomes `Repo_v1.scala`, using a mix of g8-flavored camel case for the repo name and g8-flavored snake case for the version number.

I propose to simplify this

- `org/some-repo` expands by default to regular camel case `SomeRepo.scala`, with a fallback to g8-flavored `Somerepo.scala` in case of a 404.
- `org/some-repo/v1` expands to `v1.scala`, using the version number verbatim without automatic CamelCase/snake_case conversion

This makes the short syntax `org/some-repo` useful, and the `org/repo/RuleName` syntax simple to understand since there is no complicated casing rule to infer.

**Comment by gabro** [comment]
Makes sense, I'm in favor of this change 👍
