### ISSUE TITLE
scalafixDependencies should support custom resolvers

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scalafix#866]
Currently, sbt-scalafix only supports custom rules that are published to Maven Central but it's not possible to resolve/fetch custom rules from private nexus repositories. It would be great if we can use the new librarymanagement API in sbt 1 to support resolving from private repositories.

**Comment by kamilkloch** [comment]
@olafurpg: support for private repositories aside, is there currently a way to add other public custom resolver?

**Comment by olafurpg** [comment]
@kamilkloch there's no way to add other public resolvers at the moment, the resolvers are hardcoded here https://github.com/scalacenter/sbt-scalafix/blob/a3c4bf2444b47cd76103964487b3dc6885403673/src/main/scala/scalafix/internal/sbt/ScalafixCoursier.scala#L73 

It should be possible to read a `scalafixResolvers.in(ThisBuild)` setting and pass it here https://github.com/scalacenter/sbt-scalafix/blob/a3c4bf2444b47cd76103964487b3dc6885403673/src/main/scala/scalafix/internal/sbt/ScalafixInterface.scala#L15-L18 

Currently it's only possible to define maven repositories, but we can extend that in https://github.com/olafurpg/coursier-small/blob/fbb66ac66e3082a9c20992425c16748b4e12040f/small/src/main/scala/com/geirsson/coursiersmall/Repository.scala to support anything coursier supports. sbt-scalafix doesn't use coursier directly to avoid binary conflicts with sbt-coursier.

**Comment by olafurpg** [comment]
PR https://github.com/olafurpg/coursier-small/pull/9 has been merged, thank you @kamilkloch ! The next step is to expose this setting to sbt-scalafix somehow.

**Comment by kamilkloch** [comment]
@olafurpg please take a look if adding `scalafixResolvers` setting is the desired solution, or perhaps there is some other more elegant way.

**Comment by olafurpg** [comment]
Fixed in https://github.com/scalacenter/sbt-scalafix/pull/31

Thank you @kamilkloch ! This change will be included in the upcoming v0.9.1 release
