### ISSUE TITLE
Documentation typo in scalafixSourceroot setting key

### ISSUE THREAD

**Issue by 1krutarth** [scalacenter/scalafix#872]
Came across a quick typo in documentation when trying these commands: https://scalacenter.github.io/scalafix/docs/users/installation#settings-and-tasks.

| [scalafixSourceRoot](https://github.com/scalacenter/scalafix/blob/gh-pages/v0.5/docs/users/installation.html#L151) | File | The root directory of this project. |
|--------------------|------|-------------------------------------|

`scalafixSourceRoot` should actually be `scalafixSourceroot` (lowercase `r`) as mentioned against `scalametaSourceroot` row.

**Comment by olafurpg** [comment]
Thanks for reporting! The `scalafixSourceroot` setting has been removed from the latest milestone and the pending documentation for the new release no longer mentions this option https://olafurpg.github.io/scalafix/docs/users/installation.html
