### ISSUE TITLE
Respect -P:semanticdb:exclude

### ISSUE THREAD

**Issue by abdheshkumar** [scalacenter/scalafix#875]
Reproduce:
```scala
class DefineImplicits() extends scala.annotation.StaticAnnotation {

  // scalafix:off
  inline def apply(defn: Any): Any = meta { 
...
}
//// scalafix:on
```

https://gitter.im/scalacenter/scalafix?at=5ba395ea5df5194734e91fef
Error:
```scala
 error: ; expected but def found
[error]   inline def apply(defn: Any): Any = meta {
```

**Comment by gabro** [comment]
I think this is https://github.com/scalameta/scalameta/issues/1038 (which has been closed but it's not fixed)

**Comment by abdheshkumar** [comment]
Is there a workaround? @gabro It is still not working after excluding file.
```scala
unmanagedSources.in(Compile, scalafix) := unmanagedSources.in(Compile).value.filterNot(file =>file.getName.contains("Macros"))
here Macros is Macros.scala file that has macro related code.
```

**Comment by gabro** [comment]
As a workaround, you can add a dummy statement before the `inline` statement:

```scala
class DefineImplicits() extends scala.annotation.StaticAnnotation {
  val dummy = 42
  // scalafix:off
  inline def apply(defn: Any): Any = meta { 
  // ...
}
```

This works because the bug only happens when `inline` starts a template (a template is scalac lingo for an `extends A { ... }` clause

**Comment by gabro** [comment]
(I'm tracking the new issue here https://github.com/scalameta/scalameta/issues/1776)

**Comment by abdheshkumar** [comment]
Ok, thank you @gabro Do you have an idea why it is not excluding file?

**Comment by gabro** [comment]
No, I have no idea. It could be that it still tries to parse the file before excluding it, but I'm not sure.

**Comment by abdheshkumar** [comment]
Ok thank you @gabro  but the workaround is not working. 
```scala
  val dummy = 42
  inline def apply(defn: Any): Any = meta { -}
```

**Comment by gabro** [comment]
is it the same exact error?

**Comment by abdheshkumar** [comment]
Yes, it is same.
```scala
error: ; expected but def found
[error]   inline def apply(defn: Any): Any = meta {
[error]          ^

```

**Comment by olafurpg** [comment]
@abdheshkumar Is the error reported during compilation or after running scalafix?

Either way, I am afraid that scalafix semantic rules won't work for source files where inline/meta macro annotations are used. It is not enough to exclude the file defining the macro but also all files where the macros are used.

The inline/meta macro annotations are no longer under development and it is recommended to use org.scalamacros:paradise annotations instead (which have been merged into the Scala compiler for 2.13).

To exclude a file from compilation with semanticdb-scalac, add the following to your build

```scala
scalacOptions += "-P:semanticdb:exclude:Macros"
```

To support the `inline` keyword in Scalafix, add the following to `.scalafix.conf`

```conf 
// .scalafix.conf
parser.inlineKeyword = true
```

**Comment by abdheshkumar** [comment]
@olafurpg thank you so much for the detailed reply. I am getting that error while running `scalafix RemoveUnused`

**Comment by abdheshkumar** [comment]
@olafurpg Looks like that error has gone now.
How to exclude multiple files here `scalacOptions += "-P:semanticdb:exclude:Macros"` . I have tried `scalacOptions += "-P:semanticdb:exclude:Macros, Schema"` but it doesn't work and it said bad scalacOption.
Another question, I have below code.
```scala
 // scalafix:off
    q"""
      Map(${cases: _*})
     """
    // scalafix:on
``` 
I am getting 
```scala
 error: repeated argument not allowed here
[error]       Map(${cases: _*})
[error]                    ^

```

**Comment by abdheshkumar** [comment]
I think, `scalacOptions += "-P:semanticdb:exclude:Macros|Schema" fixed the problems.

**Comment by olafurpg** [comment]
What happens if you change to `Map(..$cases)`? I have not seen that syntax before, it might be a parser bug but if you can use `..$` instead then that's a faster workaround.

**Comment by abdheshkumar** [comment]
@olafurpg thank you that trick solved `repeated argument not allowed here` error. With the help of you,I am able to run scalafix on project which use Macro.scala but not able to run scalafix on project where I have actual Macros.scala file. Below is the error which I am getting.
```scala
[info] Running scalafix on 22 Scala sources
[error] SemanticDB not found: META-INF/semanticdb/libraries/utils/shared/src/main/scala/utils/implicits/Macros.scala.semanticdb
[error] (Compile / scalafix) scalafix.sbt.ScalafixFailed: MissingSemanticdbError
[error] Total time: 18 s, completed 21-Sep-2018 01:10:05
sbt:utilities library> 
```
I have equired  scalacOptions enabled and semanticdb-scalac compile plugin.
```scala
sbt:utilities library> show scalacOptions 
[info] * -unchecked
[info] * -deprecation
[info] * -feature
[info] * -language:higherKinds
[info] * -Ypartial-unification
[info] * -Yrangepos
[info] * -Ywarn-unused-import
[info] * -P:semanticdb:exclude:Macros
[success] Total time: 9 s, completed 21-Sep-2018 01:13:33
sbt:utilities library> show libraryDependencies
[info] * org.spire-math:kind-projector:0.9.3:plugin->default(compile)
[info] * org.scalamacros:paradise:2.1.0:plugin->default(compile)
[info] * org.scalameta:paradise:3.0.0-M11:plugin->default(compile)
[info] * org.scalameta:semanticdb-scalac:4.0.0-RC1:plugin->default(compile)
```
Please, could you help me on this too?

**Comment by olafurpg** [comment]
Do you have the following settings enabled?

```
unmanagedSources.in(Compile, scalafix) := unmanagedSources.in(Compile).value.filterNot(file =>file.getName.contains("Macros"))
```

The error happens because "Macros.scala" is one of the 22 sources in the "Running scalafix on 22 Scala sources" message.

**Comment by olafurpg** [comment]
You can validate which files are processed by running `scalafix --verbose`.

**Comment by olafurpg** [comment]
I think the best solution here is to make scalafix respect the `-P:semanticdb:exclude` setting so that it will not be necessary to configure `unmanagedSources`. A related issue is #879

**Comment by olafurpg** [comment]
Pending fix https://github.com/scalacenter/scalafix/pull/885
