### ISSUE TITLE
Performance improvements in EscapeHatch

### ISSUE THREAD

**Issue by marcelocenerine** [scalacenter/scalafix#894]
Opening this ticket as a follow-up of #812 . The goal here is to identify possible hot-spots in the suppression mechanism and eventually address them.

### Profiling
I profiled `EscapeHatch` using jProfiler as well as manually adding instrumentation (aka `System.currentTimeMillis()`) to the main parts of the code:
  - `@SuppressWarnings` parsing
  - `scalafix:ok` parsing
  - `scalafix:on|off` parsing
  - `EscapeHatch.filter`

For this exercise, I used a very basic syntactic rule that just adds a comment to the top of each source file (doesn't perform tree traversal):
```scala
override def fix(implicit doc: SyntacticDocument): Patch = 
  Patch.addLeft(doc.tree, "/** Foo **/\n").atomic
```

... and ran Scalafix against the `spark` (3152 files) and `scala` (1626 files) repos:
`java -Xms2g -Xmx2g -jar scalafix-cli/target/scala-2.12/scalafix.jar --rules Foo --sourceroot <path to repo>`

Before running Scalafix, I disabled the optimizations implemented in #812 so that I could try out tweaks that benefited code with/without suppressions.

The figures shown below were collected after a single run of Scalafix against each repo (no warmup or anything as such). Proper benchmarking can be done at a later stage (maybe as part of a resulting PR).

#### Baseline:

| Repo   | Scalafix (total)   | `EscapeHatch` (total) | `:ok`         | `:on\|:off`   | `@`          | `filter`      | 
| ------ | ------- | ------------- | ------------- | ------------- | ------------ | ------------- |
| spark  | 61332ms | 29001ms (47%) | 10486ms (17%) | 264ms (0.4%)  | 6772ms (11%) | 11395ms (18%) |
| scala  | 32973ms | 14379ms (43%) | 5513ms (17%)  | 131ms (0.4%)  | 3086ms (9%)  | 5573ms (17%)  |

In both repos, the suppression algorithm accounts for almost 50% (!!!) of the total running time. What is common in the most expensive parts of the algorithm is that they traverse the scala.meta AST: `:on|:off` (once), `@SuppressWarnings` (once) and `filter` (twice).  `scala.meta.transversers.Traverser.apply` is by far the main hot spot:

![image](https://user-images.githubusercontent.com/1107367/46048612-2cd4ea00-c122-11e8-975d-566d95ca1700.png)

The call tree shows some additional work going on there that one might not expect (e.g. `unapply` calls on tree nodes not being pattern matched):

![image](https://user-images.githubusercontent.com/1107367/46048981-f39d7980-c123-11e8-92bb-c536609d170b.png)

The traversal logic seems to be generated by a macro: `scala.meta.internal.transversers.TraverserMacros`. Given that I'm not familiar with macros nor I have the background on the scalameta implementation, I just replaced it with a custom traverser to see what would happen. (@olafurpg I may need some input here)

#### Optimization 1: custom tree traverser

All calls to `Tree.foreach` and `Tree.collect` in `EscapeHatch` as well as in `ReplaceSymbolOps.naiveMoveSymbolPatch` and `ImportPatchOps.superNaiveImportPatchToTokenPatchConverter` (indirectly called by `EscapeHatch.filter`) were replaced by a custom traverser that recursively traverses the tree via `Tree.children`. This single change reduced 38-45% of the total running time:

| Repo   | Scalafix (total)   | `EscapeHatch` (total) | `:ok`         | `:on\|:off`   | `@`          | `filter`      |
| ------ | ------- | ------------- | ------------- | ------------- | ------------ | ------------- |
| spark  | 34049ms | 11070ms (32%) | 5782ms (17%)  | 270ms (0.8%)  | 2438ms (7%)  | 2504ms (7%)   |
| scala  | 20447ms | 5809ms (28%)  | 3152ms (15%)  | 108ms (0.5%)  | 1030ms (5%)  | 1448ms (7%)   |

Given that rules often traverse the scala.meta trees, such optimization could benefit them as well. 

#### Optimization 2: raw filter 

Next, I added back Olafur's optimization from #812. It turns out my https://github.com/scalacenter/scalafix/pull/812#issuecomment-419989408 was not 100% accurate. Indeed, that optimization does yield a great improvement in `EscapeHatch.filter` when the source file has no suppression:

| Repo   | Scalafix (total)   | `EscapeHatch` | `:ok`         | `:on\|:off`   | `@`          | `filter`      |
| ------ | ------- | ------------- | ------------- | ------------- | ------------ | ------------- |
| spark  | 32375ms | 8667ms (27%)  | 5846ms (18%)  | 279ms (0.8%)  | 2460ms (7%)  | 0ms (0%)      |
| scala  | 19585ms | 4382ms (22%)  | 3127ms (16%)  | 141ms (0.7%)  | 1050ms (5%)  | 0ms (0%)      |

#### Optimization 3: skip comments/annotation parsing

The part of my https://github.com/scalacenter/scalafix/pull/812#issuecomment-419989408 that is accurate takes a step further and reduces the cost of the suppression mechanism to ~0% when there is no suppression in a given source file:

| Repo   | Scalafix (total)   | `EscapeHatch` | `:ok`         | `:on\|:off`   | `@`          | `filter`      |
| ------ | ------- | ------------- | ------------- | ------------- | ------------ | ------------- |
| spark  | 27962ms | 0ms (0%)  | 0ms (0%)  | 0ms (0%)  | 0ms (0%)  | 0ms (0%)      |
| scala  | 17692ms | 0ms (0%)  | 0ms (0%)  | 0ms (0%)  | 0ms (0%)  | 0ms (0%)      |

Given that searching for a string in `Input.text` is much faster than traversing the AST, we could even do the former two or three times to be able to "short circuit" individual suppression methods rather than the "all or nothing" approach (see `FastPatch.hasSuppression`).

#### Further improvements:
- tree traversal (and `.children`) is still costly...
![image](https://user-images.githubusercontent.com/1107367/46050889-7deadb00-c12e-11e8-9f00-d22989030e42.png)
- `AssociatedComments` accounts for ~7% of the total execution time
![image](https://user-images.githubusercontent.com/1107367/46050853-41b77a80-c12e-11e8-8dd5-7c4351980e0d.png)
- `AnchoredEscapes` and `AnnotatedEscapes` could be potentially merged so that the scala.meta tree is traversed only once (trades off maintainability)
- Do more profiling taking source files that extensively use suppressions to try identify new hot spots

**Comment by olafurpg** [comment]
Great investigative work @marcelocenerine ! It is good to have confirmed with numbers that escape hatch is costly and also comforting to see that minor changes can yield nice speedups.

It's good to keep in mind that correctness has always taken priority over performance in Scalafix. I prefer correct automatic refactorings that take 1 minute to run over incorrect automatic refactorings that take 30 seconds or manual refactorings that take 1 hour!

> Optimization 1: custom tree traverser

I am surprised `.children` yielded such a huge performance improvement. This seems like a no-brainer PR to merge and already gives us most of the speedups.

> Given that searching for a string in Input.text is much faster than traversing the AST

Sidenote: we should strive for a solution to short circuit escape hatch without touching
`SyntacticDocument.tree`. The tree is parsed on demand so that rules can skip parsing a tree entirely when `input.text` does not match a particular pattern. Lazy parsing enables the speedup from 8 minutes to 2 minutes in the comment here https://github.com/scalacenter/scalafix/issues/810#issuecomment-415896113 

> we could even do the former two or three times to be able to "short circuit" individual suppression methods rather than the "all or nothing" approach 

Can you elaborate on this?

> tree traversal (and .children) is still costly...

I think I already know what part of `.children` can be optimized, it does inefficient list concats here https://github.com/scalameta/scalameta/blob/232d56a457f92582ca2cc1ac5a8f96780a8415f4/scalameta/common/shared/src/main/scala/scala/meta/internal/trees/TyperMacros.scala#L118-L144 

Down the road we can investigate why `Traverser.apply` is so slow. The `Traverser` implementation is autogenerated by a macro annotation and the generated code contains a large amount of pattern matching.

> Do more profiling taking source files that extensively use suppressions to try identify new hot spots

It would be interesting to see the numbers with a slightly modified benchmark:
```scala
override def fix(implicit doc: SyntacticDocument): Patch = 
  doc.tree.collect {
    case t @ Importee.Name(Name(name)) if name.contains("e") => Patch.removeImportee(t).atomic
  }.asPatch
```

This will trigger a fairly expensive computation to compute the token patches for each individual `removeImportee`. It might reveal that the escape hatch no longer a bottle-neck.

> AnchoredEscapes and AnnotatedEscapes could be potentially merged so that the scala.meta tree is traversed only once (trades off maintainability)

I'm not convinced this is worth it. It's expected that the tree will be traversed multiple times anyways by the rules.

**Comment by marcelocenerine** [comment]
>Can you elaborate on this?

Sure. Currently we only short circuit escape hatch (completely) if there is no suppression comment nor annotations in a given file. This could be made a bit smarter by short circuiting parts of the logic depending on what suppression method is applied to a file (assuming that cases where both methods are mixed are rare):
- if `scalafix:ok` is not found, we skip its parsing logic (and avoid traversing the tree once). Likewise for the `on|off` comments
- if `@SuppressWarnings` is not found, we skip its parsing logic (again, avoiding traversing the tree potentially for the 2nd time)
- if there is no suppression in the file at all, we short circuit `.filter` (this information would already be available)
This requires one or two additional passes in `Input.text` (which is cheap) but would increase the probability of avoiding triggering the most expensive parts of the code.


> think I already know what part of `.children` can be optimized, it does inefficient list concats 

I changed the implementation of `.children` to:
```scala
  def children[T](implicit T: c.WeakTypeTag[T]): c.Tree = {
    val buffer = q"_root_.scala.collection.mutable.ListBuffer.empty[Tree]"
    val acc = T.tpe.typeSymbol.asLeaf.fields.foldLeft(buffer)((acc, f) => f.tpe match {
        case TreeTpe(_) =>
          q"$acc += this.${f.sym}"
        case OptionTreeTpe(_) =>
          q"$acc ++= this.${f.sym}.toList"
        case ListTreeTpe(_) =>
          q"$acc ++= this.${f.sym}"
        case OptionListTreeTpe(_) =>
          q"$acc ++= this.${f.sym}.getOrElse(_root_.scala.collection.immutable.Nil)"
        case ListListTreeTpe(_) =>
          q"$acc ++= this.${f.sym}.iterator.flatten"
        case _ =>
          acc
      })
    q"$acc.result"
  }
```

...which is shorter and avoids all the list concats and intermediary lists (I can open a PR on scalameta later). This improved things a bit but there are still places worth taking a closer look (e.g. `TermApplyImpl.args`, `TermSelectImpl.qual`):

_* time measured without short circuiting escape hatch_

| Repo   | Scalafix (total)   | `EscapeHatch` (total) | `:ok`         | `:on\|:off`   | `@`          | `filter`      | 
| ------ | ------- | ------------- | ------------- | ------------- | ------------ | ------------- |
| spark  | 29857ms | 8918ms (30%) | 5084ms (17%) | 250ms (0.8%)  | 1921ms (6%) | 1597ms (5%) |
| scala  | 18399ms | 4667ms (25%) | 2558ms (14%)  | 135ms (0.7%)  | 857ms (4%)  | 1041ms (5%)  |

- spark: ~12% faster in total
- scala: ~10% faster in total


>Down the road we can investigate why `Traverser.apply` is so slow.

This would be rgreat as rules would also benefit from the speedup (and consequently improve the overall scalafix experience). I might take a stab at it.

>I'm not convinced this is worth it

That's my opinion too. Glad you agree.


I will open a PR in the coming days with the improvements I have and continue digging. I will also do the test you suggested with the modified rule. Stay tuned!

**Comment by marcelocenerine** [comment]
The current implementation of `.children` turned out to be a red herring. Luckily I did proper benchmarking with JMH and couldn't get the speedup I saw when running scalafix (in fact, I'm consistently getting the latest figures even without the change). 

The list concats are not too expensive after all. In fact, most `Tree` types don't perform concatenation or do it only once or twice (sometimes with an empty list which costs nothing): 
[children.macro.txt](https://github.com/scalacenter/scalafix/files/2453949/children.macro.txt). And due to an implementation detail of `List.++`, the current approach is actually faster than using `ListBuffer` in some cases: `List.++` iterates over the prefix whereas `ListBuffer` iterates over the suffix. Given that the prefix is usually shorter (one element), the cost of concatenation is the same as assigning an object reference. The only case where the new implementation is faster is for the `Tree` types that concatenates a non-empty list +2 times (e.g. `scala.meta.Term.Try` and `scala.meta.Defn.Def`).

Measuring this is a bit trick so what I did was:
- picked some types where `.children` does zero/few/many concatenations and measure the cost of calling `.children` on them.
- picked some random `*.scala` files with 3 (XS), 50 (S), 500 (M), 1000 (L) and 5800 (XL) lines of code and measured the cost of traversing the entire tree using the current and the proposed new implementation of `.children`. 
The source code is here https://github.com/marcelocenerine/scalameta-benchmark. Here are the numbers (best to compare them instead of considering each one alone):

```
[info] Benchmark                                    (size)              (treeType)  Mode  Cnt       Score       Error  Units
[info] ChildrenBenchmark.children_current              N/A    scala.meta.Term.Name  avgt   10       3.124 ±     0.012  ns/op
[info] ChildrenBenchmark.children_current              N/A  scala.meta.Term.Return  avgt   10       6.691 ±     0.537  ns/op
[info] ChildrenBenchmark.children_current              N/A   scala.meta.Term.Match  avgt   10      41.017 ±     0.243  ns/op
[info] ChildrenBenchmark.children_current              N/A      scala.meta.Term.If  avgt   10      13.517 ±     0.052  ns/op
[info] ChildrenBenchmark.children_current              N/A     scala.meta.Term.Try  avgt   10      76.432 ±     0.386  ns/op
[info] ChildrenBenchmark.children_current              N/A     scala.meta.Defn.Def  avgt   10    1425.630 ±     4.864  ns/op
[info] ChildrenBenchmark.children_new                  N/A    scala.meta.Term.Name  avgt   10       3.239 ±     0.012  ns/op
[info] ChildrenBenchmark.children_new                  N/A  scala.meta.Term.Return  avgt   10       8.308 ±     0.155  ns/op
[info] ChildrenBenchmark.children_new                  N/A   scala.meta.Term.Match  avgt   10     233.593 ±     1.219  ns/op
[info] ChildrenBenchmark.children_new                  N/A      scala.meta.Term.If  avgt   10      14.395 ±     0.077  ns/op
[info] ChildrenBenchmark.children_new                  N/A     scala.meta.Term.Try  avgt   10      38.538 ±     0.198  ns/op
[info] ChildrenBenchmark.children_new                  N/A     scala.meta.Defn.Def  avgt   10     349.966 ±     2.514  ns/op
[info] ChildrenTraversalBenchmark.children_current      XS                     N/A  avgt   10     274.482 ±     1.287  ns/op
[info] ChildrenTraversalBenchmark.children_current       S                     N/A  avgt   10    4149.738 ±    29.164  ns/op
[info] ChildrenTraversalBenchmark.children_current       M                     N/A  avgt   10  133791.890 ±   687.719  ns/op
[info] ChildrenTraversalBenchmark.children_current       L                     N/A  avgt   10  166421.263 ±  1764.272  ns/op
[info] ChildrenTraversalBenchmark.children_current      XL                     N/A  avgt   10  959360.739 ± 16086.024  ns/op
[info] ChildrenTraversalBenchmark.children_new          XS                     N/A  avgt   10     245.739 ±     1.668  ns/op
[info] ChildrenTraversalBenchmark.children_new           S                     N/A  avgt   10    4358.331 ±    39.276  ns/op
[info] ChildrenTraversalBenchmark.children_new           M                     N/A  avgt   10  106280.381 ±   422.182  ns/op
[info] ChildrenTraversalBenchmark.children_new           L                     N/A  avgt   10  154235.992 ±  4658.113  ns/op
[info] ChildrenTraversalBenchmark.children_new          XL                     N/A  avgt   10  979022.950 ± 24007.214  ns/op
```

The only case where there is a relevant speedup is for `Term.Try` and `Defn.Def` (already explained above). The results for the 2nd benchmark are mixed and inconclusive.

Therefore, I'm leaving this change out of my PR in scalameta.
