### ISSUE TITLE
A lint rule for M[_] <: List[_]

### ISSUE THREAD

**Issue by dwijnand** [scalacenter/scalafix#906]
See https://github.com/lampepfl/dotty/issues/1809, it would be lovely to have a lint rule for this.

**Comment by Jacoby6000** [comment]
Until this is an official rule, you can this pattern:

```regex
(\w+)\[_\]\s*<:\s*(\w+)\[_\]
```

and after #907 gets merged, you can use

```hocon
{
  "id" = "hktSubtypeOfExistential"
  "pattern" = "(\w+)\[_\]\s*<:\s*(\w+)\[_\]"
  "message" = "{$0} is attempting to express a higher-kinded type as a subtype of an existential type.  You probably meant {$1}[X] <: {$2}[X]"
}
```

To get a nicely detailed error message
