### ISSUE TITLE
multi-jvm support

### ISSUE THREAD

**Issue by hepin1989** [scalacenter/scalafix#917]
scalaifx can't detect multi-jvm tests.
eg:
akka.cluster.typed.MultiNodeTypedClusterSpec

**Comment by olafurpg** [comment]
Is multi-jvm an sbt configuration? In that case you can enable it the same way as with `IntegrationTest` https://scalacenter.github.io/scalafix/docs/users/installation.html#integration-tests

**Comment by hepin1989** [comment]
Hm then that can't be done with a simple command alias

**Comment by hepin1989** [comment]
Hm, let me go with a task.

**Comment by hepin1989** [comment]
```
object ScalafixForMultiNodeScalaTestPlugin extends AutoPlugin {
  override def trigger: PluginTrigger = allRequirements
  override def requires: Plugins = MultiNodeScalaTest
  override def projectSettings: Seq[Def.Setting[_]] =
    Seq(MultiJvm).flatMap(c => inConfig(c)(scalafixConfigSettings(c)))
}
```
fixed

**Comment by olafurpg** [comment]
That is a good workaround, thank you for sharing @hepin1989 👍
