### ISSUE TITLE
With safe guard for no fix?

### ISSUE THREAD

**Issue by hepin1989** [scalacenter/scalafix#918]
As in this PR :https://github.com/akka/akka/pull/26019 there are some code snips are used in docs too, which may be not used.

```scala
//#zip-with-index
import akka.stream.scaladsl.Source
//#zip-with-index
```

is there any chance that we could save workaround this with something like:

```scala
//#scalafix off
//#zip-with-index
import akka.stream.scaladsl.Source
//#zip-with-index
//#scalafix off
```

**Comment by marcelocenerine** [comment]
Hi @hepin1989 . If what you are trying to achieve is to make `RemoveUnused` skip some unused imports, then it should be possible with `scalafix:off` + `scalafix:on` or `scalafix:ok` comments: https://scalacenter.github.io/scalafix/docs/users/suppression.html#suppress-regions-with-scalafix-off-and-scalafix-on

Example:
```scala
// scalafix:off
//#zip-with-index
import akka.stream.scaladsl.Source
//#zip-with-index
// scalafix:on
```

Alternatively:
```scala
//#zip-with-index
import akka.stream.scaladsl.Source // scalafix:ok
//#zip-with-index
```

**Comment by hepin1989** [comment]
@marcelocenerine Thank you very much, sorry for that I did not look very into the document, let me close this issue for that's already supported.
