### ISSUE TITLE
In a single SBT session, changing file contents for a rule are not reflected

### ISSUE THREAD

**Issue by stephenjudkins** [scalacenter/scalafix#928]
To reproduce:
* Start SBT
* Add rule `a`
* Run `scalafix file:a`
* Change rule `a`
* Run `scalafix file:a`

Expected: changes made to `a` are reflected in the rule
Actual: The rule is run without reflecting the changes.

This bug is a consequence of https://github.com/olafurpg/metaconfig/issues/67, fixed in https://github.com/olafurpg/metaconfig/pull/66

**Comment by bjaglin** [comment]
@stephenjudkins I believe this is not reproducible with recent versions of scalafix?

**Comment by stephenjudkins** [comment]
Seems likely given a PR fix was on its way ~18 months ago, but I can't be sure given that metaconfig's issues and PRs seem to have been deleted

**Comment by stephenjudkins** [comment]
Looks like this probably fixed it: https://github.com/scalameta/scalameta/issues/1068

**Comment by mlachkar** [comment]
I tried to reproduce this issue, and I wasn't able to do so. I am closing this issue for now. Don't hesitate to open a new issue if you run into the same/another problem.
