### ISSUE TITLE
Scalafix doesn't download all the required jars (was Can't load class ScalafixImpl)

### ISSUE THREAD

**Issue by sideeffffect** [scalacenter/scalafix#930]
When using `sbt-scalafix` `0.9.1+2-4639946a-SNAPSHOT`, running `scalafix` fails with
```
java.lang.ClassNotFoundException: scalafix.internal.interfaces.ScalafixImpl
```

![image](https://user-images.githubusercontent.com/9019485/50827515-ef961000-133e-11e9-8258-46b4df018c54.png)

**Comment by sideeffffect** [comment]
it's quite likely because Scalafix actually doesn't download all `jar`s when downloading from a custom Nexus instance :(

comparison of downloading from custom Nexus instance (on the left) vs downloading from the default -- `repo1.maven.org` (on the right)

![image](https://user-images.githubusercontent.com/9019485/50838023-588c8080-135d-11e9-97f8-c90f2d4ec317.png)

most of the `jar`s are missing, even though no error was indicated by Scalafix while the downloading took place (it failed only when it tried to load the `ScalafixImpl` class). why is that?

**Comment by sideeffffect** [comment]
quite likely caused by coursier itself: https://github.com/coursier/coursier/issues/505

**Comment by sideeffffect** [comment]
I've submitted a PR for `coursier-small` over at https://github.com/olafurpg/coursier-small/pull/13 (@olafurpg could you please have a look at it if such a change even makes sense? I'm not very familiar with coursier...)
but @alexarchambault are you sure downloading optional artifacts would really help? because the missing `jar`s are definitely not optional, they're hard dependencies, only they weren't listed in the content of the Nexus' proxy directory

**Comment by olafurpg** [comment]
@sideeffffect Thanks for reporting and investigating! I am unable to reproduce the issue with `0.9.1+2-4639946a-SNAPSHOT` without custom resolvers. Is it correct that this error happens only with custom resolvers?

**Comment by alexarchambault** [comment]
If you feel like testing it, you can always spawn a Nexus mirror locally, like done [here](https://github.com/coursier/coursier/blob/06796458b576e9bd8a49f8b121c0048b257bc08f/scripts/launch-proxies.sh#L20-L24) (one of the `docker run` lines), and use it instead of Central.

**Comment by sideeffffect** [comment]
@olafurpg yes, this happens only with custom resolvers -- corporate Nexus proxy of `repo1.maven.org`

**Comment by sideeffffect** [comment]
I can gladly confirm, that `sbt-scalafix` [`0.9.1+4-85315e35-SNAPSHOT`](https://oss.sonatype.org/content/repositories/snapshots/ch/epfl/scala/sbt-scalafix_2.10_0.13/0.9.1+4-85315e35-SNAPSHOT/) successfully downloads *all* required jars if run against a Nexus proxy, and thus enables the use of Scalafix even behind corporate firewalls
:tada: 
thank you @olafurpg @alexarchambault !

**Comment by olafurpg** [comment]
@sideeffffect great news 👍 I'll try to get a release out before February, scalafix SNAPSHOT releases are effectively immutable because we update the version on every merge.

**Comment by sideeffffect** [comment]
> scalafix SNAPSHOT

I tested it (successfully) with that one. unfortunately I can't use a SNAPSHOT in build in our corporate environment :frowning_face: that's why I'm asking for a proper release...

**Comment by olafurpg** [comment]
Have you tried using the latest stable sbt-scalafix and add the following to `project/plugins.sbt`?

```scala
libraryDependencies += "com.geirsson" %% "coursier-small" ...
```

If not, you can try publishing a fork of scalafix to your corporate environment until the stable release is out. I wish it was faster to cut stable releases but it's more than clicking a few buttons, it usually takes a good afternoon when everything adds up.

**Comment by sideeffffect** [comment]
@olafurpg unfortunately upgrading just `coursier-small` doesn't fix [the problem with overriding repos in `sbt-scalafix` `0.9.1`](https://github.com/scalacenter/scalafix/issues/929)
so for me to deploy this, I would need a new release of `sbt-scalafix` 
but of course, I totally understand that it's elaborate process and you're busy :wink: 
thanks for your help so far

**Comment by alexarchambault** [comment]
@sideeffffect This might be an issue with the default sbt dependency resolution not selecting the latest version… Have you tried adding `sbt-coursier` in _both_ `project/plugins.sbt` and `project/project/plugins.sbt`, like described [here](https://get-coursier.io/docs/sbt-coursier.html#along-other-plugins)? There should be less issues of that kind with it…

**Comment by sideeffffect** [comment]
@alexarchambault nope, it's literally the problem that `sbt-scalafix` downloads packages from `repo1.maven.org` even though I specified different resolvers in my `build.sbt` via `scalafixCustomResolvers`.
This issue has already been fixed in `master`, but no new `sbt-scalafix` has been released since

**Comment by sideeffffect** [comment]
@olafurpg hi! do you think you could get a release out today or tomorrow?
thanks :slightly_smiling_face:

**Comment by olafurpg** [comment]
@sideeffffect v0.9.2 is out!

**Comment by sideeffffect** [comment]
@olafurpg I'm happy to report that it works as expected :smile: thank you so much!
