### ISSUE TITLE
POM contains wrong artifactId

### ISSUE THREAD

**Issue by sideeffffect** [scalacenter/scalafix#931]
the [`sbt-scalafix` POM](https://oss.sonatype.org/content/repositories/snapshots/ch/epfl/scala/sbt-scalafix_2.12_1.0/0.5.6/sbt-scalafix-0.5.6.pom) contains the wrong `artifactId`
```xml
<artifactId>sbt-scalafix</artifactId>
```

it should be
```xml
<artifactId>sbt-scalafix_2.12_1.0</artifactId>
```

(working example is [`zio`](https://oss.sonatype.org/content/repositories/releases/org/scalaz/scalaz-zio_2.12/0.5.3/scalaz-zio_2.12-0.5.3.pom) with `artifactId` `scalaz-zio_2.12`)

this probably causes issues with Nexus/badges: https://github.com/badges/shields/issues/2696

**Comment by olafurpg** [comment]
This is normal for how sbt plugins are published “maven style “. There’s not much we can do. The artifact name “sbt-scalafix” (without _2.12_1.0) might work instead.
