### ISSUE TITLE
Crash at creating new 'structural type' object

### ISSUE THREAD

**Issue by sideeffffect** [scalacenter/scalafix#935]
Scalafix crashes when it meets a code where a new object with a structural type is created.
something like
```scala
class Container[F[_]](implicit F: Effect[F]) {
  lazy val b = ???
  lazy val s = for {
    a <- aF
    c = ???
  } yield
    new {
      lazy val ccc = c
      lazy val aaa = a
    }
}
```

it throws `internal.v1.FileException`:

![image](https://user-images.githubusercontent.com/9019485/51559058-39bfdb00-1e81-11e9-81d4-12f7a48c96aa.png)

**Comment by NeQuissimus** [comment]
Just encountered this as well

**Comment by olafurpg** [comment]
The stack trace from the original issue points to `ExplicitResultType`, which was an experimental/undocumented rule until the last release a couple weeks ago. 

The `unsafeToType` method call is no longer used by this rule, so I suspect it's fixed now.

@NeQuissimus Please open a new issue
