### ISSUE TITLE
Impossible to completely override scalafixResolvers

### ISSUE THREAD

**Issue by danslapman** [scalacenter/scalafix#937]
Problem:
I need to use custom resolvers in my environment (maven central is proxied & inaccessible). Setting `scalafixResolvers := resolvers.map(repo => new Maven(repo.root))` doesn't change coursiersmall's behavior, I still experience ResolutionExceptions like that:
```
com.geirsson.coursiersmall.ResolutionException: Failed to resolve Settings(
[error]   dependencies  = List(Dependency("ch.epfl.scala", "scalafix-cli_2.12.7", "0.9.2"))
[error]   repositories  = List(Ivy2Local, Maven("https://repo1.maven.org/maven2"), Maven("https://oss.sonatype.org/content/repositories/releases"), Maven("https://oss.sonatype.org/content/repositories/snapshots"))
[error]   ttl           = Some(Duration.Inf)
[error]   forceVersions = List(Dependency("ch.epfl.scala", "scalafix-cli_2.12.7", "0.9.2"))
[error] )
[error] Dependency 'com.google.protobuf:protobuf-java:3.5.1'
[error]   not found: /Users/***/.ivy2/local/com.google.protobuf/protobuf-java/3.5.1/ivys/ivy.xml
[error]   download error: Caught java.io.IOException: Server returned HTTP response code: 403 for URL: https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.5.1/protobuf-java-3.5.1.pom (Server returned HTTP response code: 403 for URL: https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.5.1/protobuf-java-3.5.1.pom) while downloading https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.5.1/protobuf-java-3.5.1.pom
[error]   not found: https://oss.sonatype.org/content/repositories/releases/com/google/protobuf/protobuf-java/3.5.1/protobuf-java-3.5.1.pom
[error]   not found: https://oss.sonatype.org/content/repositories/snapshots/com/google/protobuf/protobuf-java/3.5.1/protobuf-java-3.5.1.pomDependency 'org.sonatype.oss:oss-parent:7'
```

**Comment by olafurpg** [comment]
Thanks for reporting! What version are you using? This might be fixed in v0.9.2 released yesterday

**Comment by danslapman** [comment]
I tried 0.9.1, then upgraded to 0.9.2, upgrade did not fix this issue

**Comment by danslapman** [comment]
Hmm, what's difference between `scalafixResolvers` and `scalafixCustomResolvers`, which one should I use?

**Comment by olafurpg** [comment]
@sideeffffect any thoughts on how to use sbt-scalafix with custom resolvers?

**Comment by danslapman** [comment]
By the way, why not simply use project resolvers, why `scalafixResolvers` exists at all?

**Comment by danslapman** [comment]
`scalafixResolvers in ThisBuild` solved my problem :)

**Comment by sideeffffect** [comment]
@danslapman

> `in ThisBuild`

:tada: 
that's exactly how I've used it

**Comment by sideeffffect** [comment]
> scalafixResolvers and scalafixCustomResolvers

old name and new name of the same thing:
https://github.com/scalacenter/sbt-scalafix/commit/141a39f82525e853b235bd1d5fa209563259068b

**Comment by sideeffffect** [comment]
basically it's a mistake in the documentation: https://github.com/scalacenter/scalafix/issues/938
