### ISSUE TITLE
Add an sbt task to download all dependencies needed to run scalafix ?

### ISSUE THREAD

**Issue by smarter** [scalacenter/scalafix#946]
I have a docker image in which I compile Scala code, to avoid downloading the dependencies of every project again and again, I run something like `sbt test:update` in the Dockerfile to prepopulate the cache, but that's not enough to download the dependencies that sbt-scalafix fetches at runtime using coursier, so I need to do `sbt "scalafix --version"` too, I wish there was a `scalafixUpdate` task or something to do this more explicitly.

**Comment by olafurpg** [comment]
Thanks for reporting! What would be the benefit of `scalafixUpdate` over `sbt "scalafix --help"`?

**Comment by smarter** [comment]
`scalafixUpdate` is self-documenting using a flag is less obviously correct.

**Comment by olafurpg** [comment]
Closing as wontfix, a workaround is to run `scalafix --help`
