### ISSUE TITLE
Using scalafix --rules file:<path> returns scalafix.sbt.InvalidArgument: Type mismatch

### ISSUE THREAD

**Issue by RCMartins** [scalacenter/scalafix#948]
I cloned https://github.com/olafurpg/named-literal-arguments and followed the tutorial until the `Run the rule from source code` part.
I tried using `scalafix --rules file:/path/to/NamedLiteralArguments.scala` command in some projects and I always get the same cryptic error:
```
> scalafix --rules file:/Users/ricardo/Documents/named-literal-arguments/scalafix/rules/src/main/scala/fix/NamedLiteralArguments.scala
[error] (Compile / scalafix) scalafix.sbt.InvalidArgument: Type mismatch;
[error]   found    : Boolean (value: true)
[error]   expected : List[java.lang.String]
[error] Total time: 0 s, completed Feb 20, 2019 3:43:53 PM
```
Also tried with NoLiteralArguments.scala, which is only a syntactic rule, but got the same error.
The only thing I did to my project was adding the scalafix sbt plugin to the project/plugins.sbt:
```addSbtPlugin("ch.epfl.scala" % "sbt-scalafix" % "0.9.4")```

**Comment by berrytj** [comment]
@RCMartins i ran into this and putting `=` after `rules` seems to fix it:
```scalafix --rules=file:/path/to/rules```
