### ISSUE TITLE
Document Disable.symbols

### ISSUE THREAD

**Issue by jatcwang** [scalacenter/scalafix#950]
This is a very useful feature for linting that doens't seem to be documented currently.

Should mention how it works in the context of inheritance. (From my experiment it seems like you need to list the method which actually has an implementation)

I'm happy to help with this but I'll need some help regarding ^ :)

**Comment by olafurpg** [comment]
Thanks for reporting! There is no published `Disable` rule, this functionality was moved to a separate project https://github.com/vovapolu/scaluzzi

**Comment by jatcwang** [comment]
Oh sorry, I saw a `Disable` class (https://github.com/scalacenter/scalafix/blob/master/scalafix-tests/unit/src/test/scala/scalafix/tests/cli/Disable.scala) and thought it was in already. Closing.

**Comment by jatcwang** [comment]
Oh sorry, I saw a `Disable` class (https://github.com/scalacenter/scalafix/blob/master/scalafix-tests/unit/src/test/scala/scalafix/tests/cli/Disable.scala) and thought it was in already. Closing.

**Comment by olafurpg** [comment]
No worries, I looked myself and also thought for a moment it was published 😅
