### ISSUE TITLE
How to configure the Scala dialect?

### ISSUE THREAD

**Issue by OlivierBlanvillain** [scalacenter/scalafix#954]
Is there a way to configure scalafix to use another Scala dialect?

**Comment by olafurpg** [comment]
Thanks for reporting! It's possible to disable/enable trailing command and the `inline` keyword, but not more than that. What Scala syntax are you interested in using? The Scalameta Dotty dialect is quite far behind the latest Dotty syntax.

**Comment by OlivierBlanvillain** [comment]
Then this might be a blocker for using scalafix on Dotty source code because of the change in Varargs pattern syntax:

```scala
case Seq(1, 2, xs: _*) =>
```

**Comment by olafurpg** [comment]
That particular syntax we already support in the parser and it would be easy to expose an option to enable it. I'm hesitant to call the option "enable dotty syntax" or something similar because the parser still won't understand enums or other new features.

**Comment by OlivierBlanvillain** [comment]
Makes sense. It would still be useful for us because the class doesn't use any of the new dotty features, but so far we still got away without putting the `-language:scala2` flag in the student build...

**Comment by bjaglin** [comment]
Since https://github.com/scalacenter/scalafix/pull/1409, the dialect is derived from `--scala-version` or the `-Xsource` `--scalac-options` when present.
