### ISSUE TITLE
scalafix to ignore .scalafix.conf while running help or version

### ISSUE THREAD

**Issue by Prithvirajbilla** [scalacenter/scalafix#957]
It's little annoying to see scalafix --help error out because I didn't pass a tool-classpath for custom rules.jar.
```
[nix-shell:~]$ scalafix --version
error: Unknown rule 'NoLiteralArguments'

[nix-shell:~]$ scalafix --help
error: Unknown rule 'NoLiteralArguments'
```
I would just expect --version or --help to work irrespective of the rules defined in scalafix.conf

**Comment by ches** [comment]
Perhaps related to #933
