### ISSUE TITLE
Running a SemanticRule on a string in code

### ISSUE THREAD

**Issue by dr-thunder** [scalacenter/scalafix#965]
I am trying to use scalafix from within code rather than as a cli tool. Is it possible to build a SemanticDocument within Scala from a string and run a SemanticRule on it? I am looking to get similar behaviour to runAllTests() in RuleSuite, but with public access to the results.

**Comment by bjaglin** [comment]
Following-up in https://github.com/scalacenter/scalafix/issues/1236
