### ISSUE TITLE
Organise imports

### ISSUE THREAD

**Issue by mwz** [scalacenter/scalafix#966]
It seems that scalafix used to be able to organise imports (#46), but this functionality seems to have been removed (or it was never completed?). Do you have any plans to bring organising imports to scalafix in the near future? I'm asking in the context of being able to integrate this into metals further down the line (https://github.com/scalameta/metals-feature-requests/issues/7), but obviously before that is going to be possible this functionality first needs to be implemented in this project as a standalone rule.

Is there any existing discussion about this feature where others can get involved? Have you guys discussed this already and do you have any ideas on how this could be implemented? Are there any technical limitations in scalafix or scalameta/semanticdb that would block this work?

**Comment by LukaszByczynski** [comment]
There is plugin for that: https://github.com/NeQuissimus/sort-imports

**Comment by bjaglin** [comment]
See also https://github.com/liancheng/scalafix-organize-imports

**Comment by bjaglin** [comment]
I am closing this as the 2 suggestions above are hopefully mature enough to cover your needs, and the specific metals needs are handled in https://github.com/scalameta/metals-feature-requests/issues/40#issuecomment-616419526.
