### ISSUE TITLE
Scala scripts producing expected class or object definition error

### ISSUE THREAD

**Issue by urbanchr** [scalacenter/scalafix#968]
I like to use Scalafix to enforce immutablity properties in my students code, for example no vars, returns and so on are allowed. My students submit Scala scripts that can run directly in the REPL. In this way, they do not contain an outer object. So when I use Scalafix with custom rules in order to pick out vars, I always receive an error like

error: expected class or object definition
def charlist2rexp(s : List[Char]): Rexp = s match {

Is there a way to disable this outer-class check so that scalafix does not complain about this? I could not see whether there is any option in the configuration for such a test. 

It has been suggested that this error can be avoided when the file extension is .sc rather than .scala. But also this does not work, since I now get an "error"

error: No files to fix
  
If possible, I like to have an explicit switch in the rules file, than having to rename the files to .sc.

**Comment by bjaglin** [comment]
Following-up in https://github.com/scalacenter/scalafix/issues/1534
