### ISSUE TITLE
Credentials support for custom resolvers

### ISSUE THREAD

**Issue by tuures** [scalacenter/scalafix#984]
I've pointed `scalafixResolvers` to a private Maven artifactory that requires authentication. Credentials are set in SBT the usual way, but it seems Scalafix is not using those. Would be very beneficial to be able to set up authentication for `scalafixResolvers`.

**Comment by olafurpg** [comment]
Thank you for reporting! This would be a nice improvement. This would need to be implemented in the sbt-scalafix repository https://github.com/scalacenter/sbt-scalafix. Currently, sbt-scalafix uses a library called coursier-small to perform the dependency resolution, which doesn't support authentication. Given this limitation in coursier-small, the fix would also need to port our usage from coursier-small to the new coursier/interface library from https://github.com/coursier/interface. The APIs should be similar so I don't think it will require a large change.

**Comment by olafurpg** [comment]
I took a stab at migrating to coursier/interface in https://github.com/scalacenter/sbt-scalafix/pull/43. Once that is merged, it should be simple to add support for credentials
