### ISSUE TITLE
sbt-scalafix regression between 0.9.7 and 0.9.8

### ISSUE THREAD

**Issue by mcanlas** [scalacenter/scalafix#991]
Doing a point-upgrade on `sbt-scalafix` and suddenly getting this error. Not sure what it means or what it is caused by.

```scala
error: Type mismatch;
  found    : Map[K, V] (value: {"scalaVersion": "2.13.0"})
  expected : scalaVersion=2.12.10
```

I think it is only happening on our repos which are running Scala 2.13.

**Comment by olafurpg** [comment]
Thank you for reporting! Can you please include your Scalafix config?

**Comment by charles-rumley** [comment]
We're seeing the same issue with 2.13.1. Here's our config:

```
rules = [
  ExplicitResultTypes
  LeakingImplicitClassVal
  RemoveUnused
  DisableSyntax
  LeakingImplicitClassVal
  NoValInForComprehension
  ProcedureSyntax
]

ExplicitResultTypes {
  unsafeShortenNames = true
}

DisableSyntax {
  noVars = false
  noThrows = false
  noNulls = false
  noReturns = true
  noWhileLoops = true
  noAsInstanceOf = true
  noIsInstanceOf = true
  noXml = true
  noFinalVal = true
  noFinalize = true
  noValPatterns = false
  noUniversalEquality = false
}

```

**Comment by olafurpg** [comment]
@charles-rumley the `ExplicitResultTypes` rewrite does not support 2.13 at this point. A workaround is to remove the rule from the configuration.

**Comment by olafurpg** [comment]
FWIW, the `ExplicitResultTypes` rule was not officially supported in the previous release BTW, it was not documented on the website and it did not appear in tab completions.

**Comment by charles-rumley** [comment]
I see, too bad.

Can confirm that removing the `ExplicitResultTypes` rule does fix this issue though, thanks for the quick response!

**Comment by olafurpg** [comment]
It should be totally possible to support this rule in 2.13. It just requires a bit more extra work than usual due to how the rule is implemented now.

**Comment by olafurpg** [comment]
Superseded by #998. A workaround for now is to

* use Scala 2.12.10 or
* disable the `ExplicitResultTypes` rule
