### ISSUE TITLE
DisableSyntax.noValPatterns should allow for single `_` as pattern

### ISSUE THREAD

**Issue by seigert** [scalacenter/scalafix#992]
Sometimes you just want to explicitly show that function return value will be discarded like `val _ = server.start()`. Currently it ends up a lint error:
```
[DisableSyntax.noValPatterns] Pattern matching in val assignment can result in match error, use "_ match { ... }" with a fallback case instead.
     val _ = server.start()
```

But there is nothing to fallback to, as `_` will match everything.

**Comment by olafurpg** [comment]
Thank you for reporting! I agree this pattern should not report an error. A PR is welcome to fix this issue

**Comment by seigert** [comment]
PR is ready.
