### ISSUE TITLE
sbt-scalafix 0.9.9 not published?

### ISSUE THREAD

**Issue by dwickern** [scalacenter/scalafix#995]
The [documentation](https://scalacenter.github.io/scalafix/docs/users/installation.html#sbt) says to use sbt-scalafix 0.9.9 with Scala 2.12.10. I can't find it on Central:

https://repo1.maven.org/maven2/ch/epfl/scala/sbt-scalafix_2.12_1.0/

**Comment by olafurpg** [comment]
Thank you for reporting! I opened https://github.com/scalacenter/sbt-scalafix/pull/45 to release an sbt-scalafix upgrade

**Comment by olafurpg** [comment]
sbt-scalafix 0.9.9 is now released!
