### ISSUE TITLE
scalafixEnable does not install semanticdb-scalac when scalaVersion is 2.13.x

### ISSUE THREAD

**Issue by fthomas** [scalacenter/scalafix#997]
`scalafixEnable` does not add the `semanticdb-scalac` plugin to `libraryDependencies` when `scalaVersion` is `2.13.x`:
```
$ sbt ";++2.12.10 ;scalafixEnable; libraryDependencies"
...
[info] * org.scala-lang:scala-library:2.12.10
[info] * org.scalatest:scalatest:3.0.8
[info] * org.scalameta:semanticdb-scalac:4.2.3:plugin->default(compile)

$ sbt ";++2.13.1 ;scalafixEnable; libraryDependencies"
...
[info] * org.scala-lang:scala-library:2.13.1
[info] * org.scalatest:scalatest:3.0.8
```
This can be reproduced in this [project](https://github.com/fthomas/scalafix-issue). It seems that this is the reason why a subsequent `scalafix` call works with 2.12.x but fails with 2.13.x with the following error:
```
$ sbt ";++2.13.1 ;scalafixEnable ;test:scalafix https://raw.githubusercontent.com/scalatest/autofix/e4de53fa40fac423bd64d165ff36bde38ce52388/3.0.x/rules/src/main/scala/org/scalatest/autofix/v3_0_x/RenameDeprecatedPackage.scala"
...
[error] (Test / scalafix) scalafix.sbt.InvalidArgument: The semanticdb-scalac compiler plugin is required to run semantic rules like RenameDeprecatedPackage.
[error] To fix this problem for this sbt shell session, run `scalafixEnable` and try again.
[error] To fix this problem permanently for your build, add the following settings to build.sbt:
[error]   addCompilerPlugin(scalafixSemanticdb)
[error]   scalacOptions += "-Yrangepos"
```
Adding `addCompilerPlugin(scalafixSemanticdb)` manually to the `build.sbt` makes the above `scalafix` work.

**Comment by olafurpg** [comment]
Thank you for reporting! This should be fixed in https://github.com/scalacenter/sbt-scalafix/pull/46

**Comment by fthomas** [comment]
Awesome, many thanks for the quick fix, Olaf!

**Comment by olafurpg** [comment]
I triggered a v0.9.11 release of sbt-scalafix, which should include support for 2.13 in `scalafixEnable`

**Comment by fthomas** [comment]
Thanks @olafurpg, I can confirm that 0.9.11 fixes this issue.

**Comment by olafurpg** [comment]
Thanks for confirming!
