### ISSUE TITLE
Make ExplicitResultTypes work with more Scala versions

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/scalafix#998]
Unlike other rules, `ExplicitResultTypes` only works with Scala 2.12.10 at the moment because the rule interfaces directly with the presentation compiler. It would be great if we could add support for Scala 2.13 and 2.11 but doing so would require rethinking how rules are compiled/published/launched.

* should Scalafix rules be cross-built against multiple Scala versions if they want to use the presentation compiler API? This would require changing sbt-scalafix to launch the correct Scalafix version (2.11/2.12/2.13) depending on the project being fixed.
* should Scalafix provide an Java-API on top of the presentation compiler allowing 2.12-compiled rules to work with 2.13/2.11? We use this approach in Metals (the server runs in 2.12, but completions work with 2.11/2.12/2.13).

I'm inclined to do the second approach since I like that Scalafix rules can work regardless of the Scala version being fixed. Regardless of the approach we use, I estimate it will require non-trivial work to implement.

**Comment by mlachkar** [comment]
in 2.13, instead of Serializable, the type found is AnyRef.

  val access: Serializable = new Serializable {
    private val results: List[Int] = List.empty
    protected val results2: List[Int] = List.empty
  }

**Comment by bjaglin** [comment]
@mlachkar not sure I follow, you mean that the rule as it's currently written has some bugs specific to scala 2.13? Is that a case of https://github.com/scalacenter/sbt-scalafix/pull/121#issuecomment-638404680 ?

**Comment by mlachkar** [comment]
When I cross compiled this rule to 2.13, this test broke. This rule is not working for all cases that were supported in 2.12. 
I was not able to fix all rules, and I thought I will do this work in other PRs before v1.

**Comment by bjaglin** [comment]
Ah ok, makes sense! Sorry, I hadn't seen https://github.com/scalacenter/scalafix/tree/master/scalafix-tests/input/src/main/scala/test/explicitResultTypes vs https://github.com/scalacenter/scalafix/tree/master/scalafix-tests/input/src/main/scala-2.12/test/explicitResultTypes.
